volumes:
  attachments:

services:
  kpi-api:
    container_name: kepegawaian-be-dev
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    image: kepegawaian:dev
    volumes:
      - attachments:/app/attachments
    ports:
      - "8080:8080"

