package id.perumdamts.kepegawaian.services.setupMaster;

import id.perumdamts.kepegawaian.entities.master.*;
import id.perumdamts.kepegawaian.repositories.master.ProfesiRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class SetupProfesi implements SetupMaster {
    @Autowired
    private ProfesiRepository profesiRepository;

    @Override
    public void insertBatch() {
        List<Profesi> list = new ArrayList<>();
        list.add(new Profesi(1L, "Manajer Satuan Pengawas Intern","-","-", new Organisasi(5L), new Jabatan(5L), new Level(4L), new Grade(1L)));
        list.add(new Profesi(2L, "Manajer Cabang Purwokerto 1","-","-", new Organisasi(8L), new Jabatan(10L), new Level(4L), new Grade(3L)));
        list.add(new Profesi(3L, "Manajer Cabang Purwokerto 2","-","-", new Organisasi(12L), new Jabatan(17L), new Level(4L), new Grade(2L)));
        list.add(new Profesi(4L, "Manajer Cabang Banyumas","-","-", new Organisasi(16L), new Jabatan(24L), new Level(4L), new Grade(2L)));
        list.add(new Profesi(5L, "Manajer Cabang Wangon","-","-", new Organisasi(20L), new Jabatan(31L), new Level(4L), new Grade(1L)));
        list.add(new Profesi(6L, "Manajer Cabang Ajibarang","-","-", new Organisasi(24L), new Jabatan(38L), new Level(4L), new Grade(1L)));
        list.add(new Profesi(7L, "Manajer Unit Bisnis AMDK","-","-", new Organisasi(28L), new Jabatan(45L), new Level(4L), new Grade(1L)));
        list.add(new Profesi(8L, "Manajer Kesekretariatan","-","-", new Organisasi(45L), new Jabatan(50L), new Level(4L), new Grade(1L)));
        list.add(new Profesi(9L, "Manajer Keuangan","-","-", new Organisasi(49L), new Jabatan(58L), new Level(4L), new Grade(1L)));
        list.add(new Profesi(10L, "Manajer Sumber Daya Manusia & TI","-","-", new Organisasi(53L), new Jabatan(65L), new Level(4L), new Grade(1L)));
        list.add(new Profesi(11L, "Manajer Perlengkapan","-","-", new Organisasi(57L), new Jabatan(72L), new Level(4L), new Grade(2L)));
        list.add(new Profesi(12L, "Manajer Perencanaan & Pengembangan","-","-", new Organisasi(31L), new Jabatan(79L), new Level(4L), new Grade(2L)));
        list.add(new Profesi(13L, "Manajer Produksi & Distribusi 1","-","-", new Organisasi(35L), new Jabatan(86L), new Level(4L), new Grade(2L)));
        list.add(new Profesi(14L, "Manajer Produksi & Distribusi 2","-","-", new Organisasi(38L), new Jabatan(91L), new Level(4L), new Grade(2L)));
        list.add(new Profesi(15L, "Manajer Pengendalian Teknik","-","-", new Organisasi(41L), new Jabatan(96L), new Level(4L), new Grade(2L)));
        list.add(new Profesi(16L, "Supervisor Audit Intern","-","-", new Organisasi(6L), new Jabatan(6L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(17L, "Supervisor Standardisasi","-","-", new Organisasi(7L), new Jabatan(8L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(18L, "Supervisor Adm & Keu Cab. Pwkt 1","-","-", new Organisasi(9L), new Jabatan(11L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(19L, "Supervisor Pelayanan Cab. Pwkt 1","-","-", new Organisasi(10L), new Jabatan(13L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(20L, "Supervisor Teknik Cab. Pwkt 1","-","-", new Organisasi(11L), new Jabatan(15L), new Level(5L), new Grade(3L)));
        list.add(new Profesi(21L, "Supervisor Adm & Keu Cab. Pwkt 2","-","-", new Organisasi(13L), new Jabatan(18L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(22L, "Supervisor Pelayanan Cab. Pwkt 2","-","-", new Organisasi(14L), new Jabatan(20L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(23L, "Supervisor Teknik Cab. Pwkt 2","-","-", new Organisasi(15L), new Jabatan(22L), new Level(5L), new Grade(3L)));
        list.add(new Profesi(24L, "Supervisor Adm & Keu Cab. Banyumas","-","-", new Organisasi(17L), new Jabatan(25L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(25L, "Supervisor Pelayanan Cab. Banyumas","-","-", new Organisasi(18L), new Jabatan(27L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(26L, "Supervisor Teknik Cab. Banyumas","-","-", new Organisasi(19L), new Jabatan(29L), new Level(5L), new Grade(3L)));
        list.add(new Profesi(27L, "Supervisor Adm & Keu Cab. Wangon","-","-", new Organisasi(21L), new Jabatan(32L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(28L, "Supervisor Pelayanan Cab. Wangon","-","-", new Organisasi(22L), new Jabatan(34L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(29L, "Supervisor Teknik Cab. Wangon","-","-", new Organisasi(23L), new Jabatan(36L), new Level(5L), new Grade(3L)));
        list.add(new Profesi(30L, "Supervisor Adm & Keu Cab. Ajibarang","-","-", new Organisasi(25L), new Jabatan(39L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(31L, "Supervisor Pelayanan Cab. Ajibarang","-","-", new Organisasi(26L), new Jabatan(41L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(32L, "Supervisor Teknik Cab. Ajibarang","-","-", new Organisasi(27L), new Jabatan(43L), new Level(5L), new Grade(3L)));
        list.add(new Profesi(33L, "Supervisor Pemasaran","-","-", new Organisasi(30L), new Jabatan(46L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(34L, "Supervisor Produksi","-","-", new Organisasi(29L), new Jabatan(48L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(35L, "Supervisor Hukum & Perizinan","-","-", new Organisasi(46L), new Jabatan(51L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(36L, "Supervisor Humas & Protokol","-","-", new Organisasi(47L), new Jabatan(53L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(37L, "Supervisor Tata Usaha & Rumah Tangga","-","-", new Organisasi(48L), new Jabatan(55L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(38L, "Supervisor Akuntansi","-","-", new Organisasi(50L), new Jabatan(59L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(39L, "Supervisor Anggaran & Pelaporan","-","-", new Organisasi(51L), new Jabatan(61L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(40L, "Supervisor Perbendaharaan","-","-", new Organisasi(52L), new Jabatan(63L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(41L, "Supervisor Adm. & Pengembangan SDM","-","-", new Organisasi(54L), new Jabatan(66L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(42L, "Supervisor Remunerasi & K3","-","-", new Organisasi(55L), new Jabatan(68L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(43L, "Supervisor Teknologi Informasi","-","-", new Organisasi(56L), new Jabatan(70L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(44L, "Supervisor Aset","-","-", new Organisasi(58L), new Jabatan(73L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(45L, "Supervisor Pengadaan","-","-", new Organisasi(59L), new Jabatan(75L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(46L, "Supervisor Persediaan","-","-", new Organisasi(60L), new Jabatan(77L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(47L, "Supervisor Perencanaan","-","-", new Organisasi(32L), new Jabatan(80L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(48L, "Supervisor Pengembangan","-","-", new Organisasi(33L), new Jabatan(82L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(49L, "Supervisor Pengawasan Pekerjaan","-","-", new Organisasi(34L), new Jabatan(84L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(50L, "Supervisor Pengendalian Produksi 1","-","-", new Organisasi(36L), new Jabatan(87L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(51L, "Supervisor Pengendalian Distribusi 1","-","-", new Organisasi(37L), new Jabatan(89L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(52L, "Supervisor Pengendalian Produksi 2","-","-", new Organisasi(39L), new Jabatan(92L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(53L, "Supervisor Pengendalian Distribusi 2","-","-", new Organisasi(40L), new Jabatan(94L), new Level(5L), new Grade(2L)));
        list.add(new Profesi(54L, "Supervisor Mekanikal & Elektrikal","-","-", new Organisasi(42L), new Jabatan(97L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(55L, "Supervisor Pengendalian Kehilangan Air","-","-", new Organisasi(43L), new Jabatan(100L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(56L, "Supervisor Penjaminan Mutu Air","-","-", new Organisasi(44L), new Jabatan(102L), new Level(5L), new Grade(1L)));
        list.add(new Profesi(57L, "Staf Sub Bag. Audit Intern","-","-", new Organisasi(6L), new Jabatan(7L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(58L, "Staf Sub Bag. Standardisasi","-","-", new Organisasi(7L), new Jabatan(9L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(59L, "Staf Sub Bag. Adm & Keu Cab. Pwkt 1","-","-", new Organisasi(9L), new Jabatan(12L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(60L, "Staf Sub Bag. Pelayanan Cab. Pwkt 1","-","-", new Organisasi(10L), new Jabatan(14L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(61L, "Staf Sub Bag. Teknik Cab. Pwkt 1 (PTM)","-","-", new Organisasi(11L), new Jabatan(16L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(62L, "Staf Sub Bag. Teknik Cab. Pwkt 1 (PMS)","-","-", new Organisasi(11L), new Jabatan(16L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(63L, "Staf Sub Bag. Teknik Cab. Pwkt 1 (PJ)","-","-", new Organisasi(11L), new Jabatan(16L), new Level(6L), new Grade(4L)));
        list.add(new Profesi(64L, "Staf Sub Bag. Teknik Cab. Pwkt 1 (Adm RAB)","-","-", new Organisasi(11L), new Jabatan(16L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(65L, "Staf Sub Bag. Teknik Cab. Pwkt 1 (Adm Kegiatan Teknik)","-","-", new Organisasi(11L), new Jabatan(16L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(66L, "Staf Sub Bag. Adm & Keu Cab. Pwkt 2","-","-", new Organisasi(13L), new Jabatan(19L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(67L, "Staf Sub Bag. Pelayanan Cab. Pwkt 2","-","-", new Organisasi(14L), new Jabatan(21L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(68L, "Staf Sub Bag. Teknik Cab. Pwkt 2 (PTM)","-","-", new Organisasi(15L), new Jabatan(23L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(69L, "Staf Sub Bag. Teknik Cab. Pwkt 2 (PMS)","-","-", new Organisasi(15L), new Jabatan(23L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(70L, "Staf Sub Bag. Teknik Cab. Pwkt 2 (PJ)","-","-", new Organisasi(15L), new Jabatan(23L), new Level(6L), new Grade(4L)));
        list.add(new Profesi(71L, "Staf Sub Bag. Teknik Cab. Pwkt 2 (Adm RAB)","-","-", new Organisasi(15L), new Jabatan(23L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(72L, "Staf Sub Bag. Teknik Cab. Pwkt 2 (Adm Kegiatan Teknik)","-","-", new Organisasi(15L), new Jabatan(23L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(73L, "Staf Sub Bag. Adm & Keu Cab. Banyumas","-","-", new Organisasi(17L), new Jabatan(26L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(74L, "Staf Sub Bag. Pelayanan Cab. Banyumas","-","-", new Organisasi(18L), new Jabatan(28L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(75L, "Staf Sub Bag. Teknik Cab. Banyumas (PTM)","-","-", new Organisasi(19L), new Jabatan(30L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(76L, "Staf Sub Bag. Teknik Cab. Banyumas (PMS)","-","-", new Organisasi(19L), new Jabatan(30L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(77L, "Staf Sub Bag. Teknik Cab. Banyumas (PJ)","-","-", new Organisasi(19L), new Jabatan(30L), new Level(6L), new Grade(4L)));
        list.add(new Profesi(78L, "Staf Sub Bag. Teknik Cab. Banyumas (Adm RAB)","-","-", new Organisasi(19L), new Jabatan(30L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(79L, "Staf Sub Bag. Teknik Cab. Banyumas (Adm Kegiatan Teknik)","-","-", new Organisasi(19L), new Jabatan(30L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(80L, "Staf Sub Bag. Adm & Keu Cab. Wangon","-","-", new Organisasi(21L), new Jabatan(33L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(81L, "Staf Sub Bag. Pelayanan Cab. Wangon","-","-", new Organisasi(22L), new Jabatan(35L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(82L, "Staf Sub Bag. Teknik Cab. Wangon (PTM)","-","-", new Organisasi(23L), new Jabatan(37L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(83L, "Staf Sub Bag. Teknik Cab. Wangon (PMS)","-","-", new Organisasi(23L), new Jabatan(37L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(84L, "Staf Sub Bag. Teknik Cab. Wangon (PJ)","-","-", new Organisasi(23L), new Jabatan(37L), new Level(6L), new Grade(4L)));
        list.add(new Profesi(85L, "Staf Sub Bag. Teknik Cab. Wangon (Adm RAB)","-","-", new Organisasi(23L), new Jabatan(37L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(86L, "Staf Sub Bag. Teknik Cab. Wangon (Adm Kegiatan Teknik)","-","-", new Organisasi(23L), new Jabatan(37L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(87L, "Staf Sub Bag. Adm & Keu Cab. Ajibarang","-","-", new Organisasi(25L), new Jabatan(40L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(88L, "Staf Sub Bag. Pelayanan Cab. Ajibarang","-","-", new Organisasi(26L), new Jabatan(42L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(89L, "Staf Sub Bag. Teknik Cab. Ajibarang (PTM)","-","-", new Organisasi(27L), new Jabatan(44L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(90L, "Staf Sub Bag. Teknik Cab. Ajibarang (PMS)","-","-", new Organisasi(27L), new Jabatan(44L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(91L, "Staf Sub Bag. Teknik Cab. Ajibarang (PJ)","-","-", new Organisasi(27L), new Jabatan(44L), new Level(6L), new Grade(4L)));
        list.add(new Profesi(92L, "Staf Sub Bag. Teknik Cab. Ajibarang (Adm RAB)","-","-", new Organisasi(27L), new Jabatan(44L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(93L, "Staf Sub Bag. Teknik Cab. Ajibarang (Adm Kegiatan Teknik)","-","-", new Organisasi(27L), new Jabatan(44L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(94L, "Staf Sub Bag. AMDK (Admin)","-","-", new Organisasi(30L), new Jabatan(47L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(95L, "Staf Sub Bag. AMDK","-","-", new Organisasi(30L), new Jabatan(47L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(96L, "Staf Sub Bag. AMDK (Admin)","-","-", new Organisasi(29L), new Jabatan(49L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(97L, "Staf Sub Bag. AMDK","-","-", new Organisasi(29L), new Jabatan(49L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(98L, "Staf Sub Bag. Hukum & Perizinan","-","-", new Organisasi(46L), new Jabatan(52L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(99L, "Staf Sub Bag. Humas & Protokol","-","-", new Organisasi(47L), new Jabatan(54L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(100L, "Staf Sub Bag. Tata Usaha & Rumah Tangga","-","-", new Organisasi(48L), new Jabatan(56L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(101L, "Kepala Satpam","-","-", new Organisasi(48L), new Jabatan(57L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(102L, "Staf Sub Bag. Akuntansi","-","-", new Organisasi(50L), new Jabatan(60L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(103L, "Staf Sub Bag. Anggaran & Pelaporan","-","-", new Organisasi(51L), new Jabatan(62L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(104L, "Staf Sub Bag. Perbendaharaan","-","-", new Organisasi(52L), new Jabatan(64L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(105L, "Staf Sub Bag. Adm. & Pengembangan SDM","-","-", new Organisasi(54L), new Jabatan(67L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(106L, "Staf Sub Bag. Remunerasi & K3","-","-", new Organisasi(55L), new Jabatan(69L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(107L, "Staf Sub Bag. Teknologi Informasi (Administrasi)","-","-", new Organisasi(56L), new Jabatan(71L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(108L, "Staf Sub Bag. Teknologi Informasi (Programmer)","-","-", new Organisasi(56L), new Jabatan(71L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(109L, "Staf Sub Bag. Teknologi Informasi (Performa Server, Hardware, jaringan & Mikrotik","-","-", new Organisasi(56L), new Jabatan(71L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(110L, "Staf Sub Bag. Aset","-","-", new Organisasi(58L), new Jabatan(74L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(111L, "Staf Sub Bag. Pengadaan","-","-", new Organisasi(59L), new Jabatan(76L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(112L, "Staf Sub Bag. Persediaan","-","-", new Organisasi(60L), new Jabatan(78L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(113L, "Staf Sub Bag. Perencanaan","-","-", new Organisasi(32L), new Jabatan(81L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(114L, "Staf Sub Bag. Pengembangan","-","-", new Organisasi(33L), new Jabatan(83L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(115L, "Staf Sub Bag. Pengawasan Pekerjaan","-","-", new Organisasi(34L), new Jabatan(85L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(116L, "Staf. Sub Bag. Pengendalian Produksi 1 (Administrasi)","-","-", new Organisasi(36L), new Jabatan(88L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(117L, "Staf. Sub Bag. Pengendalian Distribusi 1 (Administrasi)","-","-", new Organisasi(37L), new Jabatan(90L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(118L, "Staf. Sub Bag. Pengendalian Produksi 1 (Teknik)","-","-", new Organisasi(36L), new Jabatan(88L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(119L, "Staf. Sub Bag. Pengendalian Distribusi 1 (Teknik)","-","-", new Organisasi(37L), new Jabatan(90L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(120L, "Staf Sub Bag. Pengendalian Produksi 2 (Administrasi)","-","-", new Organisasi(39L), new Jabatan(93L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(121L, "Staf Sub Bag. Pengendalian Distribusi 2 (Adminsitrasi)","-","-", new Organisasi(40L), new Jabatan(95L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(122L, "Staf Sub Bag. Pengendalian Produksi 2 (Teknik)","-","-", new Organisasi(39L), new Jabatan(93L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(123L, "Staf Sub Bag. Pengendalian Distribusi 2 (Teknik)","-","-", new Organisasi(40L), new Jabatan(95L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(124L, "Staf Sub Bag. Mekanikal & Elektrikal","-","-", new Organisasi(42L), new Jabatan(98L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(125L, "Staf Sub Bag. Mekanikal & Elektrikal (Administrasi)","-","-", new Organisasi(42L), new Jabatan(98L), new Level(6L), new Grade(3L)));
        list.add(new Profesi(126L, "Mandor","-","-", new Organisasi(42L), new Jabatan(99L), new Level(6L), new Grade(1L)));
        list.add(new Profesi(127L, "Staf Sub Bag. Pengendalian Kehilangan Air","-","-", new Organisasi(43L), new Jabatan(101L), new Level(6L), new Grade(2L)));
        list.add(new Profesi(128L, "Staf Sub Bag. Penjaminan Mutu Air","-","-", new Organisasi(44L), new Jabatan(103L), new Level(6L), new Grade(2L)));

        profesiRepository.saveAll(list);
    }
}
