package id.perumdamts.kepegawaian.services.setupMaster;

import id.perumdamts.kepegawaian.entities.master.*;
import id.perumdamts.kepegawaian.repositories.master.jpa.ProfesiRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
public class SetupProfesi implements SetupMaster {
    private final ProfesiRepository profesiRepository;

    @Override
    public void insertBatch() {
        List<Profesi> list = new ArrayList<>();
        list.add(new Profesi("Manajer Satuan Pengawas Intern", "-", "-", new Organisasi(5L), new Jabatan(53L), new Level(5L), new Grade(1L)));
        list.add(new Profesi("Manajer Cabang Purwokerto 1", "-", "-", new Organisasi(8L), new Jabatan(70L), new Level(5L), new Grade(3L)));
        list.add(new Profesi("Manajer Cabang Purwokerto 2", "-", "-", new Organisasi(9L), new Jabatan(79L), new Level(5L), new Grade(2L)));
        list.add(new Profesi("Manajer Cabang Banyumas", "-", "-", new Organisasi(12L), new Jabatan(106L), new Level(5L), new Grade(2L)));
        list.add(new Profesi("Manajer Cabang Wangon", "-", "-", new Organisasi(11L), new Jabatan(97L), new Level(5L), new Grade(1L)));
        list.add(new Profesi("Manajer Cabang Ajibarang", "-", "-", new Organisasi(10L), new Jabatan(88L), new Level(5L), new Grade(1L)));
        list.add(new Profesi("Manajer Unit Bisnis AMDK", "-", "-", new Organisasi(68L), new Jabatan(119L), new Level(5L), new Grade(1L)));
        list.add(new Profesi("Manajer Kesekretariatan", "-", "-", new Organisasi(15L), new Jabatan(40L), new Level(5L), new Grade(1L)));
        list.add(new Profesi("Manajer Keuangan", "-", "-", new Organisasi(13L), new Jabatan(26L), new Level(5L), new Grade(1L)));
        list.add(new Profesi("Manajer Sumber Daya Manusia & TI", "-", "-", new Organisasi(16L), new Jabatan(48L), new Level(5L), new Grade(1L)));
        list.add(new Profesi("Manajer Perlengkapan", "-", "-", new Organisasi(69L), new Jabatan(118L), new Level(5L), new Grade(2L)));
        list.add(new Profesi("Manajer Perencanaan & Pengembangan", "-", "-", new Organisasi(17L), new Jabatan(4L), new Level(5L), new Grade(2L)));
        list.add(new Profesi("Manajer Produksi & Distribusi 1", "-", "-", new Organisasi(18L), new Jabatan(9L), new Level(5L), new Grade(2L)));
        list.add(new Profesi("Manajer Produksi & Distribusi 2", "-", "-", new Organisasi(19L), new Jabatan(14L), new Level(5L), new Grade(2L)));
        list.add(new Profesi("Manajer Pengendalian Teknik", "-", "-", new Organisasi(20L), new Jabatan(19L), new Level(5L), new Grade(2L)));
        list.add(new Profesi("Supervisor Audit Intern", "-", "-", new Organisasi(61L), new Jabatan(56L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Standardisasi", "-", "-", new Organisasi(60L), new Jabatan(54L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Adm & Keu Cab. Pwkt 1", "-", "-", new Organisasi(21L), new Jabatan(71L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Pelayanan Cab. Pwkt 1", "-", "-", new Organisasi(23L), new Jabatan(75L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Teknik Cab. Pwkt 1", "-", "-", new Organisasi(24L), new Jabatan(77L), new Level(6L), new Grade(6L)));
        list.add(new Profesi("Supervisor Adm & Keu Cab. Pwkt 2", "-", "-", new Organisasi(25L), new Jabatan(80L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Pelayanan Cab. Pwkt 2", "-", "-", new Organisasi(27L), new Jabatan(84L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Teknik Cab. Pwkt 2", "-", "-", new Organisasi(28L), new Jabatan(86L), new Level(6L), new Grade(6L)));
        list.add(new Profesi("Supervisor Adm & Keu Cab. Banyumas", "-", "-", new Organisasi(37L), new Jabatan(107L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Pelayanan Cab. Banyumas", "-", "-", new Organisasi(39L), new Jabatan(111L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Teknik Cab. Banyumas", "-", "-", new Organisasi(40L), new Jabatan(113L), new Level(6L), new Grade(6L)));
        list.add(new Profesi("Supervisor Adm & Keu Cab. Wangon", "-", "-", new Organisasi(33L), new Jabatan(98L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Pelayanan Cab. Wangon", "-", "-", new Organisasi(35L), new Jabatan(102L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Teknik Cab. Wangon", "-", "-", new Organisasi(36L), new Jabatan(104L), new Level(6L), new Grade(6L)));
        list.add(new Profesi("Supervisor Adm & Keu Cab. Ajibarang", "-", "-", new Organisasi(29L), new Jabatan(89L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Pelayanan Cab. Ajibarang", "-", "-", new Organisasi(31L), new Jabatan(93L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Teknik Cab. Ajibarang", "-", "-", new Organisasi(32L), new Jabatan(95L), new Level(6L), new Grade(6L)));
        list.add(new Profesi("Supervisor Pemasaran", "-", "-", new Organisasi(45L), new Jabatan(125L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Produksi", "-", "-", new Organisasi(75L), new Jabatan(124L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Hukum & Perizinan", "-", "-", new Organisasi(46L), new Jabatan(38L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Humas & Protokol", "-", "-", new Organisasi(44L), new Jabatan(34L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Tata Usaha & Rumah Tangga", "-", "-", new Organisasi(47L), new Jabatan(41L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Akuntansi", "-", "-", new Organisasi(42L), new Jabatan(29L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Anggaran & Pelaporan", "-", "-", new Organisasi(41L), new Jabatan(27L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Perbendaharaan", "-", "-", new Organisasi(43L), new Jabatan(31L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Adm. & Pengembangan SDM", "-", "-", new Organisasi(50L), new Jabatan(49L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Remunerasi & K3", "-", "-", new Organisasi(51L), new Jabatan(51L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Teknologi Informasi", "-", "-", new Organisasi(65L), new Jabatan(66L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Aset", "-", "-", new Organisasi(48L), new Jabatan(44L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Pengadaan", "-", "-", new Organisasi(49L), new Jabatan(46L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Persediaan", "-", "-", new Organisasi(74L), new Jabatan(123L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Perencanaan", "-", "-", new Organisasi(52L), new Jabatan(5L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Pengembangan", "-", "-", new Organisasi(63L), new Jabatan(61L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Pengawasan Pekerjaan", "-", "-", new Organisasi(53L), new Jabatan(7L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Pengendalian Produksi 1", "-", "-", new Organisasi(54L), new Jabatan(10L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Pengendalian Distribusi 1", "-", "-", new Organisasi(56L), new Jabatan(15L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Pengendalian Produksi 2", "-", "-", new Organisasi(72L), new Jabatan(121L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Pengendalian Distribusi 2", "-", "-", new Organisasi(57L), new Jabatan(17L), new Level(6L), new Grade(5L)));
        list.add(new Profesi("Supervisor Mekanikal & Elektrikal", "-", "-", new Organisasi(58L), new Jabatan(20L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Pengendalian Kehilangan Air", "-", "-", new Organisasi(64L), new Jabatan(63L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Supervisor Penjaminan Mutu Air", "-", "-", new Organisasi(55L), new Jabatan(12L), new Level(6L), new Grade(4L)));
        list.add(new Profesi("Staf Sub Bag. Audit Intern", "-", "-", new Organisasi(61L), new Jabatan(57L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Standardisasi", "-", "-", new Organisasi(60L), new Jabatan(55L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Adm & Keu Cab. Pwkt 1", "-", "-", new Organisasi(21L), new Jabatan(72L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pelayanan Cab. Pwkt 1", "-", "-", new Organisasi(23L), new Jabatan(76L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 1 (PTM)", "-", "-", new Organisasi(24L), new Jabatan(78L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 1 (PMS)", "-", "-", new Organisasi(24L), new Jabatan(78L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 1 (PJ)", "-", "-", new Organisasi(24L), new Jabatan(78L), new Level(7L), new Grade(11L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 1 (Adm RAB)", "-", "-", new Organisasi(24L), new Jabatan(78L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 1 (Adm Kegiatan Teknik)", "-", "-", new Organisasi(24L), new Jabatan(78L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Adm & Keu Cab. Pwkt 2", "-", "-", new Organisasi(25L), new Jabatan(81L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pelayanan Cab. Pwkt 2", "-", "-", new Organisasi(27L), new Jabatan(85L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 2 (PTM)", "-", "-", new Organisasi(28L), new Jabatan(87L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 2 (PMS)", "-", "-", new Organisasi(28L), new Jabatan(87L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 2 (PJ)", "-", "-", new Organisasi(28L), new Jabatan(87L), new Level(7L), new Grade(11L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 2 (Adm RAB)", "-", "-", new Organisasi(28L), new Jabatan(87L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Pwkt 2 (Adm Kegiatan Teknik)", "-", "-", new Organisasi(28L), new Jabatan(87L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Adm & Keu Cab. Banyumas", "-", "-", new Organisasi(37L), new Jabatan(108L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pelayanan Cab. Banyumas", "-", "-", new Organisasi(39L), new Jabatan(112L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Banyumas (PTM)", "-", "-", new Organisasi(40L), new Jabatan(114L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Banyumas (PMS)", "-", "-", new Organisasi(40L), new Jabatan(114L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Banyumas (PJ)", "-", "-", new Organisasi(40L), new Jabatan(114L), new Level(7L), new Grade(11L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Banyumas (Adm RAB)", "-", "-", new Organisasi(40L), new Jabatan(114L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Banyumas (Adm Kegiatan Teknik)", "-", "-", new Organisasi(40L), new Jabatan(114L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Adm & Keu Cab. Wangon", "-", "-", new Organisasi(33L), new Jabatan(99L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pelayanan Cab. Wangon", "-", "-", new Organisasi(35L), new Jabatan(103L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Wangon (PTM)", "-", "-", new Organisasi(36L), new Jabatan(105L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Wangon (PMS)", "-", "-", new Organisasi(36L), new Jabatan(105L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Wangon (PJ)", "-", "-", new Organisasi(36L), new Jabatan(105L), new Level(7L), new Grade(11L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Wangon (Adm RAB)", "-", "-", new Organisasi(36L), new Jabatan(105L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Wangon (Adm Kegiatan Teknik)", "-", "-", new Organisasi(36L), new Jabatan(105L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Adm & Keu Cab. Ajibarang", "-", "-", new Organisasi(29L), new Jabatan(90L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pelayanan Cab. Ajibarang", "-", "-", new Organisasi(31L), new Jabatan(94L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Ajibarang (PTM)", "-", "-", new Organisasi(32L), new Jabatan(96L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Ajibarang (PMS)", "-", "-", new Organisasi(32L), new Jabatan(96L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Ajibarang (PJ)", "-", "-", new Organisasi(32L), new Jabatan(96L), new Level(7L), new Grade(11L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Ajibarang (Adm RAB)", "-", "-", new Organisasi(32L), new Jabatan(96L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Teknik Cab. Ajibarang (Adm Kegiatan Teknik)", "-", "-", new Organisasi(32L), new Jabatan(96L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. AMDK (Admin)", "-", "-", new Organisasi(75L), new Jabatan(126L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. AMDK", "-", "-", new Organisasi(75L), new Jabatan(126L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. AMDK (Admin)", "-", "-", new Organisasi(45L), new Jabatan(37L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. AMDK", "-", "-", new Organisasi(45L), new Jabatan(37L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Hukum & Perizinan", "-", "-", new Organisasi(46L), new Jabatan(39L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Humas & Protokol", "-", "-", new Organisasi(44L), new Jabatan(35L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Tata Usaha & Rumah Tangga", "-", "-", new Organisasi(47L), new Jabatan(42L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Kepala Satpam", "-", "-", new Organisasi(47L), new Jabatan(43L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Akuntansi", "-", "-", new Organisasi(42L), new Jabatan(30L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Anggaran & Pelaporan", "-", "-", new Organisasi(41L), new Jabatan(28L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Perbendaharaan", "-", "-", new Organisasi(43L), new Jabatan(32L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Adm. & Pengembangan SDM", "-", "-", new Organisasi(50L), new Jabatan(50L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Remunerasi & K3", "-", "-", new Organisasi(51L), new Jabatan(52L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Teknologi Informasi (Administrasi)", "-", "-", new Organisasi(65L), new Jabatan(67L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Teknologi Informasi (Programmer)", "-", "-", new Organisasi(65L), new Jabatan(67L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Staf Sub Bag. Teknologi Informasi (Performa Server, Hardware, jaringan & Mikrotik", "-", "-", new Organisasi(65L), new Jabatan(67L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Aset", "-", "-", new Organisasi(48L), new Jabatan(45L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pengadaan", "-", "-", new Organisasi(49L), new Jabatan(47L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Persediaan", "-", "-", new Organisasi(74L), new Jabatan(130L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Perencanaan", "-", "-", new Organisasi(52L), new Jabatan(6L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Pengembangan", "-", "-", new Organisasi(63L), new Jabatan(62L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Pengawasan Pekerjaan", "-", "-", new Organisasi(53L), new Jabatan(8L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf. Sub Bag. Pengendalian Produksi 1 (Administrasi)", "-", "-", new Organisasi(54L), new Jabatan(11L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf. Sub Bag. Pengendalian Distribusi 1 (Administrasi)", "-", "-", new Organisasi(56L), new Jabatan(16L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf. Sub Bag. Pengendalian Produksi 1 (Teknik)", "-", "-", new Organisasi(54L), new Jabatan(11L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf. Sub Bag. Pengendalian Distribusi 1 (Teknik)", "-", "-", new Organisasi(56L), new Jabatan(16L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Pengendalian Produksi 2 (Administrasi)", "-", "-", new Organisasi(72L), new Jabatan(128L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pengendalian Distribusi 2 (Adminsitrasi)", "-", "-", new Organisasi(57L), new Jabatan(18L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pengendalian Produksi 2 (Teknik)", "-", "-", new Organisasi(72L), new Jabatan(128L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Pengendalian Distribusi 2 (Teknik)", "-", "-", new Organisasi(57L), new Jabatan(18L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Mekanikal & Elektrikal", "-", "-", new Organisasi(58L), new Jabatan(21L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Mekanikal & Elektrikal (Administrasi)", "-", "-", new Organisasi(58L), new Jabatan(21L), new Level(7L), new Grade(10L)));
        list.add(new Profesi("Mandor", "-", "-", new Organisasi(58L), new Jabatan(22L), new Level(7L), new Grade(8L)));
        list.add(new Profesi("Staf Sub Bag. Pengendalian Kehilangan Air", "-", "-", new Organisasi(64L), new Jabatan(64L), new Level(7L), new Grade(9L)));
        list.add(new Profesi("Staf Sub Bag. Penjaminan Mutu Air", "-", "-", new Organisasi(55L), new Jabatan(13L), new Level(7L), new Grade(9L)));

        profesiRepository.saveAll(list);
    }
}
