package id.perumdamts.kepegawaian.services.setupMaster;

import com.fasterxml.jackson.core.JsonProcessingException;
import id.perumdamts.kepegawaian.entities.commons.EJenisGaji;
import id.perumdamts.kepegawaian.entities.penggajian.GajiKomponen;
import id.perumdamts.kepegawaian.entities.penggajian.GajiProfil;
import id.perumdamts.kepegawaian.repositories.penggajian.GajiKomponenRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class SetupGajiKomponen implements SetupMaster {
    @Autowired
    private GajiKomponenRepository repository;

    @Override
    public void insertBatch() throws JsonProcessingException {
        List<GajiKomponen> list = new ArrayList<>();
        list.add(new GajiKomponen(1L,1, new GajiProfil(1L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2L,2, new GajiProfil(1L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3L,3, new GajiProfil(1L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4L,4, new GajiProfil(1L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5L,5, new GajiProfil(1L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6L,6, new GajiProfil(1L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7L,7, new GajiProfil(1L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(8L,8, new GajiProfil(1L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(9L,9, new GajiProfil(1L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(10L,10, new GajiProfil(1L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(11L,11, new GajiProfil(1L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(12L,12, new GajiProfil(1L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(13L,13, new GajiProfil(1L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(14L,14, new GajiProfil(1L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(15L,15, new GajiProfil(1L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(16L,16, new GajiProfil(1L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(17L,17, new GajiProfil(1L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(18L,18, new GajiProfil(1L), "PHDP", "PhDP", EJenisGaji.NONE,21362814,false,""));
        list.add(new GajiKomponen(19L,19, new GajiProfil(1L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,"PHDP * 0.05"));
        list.add(new GajiKomponen(20L,20, new GajiProfil(1L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(21L,21, new GajiProfil(1L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(22L,22, new GajiProfil(1L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(23L,23, new GajiProfil(1L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(24L,24, new GajiProfil(1L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(25L,25, new GajiProfil(1L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) * 0.1"));
        list.add(new GajiKomponen(26L,26, new GajiProfil(1L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(27L,27, new GajiProfil(1L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(28L,28, new GajiProfil(1L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(29L,29, new GajiProfil(1L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(30L,1, new GajiProfil(2L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(31L,2, new GajiProfil(2L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(32L,3, new GajiProfil(2L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(33L,4, new GajiProfil(2L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(34L,5, new GajiProfil(2L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(35L,6, new GajiProfil(2L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(36L,7, new GajiProfil(2L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(37L,8, new GajiProfil(2L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(38L,9, new GajiProfil(2L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(39L,10, new GajiProfil(2L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(40L,11, new GajiProfil(2L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(41L,12, new GajiProfil(2L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(42L,13, new GajiProfil(2L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(43L,14, new GajiProfil(2L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(44L,15, new GajiProfil(2L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(45L,16, new GajiProfil(2L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_KK "));
        list.add(new GajiKomponen(46L,17, new GajiProfil(2L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_AIR "));
        list.add(new GajiKomponen(47L,18, new GajiProfil(2L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(48L,19, new GajiProfil(2L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(49L,20, new GajiProfil(2L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(50L,21, new GajiProfil(2L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(51L,22, new GajiProfil(2L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(52L,23, new GajiProfil(2L), "PHDP", "PhDP", EJenisGaji.NONE,0,false,"REF_PHDP "));
        list.add(new GajiKomponen(53L,24, new GajiProfil(2L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,"PHDP * 0.05"));
        list.add(new GajiKomponen(54L,25, new GajiProfil(2L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(55L,26, new GajiProfil(2L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(56L,27, new GajiProfil(2L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(57L,28, new GajiProfil(2L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(58L,29, new GajiProfil(2L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(59L,30, new GajiProfil(2L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(60L,31, new GajiProfil(2L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(61L,32, new GajiProfil(2L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(62L,33, new GajiProfil(2L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(63L,34, new GajiProfil(2L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(64L,1, new GajiProfil(3L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(65L,2, new GajiProfil(3L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(66L,3, new GajiProfil(3L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(67L,4, new GajiProfil(3L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(68L,5, new GajiProfil(3L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(69L,6, new GajiProfil(3L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(70L,7, new GajiProfil(3L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(71L,8, new GajiProfil(3L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(72L,9, new GajiProfil(3L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(73L,10, new GajiProfil(3L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(74L,11, new GajiProfil(3L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(75L,12, new GajiProfil(3L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(76L,13, new GajiProfil(3L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(77L,14, new GajiProfil(3L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(78L,15, new GajiProfil(3L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(79L,16, new GajiProfil(3L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(80L,17, new GajiProfil(3L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(81L,18, new GajiProfil(3L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(82L,19, new GajiProfil(3L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(83L,20, new GajiProfil(3L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(84L,21, new GajiProfil(3L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(85L,22, new GajiProfil(3L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(86L,23, new GajiProfil(3L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(87L,24, new GajiProfil(3L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(88L,25, new GajiProfil(3L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(89L,26, new GajiProfil(3L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(90L,27, new GajiProfil(3L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(91L,28, new GajiProfil(3L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(92L,29, new GajiProfil(3L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(93L,30, new GajiProfil(3L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(94L,31, new GajiProfil(3L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(95L,32, new GajiProfil(3L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(96L,1, new GajiProfil(4L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(97L,2, new GajiProfil(4L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(98L,3, new GajiProfil(4L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(99L,4, new GajiProfil(4L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(100L,5, new GajiProfil(4L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(101L,6, new GajiProfil(4L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(102L,7, new GajiProfil(4L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(103L,8, new GajiProfil(4L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(104L,9, new GajiProfil(4L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(105L,10, new GajiProfil(4L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(106L,11, new GajiProfil(4L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(107L,12, new GajiProfil(4L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(108L,13, new GajiProfil(4L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(109L,14, new GajiProfil(4L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(110L,15, new GajiProfil(4L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(111L,16, new GajiProfil(4L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(112L,17, new GajiProfil(4L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(113L,18, new GajiProfil(4L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(114L,19, new GajiProfil(4L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(115L,20, new GajiProfil(4L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(116L,21, new GajiProfil(4L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(117L,22, new GajiProfil(4L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(118L,23, new GajiProfil(4L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(119L,24, new GajiProfil(4L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(120L,25, new GajiProfil(4L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(121L,26, new GajiProfil(4L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(122L,27, new GajiProfil(4L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(123L,28, new GajiProfil(4L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(124L,29, new GajiProfil(4L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(125L,30, new GajiProfil(4L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(126L,31, new GajiProfil(4L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(127L,32, new GajiProfil(4L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(128L,1, new GajiProfil(5L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(129L,2, new GajiProfil(5L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(130L,3, new GajiProfil(5L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(131L,4, new GajiProfil(5L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(132L,5, new GajiProfil(5L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(133L,6, new GajiProfil(5L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(134L,7, new GajiProfil(5L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(135L,8, new GajiProfil(5L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(136L,9, new GajiProfil(5L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(137L,10, new GajiProfil(5L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(138L,11, new GajiProfil(5L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(139L,12, new GajiProfil(5L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(140L,13, new GajiProfil(5L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(141L,14, new GajiProfil(5L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(142L,15, new GajiProfil(5L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_KK "));
        list.add(new GajiKomponen(143L,16, new GajiProfil(5L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_AIR "));
        list.add(new GajiKomponen(144L,17, new GajiProfil(5L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(145L,18, new GajiProfil(5L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(146L,19, new GajiProfil(5L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(147L,20, new GajiProfil(5L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(148L,21, new GajiProfil(5L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(149L,22, new GajiProfil(5L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(150L,23, new GajiProfil(5L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(151L,24, new GajiProfil(5L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(152L,25, new GajiProfil(5L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(153L,26, new GajiProfil(5L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(154L,27, new GajiProfil(5L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(155L,28, new GajiProfil(5L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(156L,29, new GajiProfil(5L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(157L,30, new GajiProfil(5L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(158L,31, new GajiProfil(5L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(159L,32, new GajiProfil(5L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(160L,1, new GajiProfil(6L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(161L,2, new GajiProfil(6L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(162L,3, new GajiProfil(6L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(163L,4, new GajiProfil(6L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(164L,5, new GajiProfil(6L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(165L,6, new GajiProfil(6L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(166L,7, new GajiProfil(6L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(167L,8, new GajiProfil(6L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(168L,9, new GajiProfil(6L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(169L,10, new GajiProfil(6L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(170L,11, new GajiProfil(6L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(171L,12, new GajiProfil(6L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,""));
        list.add(new GajiKomponen(172L,13, new GajiProfil(6L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,""));
        list.add(new GajiKomponen(173L,14, new GajiProfil(6L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(174L,15, new GajiProfil(6L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP"));
        list.add(new GajiKomponen(175L,16, new GajiProfil(6L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(176L,17, new GajiProfil(6L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"GP * 0.02"));
        list.add(new GajiKomponen(177L,18, new GajiProfil(6L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(178L,19, new GajiProfil(6L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"GP * 0.01"));
        list.add(new GajiKomponen(179L,20, new GajiProfil(6L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"GP * 0.01 * REF_ASKES"));
        list.add(new GajiKomponen(180L,21, new GajiProfil(6L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(181L,22, new GajiProfil(6L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(182L,23, new GajiProfil(6L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(183L,24, new GajiProfil(6L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(184L,25, new GajiProfil(6L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(185L,26, new GajiProfil(6L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(186L,1, new GajiProfil(7L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(187L,2, new GajiProfil(7L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(188L,3, new GajiProfil(7L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(189L,4, new GajiProfil(7L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(190L,5, new GajiProfil(7L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(191L,6, new GajiProfil(7L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(192L,7, new GajiProfil(7L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(193L,8, new GajiProfil(7L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(194L,9, new GajiProfil(7L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(195L,10, new GajiProfil(7L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(196L,11, new GajiProfil(7L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(197L,12, new GajiProfil(7L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(198L,13, new GajiProfil(7L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(199L,14, new GajiProfil(7L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(200L,15, new GajiProfil(7L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(201L,16, new GajiProfil(7L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_KK "));
        list.add(new GajiKomponen(202L,17, new GajiProfil(7L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_AIR "));
        list.add(new GajiKomponen(203L,18, new GajiProfil(7L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(204L,19, new GajiProfil(7L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(205L,20, new GajiProfil(7L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(206L,21, new GajiProfil(7L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(207L,22, new GajiProfil(7L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(208L,23, new GajiProfil(7L), "PHDP", "PhDP", EJenisGaji.NONE,0,false,"REF_PHDP "));
        list.add(new GajiKomponen(209L,24, new GajiProfil(7L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,"PHDP * 0.05"));
        list.add(new GajiKomponen(210L,25, new GajiProfil(7L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(211L,26, new GajiProfil(7L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(212L,27, new GajiProfil(7L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(213L,28, new GajiProfil(7L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(214L,29, new GajiProfil(7L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(215L,30, new GajiProfil(7L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(216L,31, new GajiProfil(7L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(217L,32, new GajiProfil(7L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(218L,33, new GajiProfil(7L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(219L,34, new GajiProfil(7L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(220L,1, new GajiProfil(8L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(221L,2, new GajiProfil(8L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(222L,3, new GajiProfil(8L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(223L,4, new GajiProfil(8L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(224L,5, new GajiProfil(8L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(225L,6, new GajiProfil(8L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(226L,7, new GajiProfil(8L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(227L,8, new GajiProfil(8L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(228L,9, new GajiProfil(8L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(229L,10, new GajiProfil(8L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(230L,11, new GajiProfil(8L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(231L,12, new GajiProfil(8L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(232L,13, new GajiProfil(8L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(233L,14, new GajiProfil(8L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(234L,15, new GajiProfil(8L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(235L,16, new GajiProfil(8L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(236L,17, new GajiProfil(8L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(237L,18, new GajiProfil(8L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(238L,19, new GajiProfil(8L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(239L,20, new GajiProfil(8L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(240L,21, new GajiProfil(8L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(241L,22, new GajiProfil(8L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(242L,23, new GajiProfil(8L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(243L,24, new GajiProfil(8L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(244L,25, new GajiProfil(8L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(245L,26, new GajiProfil(8L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"1750000 * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(246L,27, new GajiProfil(8L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(247L,28, new GajiProfil(8L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(248L,29, new GajiProfil(8L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(249L,30, new GajiProfil(8L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(250L,31, new GajiProfil(8L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(251L,32, new GajiProfil(8L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(252L,1, new GajiProfil(9L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(253L,2, new GajiProfil(9L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(254L,3, new GajiProfil(9L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(255L,4, new GajiProfil(9L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(256L,5, new GajiProfil(9L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(257L,6, new GajiProfil(9L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(258L,7, new GajiProfil(9L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(259L,8, new GajiProfil(9L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(260L,9, new GajiProfil(9L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(261L,10, new GajiProfil(9L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(262L,11, new GajiProfil(9L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(263L,12, new GajiProfil(9L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(264L,13, new GajiProfil(9L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(265L,14, new GajiProfil(9L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(266L,15, new GajiProfil(9L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(267L,16, new GajiProfil(9L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(268L,17, new GajiProfil(9L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(269L,18, new GajiProfil(9L), "PHDP", "PhDP", EJenisGaji.NONE,23736460,false,""));
        list.add(new GajiKomponen(270L,19, new GajiProfil(9L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,"PHDP * 0.05"));
        list.add(new GajiKomponen(271L,20, new GajiProfil(9L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(272L,21, new GajiProfil(9L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(273L,22, new GajiProfil(9L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(274L,23, new GajiProfil(9L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(275L,24, new GajiProfil(9L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(276L,25, new GajiProfil(9L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) * 0.1"));
        list.add(new GajiKomponen(277L,26, new GajiProfil(9L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(278L,27, new GajiProfil(9L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(279L,28, new GajiProfil(9L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(280L,29, new GajiProfil(9L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));

        repository.saveAll(list);
    }
}
