package id.perumdamts.kepegawaian.services.setupMaster;

import com.fasterxml.jackson.core.JsonProcessingException;
import id.perumdamts.kepegawaian.entities.penggajian.GajiKomponen;
import id.perumdamts.kepegawaian.entities.penggajian.GajiProfil;
import id.perumdamts.kepegawaian.repositories.penggajian.GajiKomponenRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class SetupGajiKomponen implements SetupMaster {
    @Autowired
    private GajiKomponenRepository repository;

    @Override
    public void insertBatch() throws JsonProcessingException {
        List<GajiKomponen> list = new ArrayList<>();
        list.add(new GajiKomponen(1L, 1, new GajiProfil(1L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(2L, 2, new GajiProfil(1L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(3L, 3, new GajiProfil(1L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(4L, 4, new GajiProfil(1L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(5L, 5, new GajiProfil(1L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(6L, 6, new GajiProfil(1L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(7L, 7, new GajiProfil(1L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(8L, 8, new GajiProfil(1L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(9L, 9, new GajiProfil(1L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(10L, 10, new GajiProfil(1L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(11L, 11, new GajiProfil(1L), "ASTEK", "Astek", "NONE", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(12L, 12, new GajiProfil(1L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(13L, 13, new GajiProfil(1L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(14L, 14, new GajiProfil(1L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(15L, 15, new GajiProfil(1L), "PHDP", "PhDP", "NONE", 21362814, false, ""));
        list.add(new GajiKomponen(16L, 16, new GajiProfil(1L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, "PHDP * 0.05"));
        list.add(new GajiKomponen(17L, 17, new GajiProfil(1L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(18L, 18, new GajiProfil(1L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(19L, 19, new GajiProfil(1L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(20L, 20, new GajiProfil(1L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(21L, 21, new GajiProfil(1L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(22L, 22, new GajiProfil(1L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "( PKP - ( 0,05 * PKP ) - REF_PTKP ) * 0.1"));
        list.add(new GajiKomponen(23L, 23, new GajiProfil(1L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(24L, 24, new GajiProfil(1L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(25L, 25, new GajiProfil(1L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(26L, 26, new GajiProfil(1L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(27L, 1, new GajiProfil(2L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(28L, 2, new GajiProfil(2L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(29L, 3, new GajiProfil(2L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(30L, 4, new GajiProfil(2L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(31L, 5, new GajiProfil(2L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(32L, 6, new GajiProfil(2L), "REF_PHDP", "Referensi PHDP", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(33L, 7, new GajiProfil(2L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(34L, 8, new GajiProfil(2L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(35L, 9, new GajiProfil(2L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(36L, 10, new GajiProfil(2L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(37L, 11, new GajiProfil(2L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(38L, 12, new GajiProfil(2L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, "0.1 * GP "));
        list.add(new GajiKomponen(39L, 13, new GajiProfil(2L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, "JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(40L, 14, new GajiProfil(2L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, "REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(41L, 15, new GajiProfil(2L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, "JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(42L, 16, new GajiProfil(2L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, "REF_TUNJ_KK "));
        list.add(new GajiKomponen(43L, 17, new GajiProfil(2L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, "REF_TUNJ_AIR "));
        list.add(new GajiKomponen(44L, 18, new GajiProfil(2L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(45L, 19, new GajiProfil(2L), "ASTEK", "Astek", "NONE", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(46L, 20, new GajiProfil(2L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(47L, 21, new GajiProfil(2L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, "( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(48L, 22, new GajiProfil(2L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(49L, 23, new GajiProfil(2L), "PHDP", "PhDP", "NONE", 0, false, "REF_PHDP "));
        list.add(new GajiKomponen(50L, 24, new GajiProfil(2L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, "PHDP * 0.05"));
        list.add(new GajiKomponen(51L, 25, new GajiProfil(2L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(52L, 26, new GajiProfil(2L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(53L, 27, new GajiProfil(2L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(54L, 28, new GajiProfil(2L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(55L, 29, new GajiProfil(2L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(56L, 30, new GajiProfil(2L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "TUNJ_PPH21 "));
        list.add(new GajiKomponen(57L, 31, new GajiProfil(2L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(58L, 32, new GajiProfil(2L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(59L, 33, new GajiProfil(2L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(60L, 34, new GajiProfil(2L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(61L, 1, new GajiProfil(3L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(62L, 2, new GajiProfil(3L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(63L, 3, new GajiProfil(3L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(64L, 4, new GajiProfil(3L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(65L, 5, new GajiProfil(3L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(66L, 6, new GajiProfil(3L), "REF_PHDP", "Referensi PHDP", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(67L, 7, new GajiProfil(3L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(68L, 8, new GajiProfil(3L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(69L, 9, new GajiProfil(3L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(70L, 10, new GajiProfil(3L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(71L, 11, new GajiProfil(3L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, "0.1 * GP "));
        list.add(new GajiKomponen(72L, 12, new GajiProfil(3L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, "JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(73L, 13, new GajiProfil(3L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, "REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(74L, 14, new GajiProfil(3L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, "JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(75L, 15, new GajiProfil(3L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(76L, 16, new GajiProfil(3L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(77L, 17, new GajiProfil(3L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(78L, 18, new GajiProfil(3L), "ASTEK", "Astek", "NONE", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(79L, 19, new GajiProfil(3L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(80L, 20, new GajiProfil(3L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, "( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(81L, 21, new GajiProfil(3L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(82L, 22, new GajiProfil(3L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, ""));
        list.add(new GajiKomponen(83L, 23, new GajiProfil(3L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(84L, 24, new GajiProfil(3L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(85L, 25, new GajiProfil(3L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(86L, 26, new GajiProfil(3L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(87L, 27, new GajiProfil(3L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(88L, 28, new GajiProfil(3L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "TUNJ_PPH21 "));
        list.add(new GajiKomponen(89L, 29, new GajiProfil(3L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(90L, 30, new GajiProfil(3L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(91L, 31, new GajiProfil(3L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(92L, 32, new GajiProfil(3L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(93L, 1, new GajiProfil(4L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(94L, 2, new GajiProfil(4L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(95L, 3, new GajiProfil(4L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(96L, 4, new GajiProfil(4L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(97L, 5, new GajiProfil(4L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(98L, 6, new GajiProfil(4L), "REF_PHDP", "Referensi PHDP", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(99L, 7, new GajiProfil(4L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(100L, 8, new GajiProfil(4L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(101L, 9, new GajiProfil(4L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(102L, 10, new GajiProfil(4L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(103L, 11, new GajiProfil(4L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, "0.1 * GP "));
        list.add(new GajiKomponen(104L, 12, new GajiProfil(4L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, "JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(105L, 13, new GajiProfil(4L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, "REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(106L, 14, new GajiProfil(4L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, "JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(107L, 15, new GajiProfil(4L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(108L, 16, new GajiProfil(4L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(109L, 17, new GajiProfil(4L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(110L, 18, new GajiProfil(4L), "ASTEK", "Astek", "NONE", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(111L, 19, new GajiProfil(4L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(112L, 20, new GajiProfil(4L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, "( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(113L, 21, new GajiProfil(4L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(114L, 22, new GajiProfil(4L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, ""));
        list.add(new GajiKomponen(115L, 23, new GajiProfil(4L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(116L, 24, new GajiProfil(4L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(117L, 25, new GajiProfil(4L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(118L, 26, new GajiProfil(4L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(119L, 27, new GajiProfil(4L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(120L, 28, new GajiProfil(4L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "TUNJ_PPH21 "));
        list.add(new GajiKomponen(121L, 29, new GajiProfil(4L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(122L, 30, new GajiProfil(4L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(123L, 31, new GajiProfil(4L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(124L, 32, new GajiProfil(4L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(125L, 1, new GajiProfil(5L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(126L, 2, new GajiProfil(5L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(127L, 3, new GajiProfil(5L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(128L, 4, new GajiProfil(5L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(129L, 5, new GajiProfil(5L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(130L, 6, new GajiProfil(5L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(131L, 7, new GajiProfil(5L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(132L, 8, new GajiProfil(5L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(133L, 9, new GajiProfil(5L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(134L, 10, new GajiProfil(5L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(135L, 11, new GajiProfil(5L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, "0.1 * GP "));
        list.add(new GajiKomponen(136L, 12, new GajiProfil(5L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, "JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(137L, 13, new GajiProfil(5L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, "REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(138L, 14, new GajiProfil(5L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, "JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(139L, 15, new GajiProfil(5L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, "REF_TUNJ_KK "));
        list.add(new GajiKomponen(140L, 16, new GajiProfil(5L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, "REF_TUNJ_AIR "));
        list.add(new GajiKomponen(141L, 17, new GajiProfil(5L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(142L, 18, new GajiProfil(5L), "ASTEK", "Astek", "NONE", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(143L, 19, new GajiProfil(5L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(144L, 20, new GajiProfil(5L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, "( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(145L, 21, new GajiProfil(5L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(146L, 22, new GajiProfil(5L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, ""));
        list.add(new GajiKomponen(147L, 23, new GajiProfil(5L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(148L, 24, new GajiProfil(5L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(149L, 25, new GajiProfil(5L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(150L, 26, new GajiProfil(5L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(151L, 27, new GajiProfil(5L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(152L, 28, new GajiProfil(5L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "TUNJ_PPH21 "));
        list.add(new GajiKomponen(153L, 29, new GajiProfil(5L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(154L, 30, new GajiProfil(5L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(155L, 31, new GajiProfil(5L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(156L, 32, new GajiProfil(5L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(157L, 1, new GajiProfil(6L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(158L, 2, new GajiProfil(6L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(159L, 3, new GajiProfil(6L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(160L, 4, new GajiProfil(6L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(161L, 5, new GajiProfil(6L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(162L, 6, new GajiProfil(6L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(163L, 7, new GajiProfil(6L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(164L, 8, new GajiProfil(6L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(165L, 9, new GajiProfil(6L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(166L, 10, new GajiProfil(6L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(167L, 11, new GajiProfil(6L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(168L, 12, new GajiProfil(6L), "ASTEK", "Astek", "NONE", 0, false, ""));
        list.add(new GajiKomponen(169L, 13, new GajiProfil(6L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, ""));
        list.add(new GajiKomponen(170L, 14, new GajiProfil(6L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(171L, 15, new GajiProfil(6L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP"));
        list.add(new GajiKomponen(172L, 16, new GajiProfil(6L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, ""));
        list.add(new GajiKomponen(173L, 17, new GajiProfil(6L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "GP * 0.02"));
        list.add(new GajiKomponen(174L, 18, new GajiProfil(6L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(175L, 19, new GajiProfil(6L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "GP * 0.01"));
        list.add(new GajiKomponen(176L, 20, new GajiProfil(6L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "GP * 0.01 * REF_ASKES"));
        list.add(new GajiKomponen(177L, 21, new GajiProfil(6L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(178L, 22, new GajiProfil(6L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "TUNJ_PPH21 "));
        list.add(new GajiKomponen(179L, 23, new GajiProfil(6L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(180L, 24, new GajiProfil(6L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(181L, 25, new GajiProfil(6L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(182L, 26, new GajiProfil(6L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(183L, 1, new GajiProfil(7L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(184L, 2, new GajiProfil(7L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(185L, 3, new GajiProfil(7L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(186L, 4, new GajiProfil(7L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(187L, 5, new GajiProfil(7L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(188L, 6, new GajiProfil(7L), "REF_PHDP", "Referensi PHDP", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(189L, 7, new GajiProfil(7L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(190L, 8, new GajiProfil(7L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(191L, 9, new GajiProfil(7L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(192L, 10, new GajiProfil(7L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(193L, 11, new GajiProfil(7L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(194L, 12, new GajiProfil(7L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(195L, 13, new GajiProfil(7L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, "JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(196L, 14, new GajiProfil(7L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, "REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(197L, 15, new GajiProfil(7L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, "JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(198L, 16, new GajiProfil(7L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, "REF_TUNJ_KK "));
        list.add(new GajiKomponen(199L, 17, new GajiProfil(7L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, "REF_TUNJ_AIR "));
        list.add(new GajiKomponen(200L, 18, new GajiProfil(7L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(201L, 19, new GajiProfil(7L), "ASTEK", "Astek", "NONE", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(202L, 20, new GajiProfil(7L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(203L, 21, new GajiProfil(7L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, "( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(204L, 22, new GajiProfil(7L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(205L, 23, new GajiProfil(7L), "PHDP", "PhDP", "NONE", 0, false, "REF_PHDP "));
        list.add(new GajiKomponen(206L, 24, new GajiProfil(7L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, "PHDP * 0.05"));
        list.add(new GajiKomponen(207L, 25, new GajiProfil(7L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(208L, 26, new GajiProfil(7L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(209L, 27, new GajiProfil(7L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(210L, 28, new GajiProfil(7L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(211L, 29, new GajiProfil(7L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(212L, 30, new GajiProfil(7L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "TUNJ_PPH21 "));
        list.add(new GajiKomponen(213L, 31, new GajiProfil(7L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(214L, 32, new GajiProfil(7L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(215L, 33, new GajiProfil(7L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(216L, 34, new GajiProfil(7L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(217L, 1, new GajiProfil(8L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(218L, 2, new GajiProfil(8L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(219L, 3, new GajiProfil(8L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(220L, 4, new GajiProfil(8L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(221L, 5, new GajiProfil(8L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(222L, 6, new GajiProfil(8L), "REF_PHDP", "Referensi PHDP", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(223L, 7, new GajiProfil(8L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(224L, 8, new GajiProfil(8L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(225L, 9, new GajiProfil(8L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(226L, 10, new GajiProfil(8L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(227L, 11, new GajiProfil(8L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, "0.1 * GP "));
        list.add(new GajiKomponen(228L, 12, new GajiProfil(8L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, "JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(229L, 13, new GajiProfil(8L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, "REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(230L, 14, new GajiProfil(8L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, "JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(231L, 15, new GajiProfil(8L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(232L, 16, new GajiProfil(8L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(233L, 17, new GajiProfil(8L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(234L, 18, new GajiProfil(8L), "ASTEK", "Astek", "NONE", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(235L, 19, new GajiProfil(8L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(236L, 20, new GajiProfil(8L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, "( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(237L, 21, new GajiProfil(8L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(238L, 22, new GajiProfil(8L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, ""));
        list.add(new GajiKomponen(239L, 23, new GajiProfil(8L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(240L, 24, new GajiProfil(8L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(241L, 25, new GajiProfil(8L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(242L, 26, new GajiProfil(8L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "1750000 * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(243L, 27, new GajiProfil(8L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(244L, 28, new GajiProfil(8L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "TUNJ_PPH21 "));
        list.add(new GajiKomponen(245L, 29, new GajiProfil(8L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(246L, 30, new GajiProfil(8L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(247L, 31, new GajiProfil(8L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(248L, 32, new GajiProfil(8L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(249L, 1, new GajiProfil(9L), "GP", "Gaji Pokok", "PEMASUKAN", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(250L, 2, new GajiProfil(9L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(251L, 3, new GajiProfil(9L), "REF_ASKES", "Referensi Kode ASKES", "NONE", 0, true, "#SYSTEM"));
        list.add(new GajiKomponen(252L, 4, new GajiProfil(9L), "TUNJ_SI", "Tunjangan Suami Istri", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(253L, 5, new GajiProfil(9L), "TUNJ_ANAK", "Tunjangan Anak", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(254L, 6, new GajiProfil(9L), "TUNJ_JABATAN", "Tunjangan Jabatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(255L, 7, new GajiProfil(9L), "TUNJ_BERAS", "Tunjangan Beras", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(256L, 8, new GajiProfil(9L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(257L, 9, new GajiProfil(9L), "TUNJ_AIR", "Tunjangan Air", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(258L, 10, new GajiProfil(9L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(259L, 11, new GajiProfil(9L), "ASTEK", "Astek", "NONE", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(260L, 12, new GajiProfil(9L), "PKP", "Pendapatan Kena Pajak", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(261L, 13, new GajiProfil(9L), "TUNJ_PPH21", "Tunjangan PPh 21", "PEMASUKAN", 0, false, ""));
        list.add(new GajiKomponen(262L, 14, new GajiProfil(9L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", "NONE", 0, false, "GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(263L, 15, new GajiProfil(9L), "PHDP", "PhDP", "NONE", 23736460, false, ""));
        list.add(new GajiKomponen(264L, 16, new GajiProfil(9L), "POT_PENSIUN", "Iuran Pensiun", "POTONGAN", 0, false, "PHDP * 0.05"));
        list.add(new GajiKomponen(265L, 17, new GajiProfil(9L), "POT_ASTEK", "Potongan Astek", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(266L, 18, new GajiProfil(9L), "POT_RUDIN", "Potongan Rumah Dinas", "POTONGAN", 0, false, "REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(267L, 19, new GajiProfil(9L), "POT_JP", "Potongan Jaminan Pensiun", "POTONGAN", 0, false, "( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(268L, 20, new GajiProfil(9L), "POT_ASKES", "Potongan BPJS Kesehatan", "POTONGAN", 0, false, "( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(269L, 21, new GajiProfil(9L), "POT_TKK", "Potongan TKK", "POTONGAN", 0, false, "REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(270L, 22, new GajiProfil(9L), "POT_PPH21", "Potongan PPh 21", "POTONGAN", 0, false, "( PKP - ( 0,05 * PKP ) - REF_PTKP ) * 0.1"));
        list.add(new GajiKomponen(271L, 23, new GajiProfil(9L), "POTONGAN", "Total Potongan", "NONE", 0, false, "POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(272L, 24, new GajiProfil(9L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", "NONE", 0, false, "PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(273L, 25, new GajiProfil(9L), "PEMBULATAN", "Pembulatan", "NONE", 0, false, "( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(274L, 26, new GajiProfil(9L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", "NONE", 0, false, "PENGHASILAN_BERSIH + PEMBULATAN "));

        repository.saveAll(list);
    }
}
