package id.perumdamts.kepegawaian.services.setupMaster;

import id.perumdamts.kepegawaian.entities.commons.EJenisGaji;
import id.perumdamts.kepegawaian.entities.penggajian.GajiKomponen;
import id.perumdamts.kepegawaian.entities.penggajian.GajiProfil;
import id.perumdamts.kepegawaian.repositories.penggajian.GajiKomponenRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
public class SetupGajiKomponen implements SetupMaster {
    private final GajiKomponenRepository repository;

    @Override
    public void insertBatch() {
        List<GajiKomponen> list = new ArrayList<>();
        list.add(new GajiKomponen(1, new GajiProfil(1L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(1L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(1L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(1L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(1L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6, new GajiProfil(1L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7, new GajiProfil(1L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(8, new GajiProfil(1L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(9, new GajiProfil(1L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(10, new GajiProfil(1L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(11, new GajiProfil(1L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(12, new GajiProfil(1L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(13, new GajiProfil(1L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(14, new GajiProfil(1L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(15, new GajiProfil(1L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(16, new GajiProfil(1L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(17, new GajiProfil(1L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(18, new GajiProfil(1L), "PHDP", "PhDP", EJenisGaji.NONE,21362814,false,""));
        list.add(new GajiKomponen(19, new GajiProfil(1L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,"PHDP * 0.05"));
        list.add(new GajiKomponen(20, new GajiProfil(1L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(21, new GajiProfil(1L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(22, new GajiProfil(1L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(23, new GajiProfil(1L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(24, new GajiProfil(1L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(25, new GajiProfil(1L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) * 0.1"));
        list.add(new GajiKomponen(26, new GajiProfil(1L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(27, new GajiProfil(1L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(28, new GajiProfil(1L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(29, new GajiProfil(1L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(1, new GajiProfil(2L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(2L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(2L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(2L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(2L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6, new GajiProfil(2L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7, new GajiProfil(2L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(8, new GajiProfil(2L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(9, new GajiProfil(2L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(10, new GajiProfil(2L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(11, new GajiProfil(2L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(12, new GajiProfil(2L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(13, new GajiProfil(2L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(14, new GajiProfil(2L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(15, new GajiProfil(2L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(16, new GajiProfil(2L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_KK "));
        list.add(new GajiKomponen(17, new GajiProfil(2L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_AIR "));
        list.add(new GajiKomponen(18, new GajiProfil(2L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(19, new GajiProfil(2L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(20, new GajiProfil(2L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(21, new GajiProfil(2L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(22, new GajiProfil(2L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(23, new GajiProfil(2L), "PHDP", "PhDP", EJenisGaji.NONE,0,false,"REF_PHDP "));
        list.add(new GajiKomponen(24, new GajiProfil(2L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,"PHDP * 0.05"));
        list.add(new GajiKomponen(25, new GajiProfil(2L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(26, new GajiProfil(2L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(27, new GajiProfil(2L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(28, new GajiProfil(2L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(29, new GajiProfil(2L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(30, new GajiProfil(2L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(31, new GajiProfil(2L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(32, new GajiProfil(2L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(33, new GajiProfil(2L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(34, new GajiProfil(2L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(1, new GajiProfil(3L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(3L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(3L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(3L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(3L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6, new GajiProfil(3L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7, new GajiProfil(3L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(8, new GajiProfil(3L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(9, new GajiProfil(3L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(10, new GajiProfil(3L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(11, new GajiProfil(3L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(12, new GajiProfil(3L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(13, new GajiProfil(3L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(14, new GajiProfil(3L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(15, new GajiProfil(3L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(16, new GajiProfil(3L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(17, new GajiProfil(3L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(18, new GajiProfil(3L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(19, new GajiProfil(3L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(20, new GajiProfil(3L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(21, new GajiProfil(3L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(22, new GajiProfil(3L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(23, new GajiProfil(3L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(24, new GajiProfil(3L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(25, new GajiProfil(3L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(26, new GajiProfil(3L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(27, new GajiProfil(3L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(28, new GajiProfil(3L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(29, new GajiProfil(3L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(30, new GajiProfil(3L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(31, new GajiProfil(3L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(32, new GajiProfil(3L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(1, new GajiProfil(4L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(4L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(4L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(4L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(4L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6, new GajiProfil(4L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7, new GajiProfil(4L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(8, new GajiProfil(4L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(9, new GajiProfil(4L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(10, new GajiProfil(4L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(11, new GajiProfil(4L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(12, new GajiProfil(4L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(13, new GajiProfil(4L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(14, new GajiProfil(4L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(15, new GajiProfil(4L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(16, new GajiProfil(4L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(17, new GajiProfil(4L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(18, new GajiProfil(4L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(19, new GajiProfil(4L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(20, new GajiProfil(4L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(21, new GajiProfil(4L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(22, new GajiProfil(4L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(23, new GajiProfil(4L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(24, new GajiProfil(4L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(25, new GajiProfil(4L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(26, new GajiProfil(4L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(27, new GajiProfil(4L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(28, new GajiProfil(4L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(29, new GajiProfil(4L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(30, new GajiProfil(4L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(31, new GajiProfil(4L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(32, new GajiProfil(4L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(1, new GajiProfil(5L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(5L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(5L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(5L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(5L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6, new GajiProfil(5L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7, new GajiProfil(5L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(8, new GajiProfil(5L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(9, new GajiProfil(5L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(10, new GajiProfil(5L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(11, new GajiProfil(5L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(12, new GajiProfil(5L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(13, new GajiProfil(5L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(14, new GajiProfil(5L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(15, new GajiProfil(5L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_KK "));
        list.add(new GajiKomponen(16, new GajiProfil(5L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_AIR "));
        list.add(new GajiKomponen(17, new GajiProfil(5L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(18, new GajiProfil(5L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(19, new GajiProfil(5L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(20, new GajiProfil(5L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(21, new GajiProfil(5L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(22, new GajiProfil(5L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(23, new GajiProfil(5L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(24, new GajiProfil(5L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(25, new GajiProfil(5L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(26, new GajiProfil(5L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(27, new GajiProfil(5L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(28, new GajiProfil(5L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(29, new GajiProfil(5L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(30, new GajiProfil(5L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(31, new GajiProfil(5L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(32, new GajiProfil(5L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(1, new GajiProfil(6L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(6L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(6L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(6L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(6L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(6, new GajiProfil(6L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(7, new GajiProfil(6L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(8, new GajiProfil(6L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(9, new GajiProfil(6L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(10, new GajiProfil(6L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(11, new GajiProfil(6L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(12, new GajiProfil(6L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,""));
        list.add(new GajiKomponen(13, new GajiProfil(6L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,""));
        list.add(new GajiKomponen(14, new GajiProfil(6L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(15, new GajiProfil(6L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP"));
        list.add(new GajiKomponen(16, new GajiProfil(6L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(17, new GajiProfil(6L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"GP * 0.02"));
        list.add(new GajiKomponen(18, new GajiProfil(6L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(19, new GajiProfil(6L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"GP * 0.01"));
        list.add(new GajiKomponen(20, new GajiProfil(6L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"GP * 0.01 * REF_ASKES"));
        list.add(new GajiKomponen(21, new GajiProfil(6L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(22, new GajiProfil(6L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(23, new GajiProfil(6L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(24, new GajiProfil(6L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(25, new GajiProfil(6L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(26, new GajiProfil(6L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(1, new GajiProfil(7L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(7L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(7L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(7L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(7L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6, new GajiProfil(7L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7, new GajiProfil(7L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(8, new GajiProfil(7L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(9, new GajiProfil(7L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(10, new GajiProfil(7L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(11, new GajiProfil(7L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(12, new GajiProfil(7L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(13, new GajiProfil(7L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(14, new GajiProfil(7L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(15, new GajiProfil(7L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(16, new GajiProfil(7L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_KK "));
        list.add(new GajiKomponen(17, new GajiProfil(7L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_AIR "));
        list.add(new GajiKomponen(18, new GajiProfil(7L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(19, new GajiProfil(7L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(20, new GajiProfil(7L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(21, new GajiProfil(7L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(22, new GajiProfil(7L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(23, new GajiProfil(7L), "PHDP", "PhDP", EJenisGaji.NONE,0,false,"REF_PHDP "));
        list.add(new GajiKomponen(24, new GajiProfil(7L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,"PHDP * 0.05"));
        list.add(new GajiKomponen(25, new GajiProfil(7L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(26, new GajiProfil(7L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(27, new GajiProfil(7L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(28, new GajiProfil(7L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(29, new GajiProfil(7L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(30, new GajiProfil(7L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(31, new GajiProfil(7L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(32, new GajiProfil(7L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(33, new GajiProfil(7L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(34, new GajiProfil(7L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(1, new GajiProfil(8L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(8L), "REF_TUNJ_JABATAN", "Referensi Tunjangan Jabatan", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(8L), "REF_TUNJ_BERAS", "Referensi Tunjangan Beras", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(8L), "REF_TUNJ_KK", "Referensi Tunjangan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(8L), "REF_TUNJ_AIR", "Referensi Tunjangan Air", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6, new GajiProfil(8L), "REF_PHDP", "Referensi PHDP", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7, new GajiProfil(8L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(8, new GajiProfil(8L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(9, new GajiProfil(8L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(10, new GajiProfil(8L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(11, new GajiProfil(8L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,"0.1 * GP "));
        list.add(new GajiKomponen(12, new GajiProfil(8L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,"JML_ANAK *  ( 0.05 * GP )"));
        list.add(new GajiKomponen(13, new GajiProfil(8L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,"REF_TUNJ_JABATAN "));
        list.add(new GajiKomponen(14, new GajiProfil(8L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,"JML_JIWA * REF_TUNJ_BERAS "));
        list.add(new GajiKomponen(15, new GajiProfil(8L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(16, new GajiProfil(8L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(17, new GajiProfil(8L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(18, new GajiProfil(8L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(19, new GajiProfil(8L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(20, new GajiProfil(8L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05"));
        list.add(new GajiKomponen(21, new GajiProfil(8L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(22, new GajiProfil(8L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,""));
        list.add(new GajiKomponen(23, new GajiProfil(8L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(24, new GajiProfil(8L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(25, new GajiProfil(8L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(26, new GajiProfil(8L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"1750000 * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(27, new GajiProfil(8L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"( REF_JML_POT_KK / 22 ) * GP"));
        list.add(new GajiKomponen(28, new GajiProfil(8L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"TUNJ_PPH21 "));
        list.add(new GajiKomponen(29, new GajiProfil(8L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(30, new GajiProfil(8L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(31, new GajiProfil(8L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(32, new GajiProfil(8L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));
        list.add(new GajiKomponen(1, new GajiProfil(9L), "GP", "Gaji Pokok", EJenisGaji.PEMASUKAN,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(2, new GajiProfil(9L), "REF_PTKP", "Referensi Pendapatan Tidak Kena Pajak", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(3, new GajiProfil(9L), "REF_ASKES", "Referensi Kode ASKES", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(4, new GajiProfil(9L), "REF_SEWA_RUMDIN", "Referensi Sewa Rumah Dinas", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(5, new GajiProfil(9L), "REF_POT_TKK", "Referensi Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(6, new GajiProfil(9L), "REF_JML_POT_KK", "Referensi Jumlah Potongan Kegiatan Kerja", EJenisGaji.NONE,0,true,"#SYSTEM"));
        list.add(new GajiKomponen(7, new GajiProfil(9L), "TUNJ_SI", "Tunjangan Suami Istri", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(8, new GajiProfil(9L), "TUNJ_ANAK", "Tunjangan Anak", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(9, new GajiProfil(9L), "TUNJ_JABATAN", "Tunjangan Jabatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(10, new GajiProfil(9L), "TUNJ_BERAS", "Tunjangan Beras", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(11, new GajiProfil(9L), "TUNJ_KK", "Tunjangan Kegiatan Kerja", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(12, new GajiProfil(9L), "TUNJ_AIR", "Tunjangan Air", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(13, new GajiProfil(9L), "TUNJ_KESEHATAN", "Tunjangan Kesehatan", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(14, new GajiProfil(9L), "ASTEK", "Astek", EJenisGaji.NONE,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489"));
        list.add(new GajiKomponen(15, new GajiProfil(9L), "PKP", "Pendapatan Kena Pajak", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK "));
        list.add(new GajiKomponen(16, new GajiProfil(9L), "TUNJ_PPH21", "Tunjangan PPh 21", EJenisGaji.PEMASUKAN,0,false,""));
        list.add(new GajiKomponen(17, new GajiProfil(9L), "PENGHASILAN_KOTOR", "Penghasilan Kotor", EJenisGaji.NONE,0,false,"GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 "));
        list.add(new GajiKomponen(18, new GajiProfil(9L), "PHDP", "PhDP", EJenisGaji.NONE,23736460,false,""));
        list.add(new GajiKomponen(19, new GajiProfil(9L), "POT_PENSIUN", "Iuran Pensiun", EJenisGaji.POTONGAN,0,false,"PHDP * 0.05"));
        list.add(new GajiKomponen(20, new GajiProfil(9L), "POT_ASTEK", "Potongan Astek", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02"));
        list.add(new GajiKomponen(21, new GajiProfil(9L), "POT_RUDIN", "Potongan Rumah Dinas", EJenisGaji.POTONGAN,0,false,"REF_SEWA_RUMDIN "));
        list.add(new GajiKomponen(22, new GajiProfil(9L), "POT_JP", "Potongan Jaminan Pensiun", EJenisGaji.POTONGAN,0,false,"( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01"));
        list.add(new GajiKomponen(23, new GajiProfil(9L), "POT_ASKES", "Potongan BPJS Kesehatan", EJenisGaji.POTONGAN,0,false,"( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES "));
        list.add(new GajiKomponen(24, new GajiProfil(9L), "POT_TKK", "Potongan TKK", EJenisGaji.POTONGAN,0,false,"REF_JML_POT_KK * REF_POT_TKK "));
        list.add(new GajiKomponen(25, new GajiProfil(9L), "POT_PPH21", "Potongan PPh 21", EJenisGaji.POTONGAN,0,false,"( PKP - ( 0.05 * PKP ) - REF_PTKP ) * 0.1"));
        list.add(new GajiKomponen(26, new GajiProfil(9L), "POTONGAN", "Total Potongan", EJenisGaji.NONE,0,false,"POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 "));
        list.add(new GajiKomponen(27, new GajiProfil(9L), "PENGHASILAN_BERSIH", "Penghasilan Bersih", EJenisGaji.NONE,0,false,"PENGHASILAN_KOTOR - POTONGAN "));
        list.add(new GajiKomponen(28, new GajiProfil(9L), "PEMBULATAN", "Pembulatan", EJenisGaji.NONE,0,false,"( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH "));
        list.add(new GajiKomponen(29, new GajiProfil(9L), "PENGHASILAN_BERSIH_FINAL", "Penghasilan Bersih Final", EJenisGaji.NONE,0,false,"PENGHASILAN_BERSIH + PEMBULATAN "));

        repository.saveAll(list);
    }
}
