/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq;


import id.perumdamts.kepegawaian.jooq.tables.AlatKerja;
import id.perumdamts.kepegawaian.jooq.tables.Apd;
import id.perumdamts.kepegawaian.jooq.tables.Golongan;
import id.perumdamts.kepegawaian.jooq.tables.Grade;
import id.perumdamts.kepegawaian.jooq.tables.Jabatan;
import id.perumdamts.kepegawaian.jooq.tables.JenisSp;
import id.perumdamts.kepegawaian.jooq.tables.Level;
import id.perumdamts.kepegawaian.jooq.tables.Organisasi;
import id.perumdamts.kepegawaian.jooq.tables.Profesi;
import id.perumdamts.kepegawaian.jooq.tables.SanksiSp;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in kepegawaian.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ALAT_KERJA_IDX_ALAT_KERJA_IS_DELETED = Internal.createIndex(DSL.name("idx_alat_kerja_is_deleted"), AlatKerja.ALAT_KERJA, new OrderField[] { AlatKerja.ALAT_KERJA.IS_DELETED }, false);
    public static final Index ALAT_KERJA_IDX_ALAT_KERJA_NAMA = Internal.createIndex(DSL.name("idx_alat_kerja_nama"), AlatKerja.ALAT_KERJA, new OrderField[] { AlatKerja.ALAT_KERJA.NAMA }, false);
    public static final Index ALAT_KERJA_IDX_ALAT_KERJA_PROFESI = Internal.createIndex(DSL.name("idx_alat_kerja_profesi"), AlatKerja.ALAT_KERJA, new OrderField[] { AlatKerja.ALAT_KERJA.PROFESI_ID }, false);
    public static final Index APD_IDX_APD_IS_DELETED = Internal.createIndex(DSL.name("idx_apd_is_deleted"), Apd.APD, new OrderField[] { Apd.APD.IS_DELETED }, false);
    public static final Index APD_IDX_APD_NAMA = Internal.createIndex(DSL.name("idx_apd_nama"), Apd.APD, new OrderField[] { Apd.APD.NAMA }, false);
    public static final Index APD_IDX_APD_PROFESI = Internal.createIndex(DSL.name("idx_apd_profesi"), Apd.APD, new OrderField[] { Apd.APD.PROFESI_ID }, false);
    public static final Index GOLONGAN_IDX_GOLONGAN_GOLONGAN = Internal.createIndex(DSL.name("idx_golongan_golongan"), Golongan.GOLONGAN, new OrderField[] { Golongan.GOLONGAN.GOLONGAN_ }, false);
    public static final Index GOLONGAN_IDX_GOLONGAN_IS_DELETED = Internal.createIndex(DSL.name("idx_golongan_is_deleted"), Golongan.GOLONGAN, new OrderField[] { Golongan.GOLONGAN.IS_DELETED }, false);
    public static final Index GRADE_IDX_GRADE_GRADE = Internal.createIndex(DSL.name("idx_grade_grade"), Grade.GRADE, new OrderField[] { Grade.GRADE.GRADE_ }, false);
    public static final Index GRADE_IDX_GRADE_IS_DELETED = Internal.createIndex(DSL.name("idx_grade_is_deleted"), Grade.GRADE, new OrderField[] { Grade.GRADE.IS_DELETED }, false);
    public static final Index GRADE_IDX_GRADE_LEVEL = Internal.createIndex(DSL.name("idx_grade_level"), Grade.GRADE, new OrderField[] { Grade.GRADE.LEVEL_ID }, false);
    public static final Index JABATAN_IDX_JABATAN_IS_DELETED = Internal.createIndex(DSL.name("idx_jabatan_is_deleted"), Jabatan.JABATAN, new OrderField[] { Jabatan.JABATAN.IS_DELETED }, false);
    public static final Index JABATAN_IDX_JABATAN_KODE = Internal.createIndex(DSL.name("idx_jabatan_kode"), Jabatan.JABATAN, new OrderField[] { Jabatan.JABATAN.KODE }, false);
    public static final Index JABATAN_IDX_JABATAN_LEVEL = Internal.createIndex(DSL.name("idx_jabatan_level"), Jabatan.JABATAN, new OrderField[] { Jabatan.JABATAN.LEVEL_ID }, false);
    public static final Index JABATAN_IDX_JABATAN_NAMA = Internal.createIndex(DSL.name("idx_jabatan_nama"), Jabatan.JABATAN, new OrderField[] { Jabatan.JABATAN.NAMA }, false);
    public static final Index JABATAN_IDX_JABATAN_ORGANISASI = Internal.createIndex(DSL.name("idx_jabatan_organisasi"), Jabatan.JABATAN, new OrderField[] { Jabatan.JABATAN.ORGANISASI_ID }, false);
    public static final Index JABATAN_IDX_JABATAN_PARENT = Internal.createIndex(DSL.name("idx_jabatan_parent"), Jabatan.JABATAN, new OrderField[] { Jabatan.JABATAN.PARENT_ID }, false);
    public static final Index JENIS_SP_IDX_JENIS_SP_IS_DELETED = Internal.createIndex(DSL.name("idx_jenis_sp_is_deleted"), JenisSp.JENIS_SP, new OrderField[] { JenisSp.JENIS_SP.IS_DELETED }, false);
    public static final Index LEVEL_IDX_LEVEL_IS_DELETED = Internal.createIndex(DSL.name("idx_level_is_deleted"), Level.LEVEL, new OrderField[] { Level.LEVEL.IS_DELETED }, false);
    public static final Index LEVEL_IDX_LEVEL_NAMA = Internal.createIndex(DSL.name("idx_level_nama"), Level.LEVEL, new OrderField[] { Level.LEVEL.NAMA }, false);
    public static final Index ORGANISASI_IDX_ORGANISASI_IS_DELETED = Internal.createIndex(DSL.name("idx_organisasi_is_deleted"), Organisasi.ORGANISASI, new OrderField[] { Organisasi.ORGANISASI.IS_DELETED }, false);
    public static final Index ORGANISASI_IDX_ORGANISASI_KODE = Internal.createIndex(DSL.name("idx_organisasi_kode"), Organisasi.ORGANISASI, new OrderField[] { Organisasi.ORGANISASI.KODE }, false);
    public static final Index ORGANISASI_IDX_ORGANISASI_LEVEL_ORG = Internal.createIndex(DSL.name("idx_organisasi_level_org"), Organisasi.ORGANISASI, new OrderField[] { Organisasi.ORGANISASI.LEVEL_ORG }, false);
    public static final Index ORGANISASI_IDX_ORGANISASI_NAMA = Internal.createIndex(DSL.name("idx_organisasi_nama"), Organisasi.ORGANISASI, new OrderField[] { Organisasi.ORGANISASI.NAMA }, false);
    public static final Index ORGANISASI_IDX_ORGANISASI_PARENT = Internal.createIndex(DSL.name("idx_organisasi_parent"), Organisasi.ORGANISASI, new OrderField[] { Organisasi.ORGANISASI.PARENT_ID }, false);
    public static final Index PROFESI_IDX_PROFESI_GRADE = Internal.createIndex(DSL.name("idx_profesi_grade"), Profesi.PROFESI, new OrderField[] { Profesi.PROFESI.GRADE_ID }, false);
    public static final Index PROFESI_IDX_PROFESI_IS_DELETED = Internal.createIndex(DSL.name("idx_profesi_is_deleted"), Profesi.PROFESI, new OrderField[] { Profesi.PROFESI.IS_DELETED }, false);
    public static final Index PROFESI_IDX_PROFESI_JABATAN = Internal.createIndex(DSL.name("idx_profesi_jabatan"), Profesi.PROFESI, new OrderField[] { Profesi.PROFESI.JABATAN_ID }, false);
    public static final Index PROFESI_IDX_PROFESI_LEVEL = Internal.createIndex(DSL.name("idx_profesi_level"), Profesi.PROFESI, new OrderField[] { Profesi.PROFESI.LEVEL_ID }, false);
    public static final Index PROFESI_IDX_PROFESI_NAMA = Internal.createIndex(DSL.name("idx_profesi_nama"), Profesi.PROFESI, new OrderField[] { Profesi.PROFESI.NAMA }, false);
    public static final Index PROFESI_IDX_PROFESI_ORGANISASI = Internal.createIndex(DSL.name("idx_profesi_organisasi"), Profesi.PROFESI, new OrderField[] { Profesi.PROFESI.ORGANISASI_ID }, false);
    public static final Index SANKSI_SP_IDX_SANKSI_SP_IS_DELETED = Internal.createIndex(DSL.name("idx_sanksi_sp_is_deleted"), SanksiSp.SANKSI_SP, new OrderField[] { SanksiSp.SANKSI_SP.IS_DELETED }, false);
    public static final Index SANKSI_SP_IDX_SANKSI_SP_JENIS_SP = Internal.createIndex(DSL.name("idx_sanksi_sp_jenis_sp"), SanksiSp.SANKSI_SP, new OrderField[] { SanksiSp.SANKSI_SP.JENIS_SP_ID }, false);
    public static final Index SANKSI_SP_IDX_SANKSI_SP_KODE = Internal.createIndex(DSL.name("idx_sanksi_sp_kode"), SanksiSp.SANKSI_SP, new OrderField[] { SanksiSp.SANKSI_SP.KODE }, false);
}
