/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq;


import id.perumdamts.kepegawaian.jooq.tables.AlasanBerhenti;
import id.perumdamts.kepegawaian.jooq.tables.AlatKerja;
import id.perumdamts.kepegawaian.jooq.tables.Apd;
import id.perumdamts.kepegawaian.jooq.tables.CutiJenis;
import id.perumdamts.kepegawaian.jooq.tables.DasarGaji;
import id.perumdamts.kepegawaian.jooq.tables.DetailDasarGaji;
import id.perumdamts.kepegawaian.jooq.tables.GajiKomponen;
import id.perumdamts.kepegawaian.jooq.tables.GajiParameterSetting;
import id.perumdamts.kepegawaian.jooq.tables.GajiPendapatanNonPajak;
import id.perumdamts.kepegawaian.jooq.tables.GajiPotonganTkk;
import id.perumdamts.kepegawaian.jooq.tables.GajiProfil;
import id.perumdamts.kepegawaian.jooq.tables.GajiTunjangan;
import id.perumdamts.kepegawaian.jooq.tables.Golongan;
import id.perumdamts.kepegawaian.jooq.tables.Grade;
import id.perumdamts.kepegawaian.jooq.tables.Jabatan;
import id.perumdamts.kepegawaian.jooq.tables.JenisKeahlian;
import id.perumdamts.kepegawaian.jooq.tables.JenisKitas;
import id.perumdamts.kepegawaian.jooq.tables.JenisPelatihan;
import id.perumdamts.kepegawaian.jooq.tables.JenisSp;
import id.perumdamts.kepegawaian.jooq.tables.JenjangPendidikan;
import id.perumdamts.kepegawaian.jooq.tables.Level;
import id.perumdamts.kepegawaian.jooq.tables.Organisasi;
import id.perumdamts.kepegawaian.jooq.tables.PrefRole;
import id.perumdamts.kepegawaian.jooq.tables.Profesi;
import id.perumdamts.kepegawaian.jooq.tables.RumahDinas;
import id.perumdamts.kepegawaian.jooq.tables.SanksiSp;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Kepegawaian extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian</code>
     */
    public static final Kepegawaian KEPEGAWAIAN = new Kepegawaian();

    /**
     * The table <code>kepegawaian.alasan_berhenti</code>.
     */
    public final AlasanBerhenti ALASAN_BERHENTI = AlasanBerhenti.ALASAN_BERHENTI;

    /**
     * The table <code>kepegawaian.alat_kerja</code>.
     */
    public final AlatKerja ALAT_KERJA = AlatKerja.ALAT_KERJA;

    /**
     * The table <code>kepegawaian.apd</code>.
     */
    public final Apd APD = Apd.APD;

    /**
     * The table <code>kepegawaian.cuti_jenis</code>.
     */
    public final CutiJenis CUTI_JENIS = CutiJenis.CUTI_JENIS;

    /**
     * The table <code>kepegawaian.dasar_gaji</code>.
     */
    public final DasarGaji DASAR_GAJI = DasarGaji.DASAR_GAJI;

    /**
     * The table <code>kepegawaian.detail_dasar_gaji</code>.
     */
    public final DetailDasarGaji DETAIL_DASAR_GAJI = DetailDasarGaji.DETAIL_DASAR_GAJI;

    /**
     * The table <code>kepegawaian.gaji_komponen</code>.
     */
    public final GajiKomponen GAJI_KOMPONEN = GajiKomponen.GAJI_KOMPONEN;

    /**
     * The table <code>kepegawaian.gaji_parameter_setting</code>.
     */
    public final GajiParameterSetting GAJI_PARAMETER_SETTING = GajiParameterSetting.GAJI_PARAMETER_SETTING;

    /**
     * The table <code>kepegawaian.gaji_pendapatan_non_pajak</code>.
     */
    public final GajiPendapatanNonPajak GAJI_PENDAPATAN_NON_PAJAK = GajiPendapatanNonPajak.GAJI_PENDAPATAN_NON_PAJAK;

    /**
     * The table <code>kepegawaian.gaji_potongan_tkk</code>.
     */
    public final GajiPotonganTkk GAJI_POTONGAN_TKK = GajiPotonganTkk.GAJI_POTONGAN_TKK;

    /**
     * The table <code>kepegawaian.gaji_profil</code>.
     */
    public final GajiProfil GAJI_PROFIL = GajiProfil.GAJI_PROFIL;

    /**
     * The table <code>kepegawaian.gaji_tunjangan</code>.
     */
    public final GajiTunjangan GAJI_TUNJANGAN = GajiTunjangan.GAJI_TUNJANGAN;

    /**
     * The table <code>kepegawaian.golongan</code>.
     */
    public final Golongan GOLONGAN = Golongan.GOLONGAN;

    /**
     * The table <code>kepegawaian.grade</code>.
     */
    public final Grade GRADE = Grade.GRADE;

    /**
     * The table <code>kepegawaian.jabatan</code>.
     */
    public final Jabatan JABATAN = Jabatan.JABATAN;

    /**
     * The table <code>kepegawaian.jenis_keahlian</code>.
     */
    public final JenisKeahlian JENIS_KEAHLIAN = JenisKeahlian.JENIS_KEAHLIAN;

    /**
     * The table <code>kepegawaian.jenis_kitas</code>.
     */
    public final JenisKitas JENIS_KITAS = JenisKitas.JENIS_KITAS;

    /**
     * The table <code>kepegawaian.jenis_pelatihan</code>.
     */
    public final JenisPelatihan JENIS_PELATIHAN = JenisPelatihan.JENIS_PELATIHAN;

    /**
     * The table <code>kepegawaian.jenis_sp</code>.
     */
    public final JenisSp JENIS_SP = JenisSp.JENIS_SP;

    /**
     * The table <code>kepegawaian.jenjang_pendidikan</code>.
     */
    public final JenjangPendidikan JENJANG_PENDIDIKAN = JenjangPendidikan.JENJANG_PENDIDIKAN;

    /**
     * The table <code>kepegawaian.level</code>.
     */
    public final Level LEVEL = Level.LEVEL;

    /**
     * The table <code>kepegawaian.organisasi</code>.
     */
    public final Organisasi ORGANISASI = Organisasi.ORGANISASI;

    /**
     * The table <code>kepegawaian.pref_role</code>.
     */
    public final PrefRole PREF_ROLE = PrefRole.PREF_ROLE;

    /**
     * The table <code>kepegawaian.profesi</code>.
     */
    public final Profesi PROFESI = Profesi.PROFESI;

    /**
     * The table <code>kepegawaian.rumah_dinas</code>.
     */
    public final RumahDinas RUMAH_DINAS = RumahDinas.RUMAH_DINAS;

    /**
     * The table <code>kepegawaian.sanksi_sp</code>.
     */
    public final SanksiSp SANKSI_SP = SanksiSp.SANKSI_SP;

    /**
     * No further instances allowed
     */
    private Kepegawaian() {
        super("kepegawaian", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AlasanBerhenti.ALASAN_BERHENTI,
            AlatKerja.ALAT_KERJA,
            Apd.APD,
            CutiJenis.CUTI_JENIS,
            DasarGaji.DASAR_GAJI,
            DetailDasarGaji.DETAIL_DASAR_GAJI,
            GajiKomponen.GAJI_KOMPONEN,
            GajiParameterSetting.GAJI_PARAMETER_SETTING,
            GajiPendapatanNonPajak.GAJI_PENDAPATAN_NON_PAJAK,
            GajiPotonganTkk.GAJI_POTONGAN_TKK,
            GajiProfil.GAJI_PROFIL,
            GajiTunjangan.GAJI_TUNJANGAN,
            Golongan.GOLONGAN,
            Grade.GRADE,
            Jabatan.JABATAN,
            JenisKeahlian.JENIS_KEAHLIAN,
            JenisKitas.JENIS_KITAS,
            JenisPelatihan.JENIS_PELATIHAN,
            JenisSp.JENIS_SP,
            JenjangPendidikan.JENJANG_PENDIDIKAN,
            Level.LEVEL,
            Organisasi.ORGANISASI,
            PrefRole.PREF_ROLE,
            Profesi.PROFESI,
            RumahDinas.RUMAH_DINAS,
            SanksiSp.SANKSI_SP
        );
    }
}
