/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq;


import id.perumdamts.kepegawaian.jooq.tables.AlasanBerhenti;
import id.perumdamts.kepegawaian.jooq.tables.AlatKerja;
import id.perumdamts.kepegawaian.jooq.tables.Apd;
import id.perumdamts.kepegawaian.jooq.tables.CutiJenis;
import id.perumdamts.kepegawaian.jooq.tables.DasarGaji;
import id.perumdamts.kepegawaian.jooq.tables.DetailDasarGaji;
import id.perumdamts.kepegawaian.jooq.tables.GajiKomponen;
import id.perumdamts.kepegawaian.jooq.tables.GajiParameterSetting;
import id.perumdamts.kepegawaian.jooq.tables.GajiPendapatanNonPajak;
import id.perumdamts.kepegawaian.jooq.tables.GajiPotonganTkk;
import id.perumdamts.kepegawaian.jooq.tables.GajiProfil;
import id.perumdamts.kepegawaian.jooq.tables.GajiTunjangan;
import id.perumdamts.kepegawaian.jooq.tables.Golongan;
import id.perumdamts.kepegawaian.jooq.tables.Grade;
import id.perumdamts.kepegawaian.jooq.tables.Jabatan;
import id.perumdamts.kepegawaian.jooq.tables.JenisKeahlian;
import id.perumdamts.kepegawaian.jooq.tables.JenisKitas;
import id.perumdamts.kepegawaian.jooq.tables.JenisPelatihan;
import id.perumdamts.kepegawaian.jooq.tables.JenisSp;
import id.perumdamts.kepegawaian.jooq.tables.JenjangPendidikan;
import id.perumdamts.kepegawaian.jooq.tables.Level;
import id.perumdamts.kepegawaian.jooq.tables.Organisasi;
import id.perumdamts.kepegawaian.jooq.tables.PrefRole;
import id.perumdamts.kepegawaian.jooq.tables.Profesi;
import id.perumdamts.kepegawaian.jooq.tables.RumahDinas;
import id.perumdamts.kepegawaian.jooq.tables.SanksiSp;


/**
 * Convenience access to all tables in kepegawaian.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>kepegawaian.alasan_berhenti</code>.
     */
    public static final AlasanBerhenti ALASAN_BERHENTI = AlasanBerhenti.ALASAN_BERHENTI;

    /**
     * The table <code>kepegawaian.alat_kerja</code>.
     */
    public static final AlatKerja ALAT_KERJA = AlatKerja.ALAT_KERJA;

    /**
     * The table <code>kepegawaian.apd</code>.
     */
    public static final Apd APD = Apd.APD;

    /**
     * The table <code>kepegawaian.cuti_jenis</code>.
     */
    public static final CutiJenis CUTI_JENIS = CutiJenis.CUTI_JENIS;

    /**
     * The table <code>kepegawaian.dasar_gaji</code>.
     */
    public static final DasarGaji DASAR_GAJI = DasarGaji.DASAR_GAJI;

    /**
     * The table <code>kepegawaian.detail_dasar_gaji</code>.
     */
    public static final DetailDasarGaji DETAIL_DASAR_GAJI = DetailDasarGaji.DETAIL_DASAR_GAJI;

    /**
     * The table <code>kepegawaian.gaji_komponen</code>.
     */
    public static final GajiKomponen GAJI_KOMPONEN = GajiKomponen.GAJI_KOMPONEN;

    /**
     * The table <code>kepegawaian.gaji_parameter_setting</code>.
     */
    public static final GajiParameterSetting GAJI_PARAMETER_SETTING = GajiParameterSetting.GAJI_PARAMETER_SETTING;

    /**
     * The table <code>kepegawaian.gaji_pendapatan_non_pajak</code>.
     */
    public static final GajiPendapatanNonPajak GAJI_PENDAPATAN_NON_PAJAK = GajiPendapatanNonPajak.GAJI_PENDAPATAN_NON_PAJAK;

    /**
     * The table <code>kepegawaian.gaji_potongan_tkk</code>.
     */
    public static final GajiPotonganTkk GAJI_POTONGAN_TKK = GajiPotonganTkk.GAJI_POTONGAN_TKK;

    /**
     * The table <code>kepegawaian.gaji_profil</code>.
     */
    public static final GajiProfil GAJI_PROFIL = GajiProfil.GAJI_PROFIL;

    /**
     * The table <code>kepegawaian.gaji_tunjangan</code>.
     */
    public static final GajiTunjangan GAJI_TUNJANGAN = GajiTunjangan.GAJI_TUNJANGAN;

    /**
     * The table <code>kepegawaian.golongan</code>.
     */
    public static final Golongan GOLONGAN = Golongan.GOLONGAN;

    /**
     * The table <code>kepegawaian.grade</code>.
     */
    public static final Grade GRADE = Grade.GRADE;

    /**
     * The table <code>kepegawaian.jabatan</code>.
     */
    public static final Jabatan JABATAN = Jabatan.JABATAN;

    /**
     * The table <code>kepegawaian.jenis_keahlian</code>.
     */
    public static final JenisKeahlian JENIS_KEAHLIAN = JenisKeahlian.JENIS_KEAHLIAN;

    /**
     * The table <code>kepegawaian.jenis_kitas</code>.
     */
    public static final JenisKitas JENIS_KITAS = JenisKitas.JENIS_KITAS;

    /**
     * The table <code>kepegawaian.jenis_pelatihan</code>.
     */
    public static final JenisPelatihan JENIS_PELATIHAN = JenisPelatihan.JENIS_PELATIHAN;

    /**
     * The table <code>kepegawaian.jenis_sp</code>.
     */
    public static final JenisSp JENIS_SP = JenisSp.JENIS_SP;

    /**
     * The table <code>kepegawaian.jenjang_pendidikan</code>.
     */
    public static final JenjangPendidikan JENJANG_PENDIDIKAN = JenjangPendidikan.JENJANG_PENDIDIKAN;

    /**
     * The table <code>kepegawaian.level</code>.
     */
    public static final Level LEVEL = Level.LEVEL;

    /**
     * The table <code>kepegawaian.organisasi</code>.
     */
    public static final Organisasi ORGANISASI = Organisasi.ORGANISASI;

    /**
     * The table <code>kepegawaian.pref_role</code>.
     */
    public static final PrefRole PREF_ROLE = PrefRole.PREF_ROLE;

    /**
     * The table <code>kepegawaian.profesi</code>.
     */
    public static final Profesi PROFESI = Profesi.PROFESI;

    /**
     * The table <code>kepegawaian.rumah_dinas</code>.
     */
    public static final RumahDinas RUMAH_DINAS = RumahDinas.RUMAH_DINAS;

    /**
     * The table <code>kepegawaian.sanksi_sp</code>.
     */
    public static final SanksiSp SANKSI_SP = SanksiSp.SANKSI_SP;
}
