server:
  port: ${SERVER_PORT:8080}

spring:
  devtools:
    restart:
      enabled: ${DEVELOPMENT:false}
  profiles:
    active: ${PROFILE:development}
  main:
    banner-mode: off
  application:
    name: kepegawaian
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mariadb://${DB_HOST:192.168.230.84}:${DB_PORT:3307}/${DB_SCHEMA:kepegawaian_dev_new}?useSSL=false&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&server=mysql
    username: ${DB_USER:dev}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        column_ordering_strategy: legacy
  #      org:
  #        hibernate:
  #          envers:
  #            audit_table_suffix: _aud
  #            revision_field_name: rev
  #            revision_type_field_name: revtype
  #            store_data_at_delete: true
  #      javax:
  #        persistence:
  #          schema-generation:
  #            scripts:
  #              action: create
  #              create-target: create.sql
  #              create-source: metadata
  #              drop-target: drop.sql
  #              drop-source: metadata
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.1.214:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic: ${KAFKA_TOPIC:penggajian}
  data:
    redis:
      host: ${REDIS_HOST:192.168.1.214}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
  docker:
    compose:
      enabled: false
#    consumer:
#      group-id: kepegawaian
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.build.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.build.serialization.StringDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: id.perumdamts.kepegawaian

logging:
  level:
    org:
      spring:
        security: DEBUG
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

appwrite:
  endpoint: ${APPWRITE_ENDPOINT:http://192.168.230.254:82/v1}
  project_id: ${APPWRITE_PROJECT_ID:65cd62cc3385d8434a53}
  api_key: ${APPWRITE_API_KEY}

penggajian:
  endpoint: ${PENGGAJIAN_URL:http://192.168.1.214:81}
laporan:
  kepegawaian:
    endpoint: ${LAPORAN_KEPEGAWAIAN_URL:http://192.168.1.214:82}

custom:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000
  protected:
    delete:
      kartuIdentitas:
        ktp: ${PROTECTED_DELETE_KTP:1}
  jenisCuti:
    tahunan: ${JENIS_CUTI_TAHUNAN:1}
    besar: ${JENIS_CUTI_BESAR:2}
    ibadah: ${JENIS_CUTI_IBADAH:4}
  jabatan:
    direkturUtama: ${JABATAN_DIREKTUR_UTAMA:2}
    direkturTeknik: ${JABATAN_DIREKTUR_TEKNIK:3}
    direkturUmum: ${JABATAN_DIREKTUR_UMUM:25}
    managerSdm: ${JABATAN_MANAGER_SDM:48}
    supervisorSdm: ${JABATAN_SUPERVISOR_SDM:49}
  levelJabatan:
    direkturUtama: ${LEVEL_DIREKTUR_UTAMA:2}
    direkturTeknik: ${LEVEL_DIREKTUR_TEKNIK:3}
    direkturUmum: ${LEVEL_DIREKTUR_UMUM:4}
    manager: ${LEVEL_MANAGER:5}
    supervisor: ${LEVEL_SUPERVISOR:6}
    staff: ${LEVEL_STAFF:7}
  security:
    dev:
      roles: ${DEV_ROLES:ADMIN,SYSTEM,SDM}

