/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Revinfo.RevinfoPath;
import id.perumdamts.kepegawaian.jooq.tables.records.CutiApprovalAudRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CutiApprovalAud extends TableImpl<CutiApprovalAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.cuti_approval_aud</code>
     */
    public static final CutiApprovalAud CUTI_APPROVAL_AUD = new CutiApprovalAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CutiApprovalAudRecord> getRecordType() {
        return CutiApprovalAudRecord.class;
    }

    /**
     * The column <code>kepegawaian.cuti_approval_aud.id</code>.
     */
    public final TableField<CutiApprovalAudRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.rev</code>.
     */
    public final TableField<CutiApprovalAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.revtype</code>.
     */
    public final TableField<CutiApprovalAudRecord, Byte> REVTYPE = createField(DSL.name("revtype"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.changed_status</code>.
     */
    public final TableField<CutiApprovalAudRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.created_at</code>.
     */
    public final TableField<CutiApprovalAudRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.created_by</code>.
     */
    public final TableField<CutiApprovalAudRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.is_deleted</code>.
     */
    public final TableField<CutiApprovalAudRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.updated_at</code>.
     */
    public final TableField<CutiApprovalAudRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.updated_by</code>.
     */
    public final TableField<CutiApprovalAudRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.approval_level</code>.
     */
    public final TableField<CutiApprovalAudRecord, Integer> APPROVAL_LEVEL = createField(DSL.name("approval_level"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.approval_status</code>.
     */
    public final TableField<CutiApprovalAudRecord, Byte> APPROVAL_STATUS = createField(DSL.name("approval_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.notes</code>.
     */
    public final TableField<CutiApprovalAudRecord, String> NOTES = createField(DSL.name("notes"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.approver_id</code>.
     */
    public final TableField<CutiApprovalAudRecord, Long> APPROVER_ID = createField(DSL.name("approver_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.cuti_pegawai_id</code>.
     */
    public final TableField<CutiApprovalAudRecord, Long> CUTI_PEGAWAI_ID = createField(DSL.name("cuti_pegawai_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.cuti_approval_aud.jabatan_id</code>.
     */
    public final TableField<CutiApprovalAudRecord, Long> JABATAN_ID = createField(DSL.name("jabatan_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    private CutiApprovalAud(Name alias, Table<CutiApprovalAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CutiApprovalAud(Name alias, Table<CutiApprovalAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.cuti_approval_aud</code> table
     * reference
     */
    public CutiApprovalAud(String alias) {
        this(DSL.name(alias), CUTI_APPROVAL_AUD);
    }

    /**
     * Create an aliased <code>kepegawaian.cuti_approval_aud</code> table
     * reference
     */
    public CutiApprovalAud(Name alias) {
        this(alias, CUTI_APPROVAL_AUD);
    }

    /**
     * Create a <code>kepegawaian.cuti_approval_aud</code> table reference
     */
    public CutiApprovalAud() {
        this(DSL.name("cuti_approval_aud"), null);
    }

    public <O extends Record> CutiApprovalAud(Table<O> path, ForeignKey<O, CutiApprovalAudRecord> childPath, InverseForeignKey<O, CutiApprovalAudRecord> parentPath) {
        super(path, childPath, parentPath, CUTI_APPROVAL_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CutiApprovalAudPath extends CutiApprovalAud implements Path<CutiApprovalAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CutiApprovalAudPath(Table<O> path, ForeignKey<O, CutiApprovalAudRecord> childPath, InverseForeignKey<O, CutiApprovalAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CutiApprovalAudPath(Name alias, Table<CutiApprovalAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CutiApprovalAudPath as(String alias) {
            return new CutiApprovalAudPath(DSL.name(alias), this);
        }

        @Override
        public CutiApprovalAudPath as(Name alias) {
            return new CutiApprovalAudPath(alias, this);
        }

        @Override
        public CutiApprovalAudPath as(Table<?> alias) {
            return new CutiApprovalAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<CutiApprovalAudRecord> getPrimaryKey() {
        return Keys.KEY_CUTI_APPROVAL_AUD_PRIMARY;
    }

    @Override
    public List<ForeignKey<CutiApprovalAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK20COYHPWFQDUFHCGCIMB525T7);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>kepegawaian.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.FK20COYHPWFQDUFHCGCIMB525T7, null);

        return _revinfo;
    }

    @Override
    public CutiApprovalAud as(String alias) {
        return new CutiApprovalAud(DSL.name(alias), this);
    }

    @Override
    public CutiApprovalAud as(Name alias) {
        return new CutiApprovalAud(alias, this);
    }

    @Override
    public CutiApprovalAud as(Table<?> alias) {
        return new CutiApprovalAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CutiApprovalAud rename(String name) {
        return new CutiApprovalAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CutiApprovalAud rename(Name name) {
        return new CutiApprovalAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CutiApprovalAud rename(Table<?> name) {
        return new CutiApprovalAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CutiApprovalAud where(Condition condition) {
        return new CutiApprovalAud(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CutiApprovalAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CutiApprovalAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CutiApprovalAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CutiApprovalAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CutiApprovalAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CutiApprovalAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CutiApprovalAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CutiApprovalAud whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CutiApprovalAud whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
