/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.enums.GajiBatchMasterProsesJenisGaji;
import id.perumdamts.kepegawaian.jooq.tables.records.GajiBatchMasterProsesRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GajiBatchMasterProses extends TableImpl<GajiBatchMasterProsesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>kepegawaian.gaji_batch_master_proses</code>
     */
    public static final GajiBatchMasterProses GAJI_BATCH_MASTER_PROSES = new GajiBatchMasterProses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GajiBatchMasterProsesRecord> getRecordType() {
        return GajiBatchMasterProsesRecord.class;
    }

    /**
     * The column <code>kepegawaian.gaji_batch_master_proses.id</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_batch_master_proses.batch_master_id</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, Long> BATCH_MASTER_ID = createField(DSL.name("batch_master_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.gaji_batch_master_proses.formula</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, String> FORMULA = createField(DSL.name("formula"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_batch_master_proses.jenis_gaji</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, GajiBatchMasterProsesJenisGaji> JENIS_GAJI = createField(DSL.name("jenis_gaji"), SQLDataType.VARCHAR(9).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)).asEnumDataType(GajiBatchMasterProsesJenisGaji.class), this, "");

    /**
     * The column <code>kepegawaian.gaji_batch_master_proses.kode</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, String> KODE = createField(DSL.name("kode"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_batch_master_proses.nama</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, String> NAMA = createField(DSL.name("nama"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_batch_master_proses.nilai</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, Double> NILAI = createField(DSL.name("nilai"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_batch_master_proses.nilai_formula</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, String> NILAI_FORMULA = createField(DSL.name("nilai_formula"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_batch_master_proses.urut</code>.
     */
    public final TableField<GajiBatchMasterProsesRecord, Integer> URUT = createField(DSL.name("urut"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private GajiBatchMasterProses(Name alias, Table<GajiBatchMasterProsesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GajiBatchMasterProses(Name alias, Table<GajiBatchMasterProsesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.gaji_batch_master_proses</code> table
     * reference
     */
    public GajiBatchMasterProses(String alias) {
        this(DSL.name(alias), GAJI_BATCH_MASTER_PROSES);
    }

    /**
     * Create an aliased <code>kepegawaian.gaji_batch_master_proses</code> table
     * reference
     */
    public GajiBatchMasterProses(Name alias) {
        this(alias, GAJI_BATCH_MASTER_PROSES);
    }

    /**
     * Create a <code>kepegawaian.gaji_batch_master_proses</code> table
     * reference
     */
    public GajiBatchMasterProses() {
        this(DSL.name("gaji_batch_master_proses"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GAJI_BATCH_MASTER_PROSES_IDX4M7UF76B7PCXHTBD1D5BBE3J, Indexes.GAJI_BATCH_MASTER_PROSES_IDX8C7F8XMW7AHW2VPFOCCUJ5SOA, Indexes.GAJI_BATCH_MASTER_PROSES_IDXE5G9XPIWFVUGCGQH7G3A5TGU0, Indexes.GAJI_BATCH_MASTER_PROSES_IDXOJ7601U6FWTLV4O9WQ30PKLKQ);
    }

    @Override
    public Identity<GajiBatchMasterProsesRecord, Long> getIdentity() {
        return (Identity<GajiBatchMasterProsesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GajiBatchMasterProsesRecord> getPrimaryKey() {
        return Keys.KEY_GAJI_BATCH_MASTER_PROSES_PRIMARY;
    }

    @Override
    public GajiBatchMasterProses as(String alias) {
        return new GajiBatchMasterProses(DSL.name(alias), this);
    }

    @Override
    public GajiBatchMasterProses as(Name alias) {
        return new GajiBatchMasterProses(alias, this);
    }

    @Override
    public GajiBatchMasterProses as(Table<?> alias) {
        return new GajiBatchMasterProses(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiBatchMasterProses rename(String name) {
        return new GajiBatchMasterProses(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiBatchMasterProses rename(Name name) {
        return new GajiBatchMasterProses(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiBatchMasterProses rename(Table<?> name) {
        return new GajiBatchMasterProses(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiBatchMasterProses where(Condition condition) {
        return new GajiBatchMasterProses(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiBatchMasterProses where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiBatchMasterProses where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiBatchMasterProses where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiBatchMasterProses where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiBatchMasterProses where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiBatchMasterProses where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiBatchMasterProses where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiBatchMasterProses whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiBatchMasterProses whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
