/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.DefaultSchema;
import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Golongan.GolonganPath;
import id.perumdamts.kepegawaian.jooq.tables.Level.LevelPath;
import id.perumdamts.kepegawaian.jooq.tables.records.GajiPotonganTkkRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GajiPotonganTkk extends TableImpl<GajiPotonganTkkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gaji_potongan_tkk</code>
     */
    public static final GajiPotonganTkk GAJI_POTONGAN_TKK = new GajiPotonganTkk();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GajiPotonganTkkRecord> getRecordType() {
        return GajiPotonganTkkRecord.class;
    }

    /**
     * The column <code>gaji_potongan_tkk.id</code>.
     */
    public final TableField<GajiPotonganTkkRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>gaji_potongan_tkk.changed_status</code>.
     */
    public final TableField<GajiPotonganTkkRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.nominal</code>.
     */
    public final TableField<GajiPotonganTkkRecord, Double> NOMINAL = createField(DSL.name("nominal"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.status_pegawai</code>.
     */
    public final TableField<GajiPotonganTkkRecord, Byte> STATUS_PEGAWAI = createField(DSL.name("status_pegawai"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.golongan_id</code>.
     */
    public final TableField<GajiPotonganTkkRecord, Long> GOLONGAN_ID = createField(DSL.name("golongan_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.level_id</code>.
     */
    public final TableField<GajiPotonganTkkRecord, Long> LEVEL_ID = createField(DSL.name("level_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.created_at</code>.
     */
    public final TableField<GajiPotonganTkkRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.created_by</code>.
     */
    public final TableField<GajiPotonganTkkRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.is_deleted</code>.
     */
    public final TableField<GajiPotonganTkkRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.updated_at</code>.
     */
    public final TableField<GajiPotonganTkkRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.updated_by</code>.
     */
    public final TableField<GajiPotonganTkkRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gaji_potongan_tkk.version</code>.
     */
    public final TableField<GajiPotonganTkkRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private GajiPotonganTkk(Name alias, Table<GajiPotonganTkkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GajiPotonganTkk(Name alias, Table<GajiPotonganTkkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>gaji_potongan_tkk</code> table reference
     */
    public GajiPotonganTkk(String alias) {
        this(DSL.name(alias), GAJI_POTONGAN_TKK);
    }

    /**
     * Create an aliased <code>gaji_potongan_tkk</code> table reference
     */
    public GajiPotonganTkk(Name alias) {
        this(alias, GAJI_POTONGAN_TKK);
    }

    /**
     * Create a <code>gaji_potongan_tkk</code> table reference
     */
    public GajiPotonganTkk() {
        this(DSL.name("gaji_potongan_tkk"), null);
    }

    public <O extends Record> GajiPotonganTkk(Table<O> path, ForeignKey<O, GajiPotonganTkkRecord> childPath, InverseForeignKey<O, GajiPotonganTkkRecord> parentPath) {
        super(path, childPath, parentPath, GAJI_POTONGAN_TKK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GajiPotonganTkkPath extends GajiPotonganTkk implements Path<GajiPotonganTkkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GajiPotonganTkkPath(Table<O> path, ForeignKey<O, GajiPotonganTkkRecord> childPath, InverseForeignKey<O, GajiPotonganTkkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GajiPotonganTkkPath(Name alias, Table<GajiPotonganTkkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GajiPotonganTkkPath as(String alias) {
            return new GajiPotonganTkkPath(DSL.name(alias), this);
        }

        @Override
        public GajiPotonganTkkPath as(Name alias) {
            return new GajiPotonganTkkPath(alias, this);
        }

        @Override
        public GajiPotonganTkkPath as(Table<?> alias) {
            return new GajiPotonganTkkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GAJI_POTONGAN_TKK_IDX_GJ_PTG_TKK_GLG_ID, Indexes.GAJI_POTONGAN_TKK_IDX_GJ_PTG_TKK_IS_DELETED, Indexes.GAJI_POTONGAN_TKK_IDX_GJ_PTG_TKK_LVL_ID);
    }

    @Override
    public Identity<GajiPotonganTkkRecord, Long> getIdentity() {
        return (Identity<GajiPotonganTkkRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GajiPotonganTkkRecord> getPrimaryKey() {
        return Keys.KEY_GAJI_POTONGAN_TKK_PRIMARY;
    }

    @Override
    public List<ForeignKey<GajiPotonganTkkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_GJ_PTG_TKK_GLG_GLG_ID, Keys.FK_GJ_PTG_TKK_LVL_LVL_ID);
    }

    private transient GolonganPath _golongan;

    /**
     * Get the implicit join path to the <code>golongan</code> table.
     */
    public GolonganPath golongan() {
        if (_golongan == null)
            _golongan = new GolonganPath(this, Keys.FK_GJ_PTG_TKK_GLG_GLG_ID, null);

        return _golongan;
    }

    private transient LevelPath _level;

    /**
     * Get the implicit join path to the <code>level</code> table.
     */
    public LevelPath level() {
        if (_level == null)
            _level = new LevelPath(this, Keys.FK_GJ_PTG_TKK_LVL_LVL_ID, null);

        return _level;
    }

    @Override
    public GajiPotonganTkk as(String alias) {
        return new GajiPotonganTkk(DSL.name(alias), this);
    }

    @Override
    public GajiPotonganTkk as(Name alias) {
        return new GajiPotonganTkk(alias, this);
    }

    @Override
    public GajiPotonganTkk as(Table<?> alias) {
        return new GajiPotonganTkk(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPotonganTkk rename(String name) {
        return new GajiPotonganTkk(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPotonganTkk rename(Name name) {
        return new GajiPotonganTkk(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPotonganTkk rename(Table<?> name) {
        return new GajiPotonganTkk(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPotonganTkk where(Condition condition) {
        return new GajiPotonganTkk(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPotonganTkk where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPotonganTkk where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPotonganTkk where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPotonganTkk where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPotonganTkk where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPotonganTkk where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPotonganTkk where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPotonganTkk whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPotonganTkk whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
