/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.enums.GajiKomponenJenisGaji;
import id.perumdamts.kepegawaian.jooq.tables.GajiProfil.GajiProfilPath;
import id.perumdamts.kepegawaian.jooq.tables.records.GajiKomponenRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GajiKomponen extends TableImpl<GajiKomponenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.gaji_komponen</code>
     */
    public static final GajiKomponen GAJI_KOMPONEN = new GajiKomponen();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GajiKomponenRecord> getRecordType() {
        return GajiKomponenRecord.class;
    }

    /**
     * The column <code>kepegawaian.gaji_komponen.id</code>.
     */
    public final TableField<GajiKomponenRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.changed_status</code>.
     */
    public final TableField<GajiKomponenRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.created_at</code>.
     */
    public final TableField<GajiKomponenRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.created_by</code>.
     */
    public final TableField<GajiKomponenRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.is_deleted</code>.
     */
    public final TableField<GajiKomponenRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.updated_at</code>.
     */
    public final TableField<GajiKomponenRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.updated_by</code>.
     */
    public final TableField<GajiKomponenRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.version</code>.
     */
    public final TableField<GajiKomponenRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.formula</code>.
     */
    public final TableField<GajiKomponenRecord, String> FORMULA = createField(DSL.name("formula"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.is_reference</code>.
     */
    public final TableField<GajiKomponenRecord, Boolean> IS_REFERENCE = createField(DSL.name("is_reference"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.jenis_gaji</code>.
     */
    public final TableField<GajiKomponenRecord, GajiKomponenJenisGaji> JENIS_GAJI = createField(DSL.name("jenis_gaji"), SQLDataType.VARCHAR(9).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)).asEnumDataType(GajiKomponenJenisGaji.class), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.kode</code>.
     */
    public final TableField<GajiKomponenRecord, String> KODE = createField(DSL.name("kode"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.nama</code>.
     */
    public final TableField<GajiKomponenRecord, String> NAMA = createField(DSL.name("nama"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.nilai</code>.
     */
    public final TableField<GajiKomponenRecord, Double> NILAI = createField(DSL.name("nilai"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.urut</code>.
     */
    public final TableField<GajiKomponenRecord, Integer> URUT = createField(DSL.name("urut"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kepegawaian.gaji_komponen.profil_gaji_id</code>.
     */
    public final TableField<GajiKomponenRecord, Long> PROFIL_GAJI_ID = createField(DSL.name("profil_gaji_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    private GajiKomponen(Name alias, Table<GajiKomponenRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GajiKomponen(Name alias, Table<GajiKomponenRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.gaji_komponen</code> table reference
     */
    public GajiKomponen(String alias) {
        this(DSL.name(alias), GAJI_KOMPONEN);
    }

    /**
     * Create an aliased <code>kepegawaian.gaji_komponen</code> table reference
     */
    public GajiKomponen(Name alias) {
        this(alias, GAJI_KOMPONEN);
    }

    /**
     * Create a <code>kepegawaian.gaji_komponen</code> table reference
     */
    public GajiKomponen() {
        this(DSL.name("gaji_komponen"), null);
    }

    public <O extends Record> GajiKomponen(Table<O> path, ForeignKey<O, GajiKomponenRecord> childPath, InverseForeignKey<O, GajiKomponenRecord> parentPath) {
        super(path, childPath, parentPath, GAJI_KOMPONEN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GajiKomponenPath extends GajiKomponen implements Path<GajiKomponenRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GajiKomponenPath(Table<O> path, ForeignKey<O, GajiKomponenRecord> childPath, InverseForeignKey<O, GajiKomponenRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GajiKomponenPath(Name alias, Table<GajiKomponenRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GajiKomponenPath as(String alias) {
            return new GajiKomponenPath(DSL.name(alias), this);
        }

        @Override
        public GajiKomponenPath as(Name alias) {
            return new GajiKomponenPath(alias, this);
        }

        @Override
        public GajiKomponenPath as(Table<?> alias) {
            return new GajiKomponenPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GAJI_KOMPONEN_IDXL2PIC9X86XB26OPXH6GCGFK3);
    }

    @Override
    public Identity<GajiKomponenRecord, Long> getIdentity() {
        return (Identity<GajiKomponenRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GajiKomponenRecord> getPrimaryKey() {
        return Keys.KEY_GAJI_KOMPONEN_PRIMARY;
    }

    @Override
    public List<ForeignKey<GajiKomponenRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK5PHAMFQ1ATJUDIIYQY0X2IL98);
    }

    private transient GajiProfilPath _gajiProfil;

    /**
     * Get the implicit join path to the <code>kepegawaian.gaji_profil</code>
     * table.
     */
    public GajiProfilPath gajiProfil() {
        if (_gajiProfil == null)
            _gajiProfil = new GajiProfilPath(this, Keys.FK5PHAMFQ1ATJUDIIYQY0X2IL98, null);

        return _gajiProfil;
    }

    @Override
    public GajiKomponen as(String alias) {
        return new GajiKomponen(DSL.name(alias), this);
    }

    @Override
    public GajiKomponen as(Name alias) {
        return new GajiKomponen(alias, this);
    }

    @Override
    public GajiKomponen as(Table<?> alias) {
        return new GajiKomponen(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiKomponen rename(String name) {
        return new GajiKomponen(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiKomponen rename(Name name) {
        return new GajiKomponen(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiKomponen rename(Table<?> name) {
        return new GajiKomponen(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiKomponen where(Condition condition) {
        return new GajiKomponen(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiKomponen where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiKomponen where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiKomponen where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiKomponen where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiKomponen where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiKomponen where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiKomponen where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiKomponen whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiKomponen whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
