/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Revinfo.RevinfoPath;
import id.perumdamts.kepegawaian.jooq.tables.records.GajiPendapatanNonPajakAudRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GajiPendapatanNonPajakAud extends TableImpl<GajiPendapatanNonPajakAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud</code>
     */
    public static final GajiPendapatanNonPajakAud GAJI_PENDAPATAN_NON_PAJAK_AUD = new GajiPendapatanNonPajakAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GajiPendapatanNonPajakAudRecord> getRecordType() {
        return GajiPendapatanNonPajakAudRecord.class;
    }

    /**
     * The column <code>kepegawaian.gaji_pendapatan_non_pajak_aud.id</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.gaji_pendapatan_non_pajak_aud.rev</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud.revtype</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, Byte> REVTYPE = createField(DSL.name("revtype"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud.changed_status</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud.created_at</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud.created_by</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud.is_deleted</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud.updated_at</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud.updated_by</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_pendapatan_non_pajak_aud.kode</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, String> KODE = createField(DSL.name("kode"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>kepegawaian.gaji_pendapatan_non_pajak_aud.nominal</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, Double> NOMINAL = createField(DSL.name("nominal"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>kepegawaian.gaji_pendapatan_non_pajak_aud.notes</code>.
     */
    public final TableField<GajiPendapatanNonPajakAudRecord, String> NOTES = createField(DSL.name("notes"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private GajiPendapatanNonPajakAud(Name alias, Table<GajiPendapatanNonPajakAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GajiPendapatanNonPajakAud(Name alias, Table<GajiPendapatanNonPajakAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.gaji_pendapatan_non_pajak_aud</code>
     * table reference
     */
    public GajiPendapatanNonPajakAud(String alias) {
        this(DSL.name(alias), GAJI_PENDAPATAN_NON_PAJAK_AUD);
    }

    /**
     * Create an aliased <code>kepegawaian.gaji_pendapatan_non_pajak_aud</code>
     * table reference
     */
    public GajiPendapatanNonPajakAud(Name alias) {
        this(alias, GAJI_PENDAPATAN_NON_PAJAK_AUD);
    }

    /**
     * Create a <code>kepegawaian.gaji_pendapatan_non_pajak_aud</code> table
     * reference
     */
    public GajiPendapatanNonPajakAud() {
        this(DSL.name("gaji_pendapatan_non_pajak_aud"), null);
    }

    public <O extends Record> GajiPendapatanNonPajakAud(Table<O> path, ForeignKey<O, GajiPendapatanNonPajakAudRecord> childPath, InverseForeignKey<O, GajiPendapatanNonPajakAudRecord> parentPath) {
        super(path, childPath, parentPath, GAJI_PENDAPATAN_NON_PAJAK_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GajiPendapatanNonPajakAudPath extends GajiPendapatanNonPajakAud implements Path<GajiPendapatanNonPajakAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GajiPendapatanNonPajakAudPath(Table<O> path, ForeignKey<O, GajiPendapatanNonPajakAudRecord> childPath, InverseForeignKey<O, GajiPendapatanNonPajakAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GajiPendapatanNonPajakAudPath(Name alias, Table<GajiPendapatanNonPajakAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GajiPendapatanNonPajakAudPath as(String alias) {
            return new GajiPendapatanNonPajakAudPath(DSL.name(alias), this);
        }

        @Override
        public GajiPendapatanNonPajakAudPath as(Name alias) {
            return new GajiPendapatanNonPajakAudPath(alias, this);
        }

        @Override
        public GajiPendapatanNonPajakAudPath as(Table<?> alias) {
            return new GajiPendapatanNonPajakAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<GajiPendapatanNonPajakAudRecord> getPrimaryKey() {
        return Keys.KEY_GAJI_PENDAPATAN_NON_PAJAK_AUD_PRIMARY;
    }

    @Override
    public List<ForeignKey<GajiPendapatanNonPajakAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKNQHKW4CK5W0KBPL2KYJTL5NDK);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>kepegawaian.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.FKNQHKW4CK5W0KBPL2KYJTL5NDK, null);

        return _revinfo;
    }

    @Override
    public GajiPendapatanNonPajakAud as(String alias) {
        return new GajiPendapatanNonPajakAud(DSL.name(alias), this);
    }

    @Override
    public GajiPendapatanNonPajakAud as(Name alias) {
        return new GajiPendapatanNonPajakAud(alias, this);
    }

    @Override
    public GajiPendapatanNonPajakAud as(Table<?> alias) {
        return new GajiPendapatanNonPajakAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPendapatanNonPajakAud rename(String name) {
        return new GajiPendapatanNonPajakAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPendapatanNonPajakAud rename(Name name) {
        return new GajiPendapatanNonPajakAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPendapatanNonPajakAud rename(Table<?> name) {
        return new GajiPendapatanNonPajakAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPendapatanNonPajakAud where(Condition condition) {
        return new GajiPendapatanNonPajakAud(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPendapatanNonPajakAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPendapatanNonPajakAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPendapatanNonPajakAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPendapatanNonPajakAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPendapatanNonPajakAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPendapatanNonPajakAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPendapatanNonPajakAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPendapatanNonPajakAud whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPendapatanNonPajakAud whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
