/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Revinfo.RevinfoPath;
import id.perumdamts.kepegawaian.jooq.tables.records.GajiPhdpAudRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GajiPhdpAud extends TableImpl<GajiPhdpAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.gaji_phdp_aud</code>
     */
    public static final GajiPhdpAud GAJI_PHDP_AUD = new GajiPhdpAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GajiPhdpAudRecord> getRecordType() {
        return GajiPhdpAudRecord.class;
    }

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.id</code>.
     */
    public final TableField<GajiPhdpAudRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.rev</code>.
     */
    public final TableField<GajiPhdpAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.revtype</code>.
     */
    public final TableField<GajiPhdpAudRecord, Byte> REVTYPE = createField(DSL.name("revtype"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.changed_status</code>.
     */
    public final TableField<GajiPhdpAudRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.created_at</code>.
     */
    public final TableField<GajiPhdpAudRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.created_by</code>.
     */
    public final TableField<GajiPhdpAudRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.is_deleted</code>.
     */
    public final TableField<GajiPhdpAudRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.updated_at</code>.
     */
    public final TableField<GajiPhdpAudRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.updated_by</code>.
     */
    public final TableField<GajiPhdpAudRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.formula</code>.
     */
    public final TableField<GajiPhdpAudRecord, String> FORMULA = createField(DSL.name("formula"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.kondisi</code>.
     */
    public final TableField<GajiPhdpAudRecord, String> KONDISI = createField(DSL.name("kondisi"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.gaji_phdp_aud.urut</code>.
     */
    public final TableField<GajiPhdpAudRecord, Integer> URUT = createField(DSL.name("urut"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private GajiPhdpAud(Name alias, Table<GajiPhdpAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GajiPhdpAud(Name alias, Table<GajiPhdpAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.gaji_phdp_aud</code> table reference
     */
    public GajiPhdpAud(String alias) {
        this(DSL.name(alias), GAJI_PHDP_AUD);
    }

    /**
     * Create an aliased <code>kepegawaian.gaji_phdp_aud</code> table reference
     */
    public GajiPhdpAud(Name alias) {
        this(alias, GAJI_PHDP_AUD);
    }

    /**
     * Create a <code>kepegawaian.gaji_phdp_aud</code> table reference
     */
    public GajiPhdpAud() {
        this(DSL.name("gaji_phdp_aud"), null);
    }

    public <O extends Record> GajiPhdpAud(Table<O> path, ForeignKey<O, GajiPhdpAudRecord> childPath, InverseForeignKey<O, GajiPhdpAudRecord> parentPath) {
        super(path, childPath, parentPath, GAJI_PHDP_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GajiPhdpAudPath extends GajiPhdpAud implements Path<GajiPhdpAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GajiPhdpAudPath(Table<O> path, ForeignKey<O, GajiPhdpAudRecord> childPath, InverseForeignKey<O, GajiPhdpAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GajiPhdpAudPath(Name alias, Table<GajiPhdpAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GajiPhdpAudPath as(String alias) {
            return new GajiPhdpAudPath(DSL.name(alias), this);
        }

        @Override
        public GajiPhdpAudPath as(Name alias) {
            return new GajiPhdpAudPath(alias, this);
        }

        @Override
        public GajiPhdpAudPath as(Table<?> alias) {
            return new GajiPhdpAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<GajiPhdpAudRecord> getPrimaryKey() {
        return Keys.KEY_GAJI_PHDP_AUD_PRIMARY;
    }

    @Override
    public List<ForeignKey<GajiPhdpAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKGLJI8PRKRK7SSDLR0T5WH6R3Q);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>kepegawaian.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.FKGLJI8PRKRK7SSDLR0T5WH6R3Q, null);

        return _revinfo;
    }

    @Override
    public GajiPhdpAud as(String alias) {
        return new GajiPhdpAud(DSL.name(alias), this);
    }

    @Override
    public GajiPhdpAud as(Name alias) {
        return new GajiPhdpAud(alias, this);
    }

    @Override
    public GajiPhdpAud as(Table<?> alias) {
        return new GajiPhdpAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPhdpAud rename(String name) {
        return new GajiPhdpAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPhdpAud rename(Name name) {
        return new GajiPhdpAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GajiPhdpAud rename(Table<?> name) {
        return new GajiPhdpAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPhdpAud where(Condition condition) {
        return new GajiPhdpAud(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPhdpAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPhdpAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPhdpAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPhdpAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPhdpAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPhdpAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GajiPhdpAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPhdpAud whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GajiPhdpAud whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
