/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Level.LevelPath;
import id.perumdamts.kepegawaian.jooq.tables.Profesi.ProfesiPath;
import id.perumdamts.kepegawaian.jooq.tables.records.GradeRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Grade extends TableImpl<GradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.grade</code>
     */
    public static final Grade GRADE = new Grade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GradeRecord> getRecordType() {
        return GradeRecord.class;
    }

    /**
     * The column <code>kepegawaian.grade.id</code>.
     */
    public final TableField<GradeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>kepegawaian.grade.level_id</code>.
     */
    public final TableField<GradeRecord, Long> LEVEL_ID = createField(DSL.name("level_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.grade.grade</code>.
     */
    public final TableField<GradeRecord, Integer> GRADE_ = createField(DSL.name("grade"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.grade.tukin</code>.
     */
    public final TableField<GradeRecord, Double> TUKIN = createField(DSL.name("tukin"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>kepegawaian.grade.is_deleted</code>.
     */
    public final TableField<GradeRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BIT.nullable(false).defaultValue(DSL.field(DSL.raw("b'0'"), SQLDataType.BIT)), this, "");

    /**
     * The column <code>kepegawaian.grade.created_at</code>.
     */
    public final TableField<GradeRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp(6)"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.grade.created_by</code>.
     */
    public final TableField<GradeRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.grade.updated_at</code>.
     */
    public final TableField<GradeRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.grade.updated_by</code>.
     */
    public final TableField<GradeRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Grade(Name alias, Table<GradeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Grade(Name alias, Table<GradeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.grade</code> table reference
     */
    public Grade(String alias) {
        this(DSL.name(alias), GRADE);
    }

    /**
     * Create an aliased <code>kepegawaian.grade</code> table reference
     */
    public Grade(Name alias) {
        this(alias, GRADE);
    }

    /**
     * Create a <code>kepegawaian.grade</code> table reference
     */
    public Grade() {
        this(DSL.name("grade"), null);
    }

    public <O extends Record> Grade(Table<O> path, ForeignKey<O, GradeRecord> childPath, InverseForeignKey<O, GradeRecord> parentPath) {
        super(path, childPath, parentPath, GRADE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GradePath extends Grade implements Path<GradeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GradePath(Table<O> path, ForeignKey<O, GradeRecord> childPath, InverseForeignKey<O, GradeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GradePath(Name alias, Table<GradeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GradePath as(String alias) {
            return new GradePath(DSL.name(alias), this);
        }

        @Override
        public GradePath as(Name alias) {
            return new GradePath(alias, this);
        }

        @Override
        public GradePath as(Table<?> alias) {
            return new GradePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GRADE_IDX_GRADE_GRADE, Indexes.GRADE_IDX_GRADE_IS_DELETED, Indexes.GRADE_IDX_GRADE_LEVEL);
    }

    @Override
    public Identity<GradeRecord, Long> getIdentity() {
        return (Identity<GradeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GradeRecord> getPrimaryKey() {
        return Keys.KEY_GRADE_PRIMARY;
    }

    @Override
    public List<ForeignKey<GradeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_GRADE_LEVEL);
    }

    private transient LevelPath _level;

    /**
     * Get the implicit join path to the <code>kepegawaian.level</code> table.
     */
    public LevelPath level() {
        if (_level == null)
            _level = new LevelPath(this, Keys.FK_GRADE_LEVEL, null);

        return _level;
    }

    private transient ProfesiPath _profesi;

    /**
     * Get the implicit to-many join path to the
     * <code>kepegawaian.profesi</code> table
     */
    public ProfesiPath profesi() {
        if (_profesi == null)
            _profesi = new ProfesiPath(this, null, Keys.FK_PROFESI_GRADE.getInverseKey());

        return _profesi;
    }

    @Override
    public Grade as(String alias) {
        return new Grade(DSL.name(alias), this);
    }

    @Override
    public Grade as(Name alias) {
        return new Grade(alias, this);
    }

    @Override
    public Grade as(Table<?> alias) {
        return new Grade(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Grade rename(String name) {
        return new Grade(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Grade rename(Name name) {
        return new Grade(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Grade rename(Table<?> name) {
        return new Grade(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Grade where(Condition condition) {
        return new Grade(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Grade where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Grade where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Grade where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Grade where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Grade where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Grade where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Grade where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Grade whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Grade whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
