/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Revinfo.RevinfoPath;
import id.perumdamts.kepegawaian.jooq.tables.records.JenisKitasAudRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JenisKitasAud extends TableImpl<JenisKitasAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.jenis_kitas_aud</code>
     */
    public static final JenisKitasAud JENIS_KITAS_AUD = new JenisKitasAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JenisKitasAudRecord> getRecordType() {
        return JenisKitasAudRecord.class;
    }

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.id</code>.
     */
    public final TableField<JenisKitasAudRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.rev</code>.
     */
    public final TableField<JenisKitasAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.revtype</code>.
     */
    public final TableField<JenisKitasAudRecord, Byte> REVTYPE = createField(DSL.name("revtype"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.changed_status</code>.
     */
    public final TableField<JenisKitasAudRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.created_at</code>.
     */
    public final TableField<JenisKitasAudRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.created_by</code>.
     */
    public final TableField<JenisKitasAudRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.is_deleted</code>.
     */
    public final TableField<JenisKitasAudRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.updated_at</code>.
     */
    public final TableField<JenisKitasAudRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.updated_by</code>.
     */
    public final TableField<JenisKitasAudRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.jenis_kitas_aud.nama</code>.
     */
    public final TableField<JenisKitasAudRecord, String> NAMA = createField(DSL.name("nama"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private JenisKitasAud(Name alias, Table<JenisKitasAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JenisKitasAud(Name alias, Table<JenisKitasAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.jenis_kitas_aud</code> table
     * reference
     */
    public JenisKitasAud(String alias) {
        this(DSL.name(alias), JENIS_KITAS_AUD);
    }

    /**
     * Create an aliased <code>kepegawaian.jenis_kitas_aud</code> table
     * reference
     */
    public JenisKitasAud(Name alias) {
        this(alias, JENIS_KITAS_AUD);
    }

    /**
     * Create a <code>kepegawaian.jenis_kitas_aud</code> table reference
     */
    public JenisKitasAud() {
        this(DSL.name("jenis_kitas_aud"), null);
    }

    public <O extends Record> JenisKitasAud(Table<O> path, ForeignKey<O, JenisKitasAudRecord> childPath, InverseForeignKey<O, JenisKitasAudRecord> parentPath) {
        super(path, childPath, parentPath, JENIS_KITAS_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JenisKitasAudPath extends JenisKitasAud implements Path<JenisKitasAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JenisKitasAudPath(Table<O> path, ForeignKey<O, JenisKitasAudRecord> childPath, InverseForeignKey<O, JenisKitasAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JenisKitasAudPath(Name alias, Table<JenisKitasAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JenisKitasAudPath as(String alias) {
            return new JenisKitasAudPath(DSL.name(alias), this);
        }

        @Override
        public JenisKitasAudPath as(Name alias) {
            return new JenisKitasAudPath(alias, this);
        }

        @Override
        public JenisKitasAudPath as(Table<?> alias) {
            return new JenisKitasAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<JenisKitasAudRecord> getPrimaryKey() {
        return Keys.KEY_JENIS_KITAS_AUD_PRIMARY;
    }

    @Override
    public List<ForeignKey<JenisKitasAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK3Q5TFXOBMPFWA7U538CSW362R);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>kepegawaian.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.FK3Q5TFXOBMPFWA7U538CSW362R, null);

        return _revinfo;
    }

    @Override
    public JenisKitasAud as(String alias) {
        return new JenisKitasAud(DSL.name(alias), this);
    }

    @Override
    public JenisKitasAud as(Name alias) {
        return new JenisKitasAud(alias, this);
    }

    @Override
    public JenisKitasAud as(Table<?> alias) {
        return new JenisKitasAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JenisKitasAud rename(String name) {
        return new JenisKitasAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JenisKitasAud rename(Name name) {
        return new JenisKitasAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JenisKitasAud rename(Table<?> name) {
        return new JenisKitasAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JenisKitasAud where(Condition condition) {
        return new JenisKitasAud(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JenisKitasAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JenisKitasAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JenisKitasAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JenisKitasAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JenisKitasAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JenisKitasAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JenisKitasAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JenisKitasAud whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JenisKitasAud whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
