/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.DefaultSchema;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Revinfo.RevinfoPath;
import id.perumdamts.kepegawaian.jooq.tables.records.KeahlianAudRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KeahlianAud extends TableImpl<KeahlianAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>keahlian_aud</code>
     */
    public static final KeahlianAud KEAHLIAN_AUD = new KeahlianAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KeahlianAudRecord> getRecordType() {
        return KeahlianAudRecord.class;
    }

    /**
     * The column <code>keahlian_aud.id</code>.
     */
    public final TableField<KeahlianAudRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>keahlian_aud.rev</code>.
     */
    public final TableField<KeahlianAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>keahlian_aud.revtype</code>.
     */
    public final TableField<KeahlianAudRecord, Byte> REVTYPE = createField(DSL.name("revtype"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>keahlian_aud.changed_status</code>.
     */
    public final TableField<KeahlianAudRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>keahlian_aud.created_at</code>.
     */
    public final TableField<KeahlianAudRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>keahlian_aud.created_by</code>.
     */
    public final TableField<KeahlianAudRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian_aud.is_deleted</code>.
     */
    public final TableField<KeahlianAudRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>keahlian_aud.updated_at</code>.
     */
    public final TableField<KeahlianAudRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>keahlian_aud.updated_by</code>.
     */
    public final TableField<KeahlianAudRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian_aud.disetujui</code>.
     */
    public final TableField<KeahlianAudRecord, Boolean> DISETUJUI = createField(DSL.name("disetujui"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "");

    /**
     * The column <code>keahlian_aud.disetujui_oleh</code>.
     */
    public final TableField<KeahlianAudRecord, String> DISETUJUI_OLEH = createField(DSL.name("disetujui_oleh"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian_aud.institusi</code>.
     */
    public final TableField<KeahlianAudRecord, String> INSTITUSI = createField(DSL.name("institusi"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian_aud.kualifikasi</code>.
     */
    public final TableField<KeahlianAudRecord, Byte> KUALIFIKASI = createField(DSL.name("kualifikasi"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>keahlian_aud.masa_berlaku</code>.
     */
    public final TableField<KeahlianAudRecord, String> MASA_BERLAKU = createField(DSL.name("masa_berlaku"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian_aud.sertifikasi</code>.
     */
    public final TableField<KeahlianAudRecord, Boolean> SERTIFIKASI = createField(DSL.name("sertifikasi"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "");

    /**
     * The column <code>keahlian_aud.tahun</code>.
     */
    public final TableField<KeahlianAudRecord, Integer> TAHUN = createField(DSL.name("tahun"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>keahlian_aud.tanggal_disetujui</code>.
     */
    public final TableField<KeahlianAudRecord, LocalDateTime> TANGGAL_DISETUJUI = createField(DSL.name("tanggal_disetujui"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>keahlian_aud.tanggal_pengajuan</code>.
     */
    public final TableField<KeahlianAudRecord, LocalDateTime> TANGGAL_PENGAJUAN = createField(DSL.name("tanggal_pengajuan"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>keahlian_aud.biodata_id</code>.
     */
    public final TableField<KeahlianAudRecord, String> BIODATA_ID = createField(DSL.name("biodata_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian_aud.jenis_keahlian_id</code>.
     */
    public final TableField<KeahlianAudRecord, Long> JENIS_KEAHLIAN_ID = createField(DSL.name("jenis_keahlian_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    private KeahlianAud(Name alias, Table<KeahlianAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private KeahlianAud(Name alias, Table<KeahlianAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>keahlian_aud</code> table reference
     */
    public KeahlianAud(String alias) {
        this(DSL.name(alias), KEAHLIAN_AUD);
    }

    /**
     * Create an aliased <code>keahlian_aud</code> table reference
     */
    public KeahlianAud(Name alias) {
        this(alias, KEAHLIAN_AUD);
    }

    /**
     * Create a <code>keahlian_aud</code> table reference
     */
    public KeahlianAud() {
        this(DSL.name("keahlian_aud"), null);
    }

    public <O extends Record> KeahlianAud(Table<O> path, ForeignKey<O, KeahlianAudRecord> childPath, InverseForeignKey<O, KeahlianAudRecord> parentPath) {
        super(path, childPath, parentPath, KEAHLIAN_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class KeahlianAudPath extends KeahlianAud implements Path<KeahlianAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> KeahlianAudPath(Table<O> path, ForeignKey<O, KeahlianAudRecord> childPath, InverseForeignKey<O, KeahlianAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private KeahlianAudPath(Name alias, Table<KeahlianAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public KeahlianAudPath as(String alias) {
            return new KeahlianAudPath(DSL.name(alias), this);
        }

        @Override
        public KeahlianAudPath as(Name alias) {
            return new KeahlianAudPath(alias, this);
        }

        @Override
        public KeahlianAudPath as(Table<?> alias) {
            return new KeahlianAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<KeahlianAudRecord> getPrimaryKey() {
        return Keys.KEY_KEAHLIAN_AUD_PRIMARY;
    }

    @Override
    public List<ForeignKey<KeahlianAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_AHL_AUD_REV_REV);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.FK_AHL_AUD_REV_REV, null);

        return _revinfo;
    }

    @Override
    public KeahlianAud as(String alias) {
        return new KeahlianAud(DSL.name(alias), this);
    }

    @Override
    public KeahlianAud as(Name alias) {
        return new KeahlianAud(alias, this);
    }

    @Override
    public KeahlianAud as(Table<?> alias) {
        return new KeahlianAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public KeahlianAud rename(String name) {
        return new KeahlianAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public KeahlianAud rename(Name name) {
        return new KeahlianAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public KeahlianAud rename(Table<?> name) {
        return new KeahlianAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeahlianAud where(Condition condition) {
        return new KeahlianAud(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeahlianAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeahlianAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeahlianAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KeahlianAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KeahlianAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KeahlianAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KeahlianAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeahlianAud whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeahlianAud whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
