/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.DefaultSchema;
import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Biodata.BiodataPath;
import id.perumdamts.kepegawaian.jooq.tables.JenisKeahlian.JenisKeahlianPath;
import id.perumdamts.kepegawaian.jooq.tables.records.KeahlianRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keahlian extends TableImpl<KeahlianRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>keahlian</code>
     */
    public static final Keahlian KEAHLIAN = new Keahlian();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KeahlianRecord> getRecordType() {
        return KeahlianRecord.class;
    }

    /**
     * The column <code>keahlian.id</code>.
     */
    public final TableField<KeahlianRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>keahlian.changed_status</code>.
     */
    public final TableField<KeahlianRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>keahlian.disetujui</code>.
     */
    public final TableField<KeahlianRecord, Boolean> DISETUJUI = createField(DSL.name("disetujui"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "");

    /**
     * The column <code>keahlian.disetujui_oleh</code>.
     */
    public final TableField<KeahlianRecord, String> DISETUJUI_OLEH = createField(DSL.name("disetujui_oleh"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian.institusi</code>.
     */
    public final TableField<KeahlianRecord, String> INSTITUSI = createField(DSL.name("institusi"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian.kualifikasi</code>.
     */
    public final TableField<KeahlianRecord, Byte> KUALIFIKASI = createField(DSL.name("kualifikasi"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>keahlian.masa_berlaku</code>.
     */
    public final TableField<KeahlianRecord, String> MASA_BERLAKU = createField(DSL.name("masa_berlaku"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian.sertifikasi</code>.
     */
    public final TableField<KeahlianRecord, Boolean> SERTIFIKASI = createField(DSL.name("sertifikasi"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "");

    /**
     * The column <code>keahlian.tahun</code>.
     */
    public final TableField<KeahlianRecord, Integer> TAHUN = createField(DSL.name("tahun"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>keahlian.tanggal_disetujui</code>.
     */
    public final TableField<KeahlianRecord, LocalDateTime> TANGGAL_DISETUJUI = createField(DSL.name("tanggal_disetujui"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>keahlian.tanggal_pengajuan</code>.
     */
    public final TableField<KeahlianRecord, LocalDateTime> TANGGAL_PENGAJUAN = createField(DSL.name("tanggal_pengajuan"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>keahlian.biodata_id</code>.
     */
    public final TableField<KeahlianRecord, String> BIODATA_ID = createField(DSL.name("biodata_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian.jenis_keahlian_id</code>.
     */
    public final TableField<KeahlianRecord, Long> JENIS_KEAHLIAN_ID = createField(DSL.name("jenis_keahlian_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>keahlian.created_at</code>.
     */
    public final TableField<KeahlianRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>keahlian.created_by</code>.
     */
    public final TableField<KeahlianRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian.is_deleted</code>.
     */
    public final TableField<KeahlianRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>keahlian.updated_at</code>.
     */
    public final TableField<KeahlianRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>keahlian.updated_by</code>.
     */
    public final TableField<KeahlianRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>keahlian.version</code>.
     */
    public final TableField<KeahlianRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private Keahlian(Name alias, Table<KeahlianRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Keahlian(Name alias, Table<KeahlianRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>keahlian</code> table reference
     */
    public Keahlian(String alias) {
        this(DSL.name(alias), KEAHLIAN);
    }

    /**
     * Create an aliased <code>keahlian</code> table reference
     */
    public Keahlian(Name alias) {
        this(alias, KEAHLIAN);
    }

    /**
     * Create a <code>keahlian</code> table reference
     */
    public Keahlian() {
        this(DSL.name("keahlian"), null);
    }

    public <O extends Record> Keahlian(Table<O> path, ForeignKey<O, KeahlianRecord> childPath, InverseForeignKey<O, KeahlianRecord> parentPath) {
        super(path, childPath, parentPath, KEAHLIAN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class KeahlianPath extends Keahlian implements Path<KeahlianRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> KeahlianPath(Table<O> path, ForeignKey<O, KeahlianRecord> childPath, InverseForeignKey<O, KeahlianRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private KeahlianPath(Name alias, Table<KeahlianRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public KeahlianPath as(String alias) {
            return new KeahlianPath(DSL.name(alias), this);
        }

        @Override
        public KeahlianPath as(Name alias) {
            return new KeahlianPath(alias, this);
        }

        @Override
        public KeahlianPath as(Table<?> alias) {
            return new KeahlianPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.KEAHLIAN_IDX_AHL_BIO_ID, Indexes.KEAHLIAN_IDX_AHL_DISETUJUI, Indexes.KEAHLIAN_IDX_AHL_IS_DELETED, Indexes.KEAHLIAN_IDX_AHL_JNS_AHL_ID);
    }

    @Override
    public Identity<KeahlianRecord, Long> getIdentity() {
        return (Identity<KeahlianRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<KeahlianRecord> getPrimaryKey() {
        return Keys.KEY_KEAHLIAN_PRIMARY;
    }

    @Override
    public List<ForeignKey<KeahlianRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_AHL_BIO_BIO_ID, Keys.FK_AHL_JNS_AHL_JNS_AHL_ID);
    }

    private transient BiodataPath _biodata;

    /**
     * Get the implicit join path to the <code>biodata</code> table.
     */
    public BiodataPath biodata() {
        if (_biodata == null)
            _biodata = new BiodataPath(this, Keys.FK_AHL_BIO_BIO_ID, null);

        return _biodata;
    }

    private transient JenisKeahlianPath _jenisKeahlian;

    /**
     * Get the implicit join path to the <code>jenis_keahlian</code> table.
     */
    public JenisKeahlianPath jenisKeahlian() {
        if (_jenisKeahlian == null)
            _jenisKeahlian = new JenisKeahlianPath(this, Keys.FK_AHL_JNS_AHL_JNS_AHL_ID, null);

        return _jenisKeahlian;
    }

    @Override
    public Keahlian as(String alias) {
        return new Keahlian(DSL.name(alias), this);
    }

    @Override
    public Keahlian as(Name alias) {
        return new Keahlian(alias, this);
    }

    @Override
    public Keahlian as(Table<?> alias) {
        return new Keahlian(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Keahlian rename(String name) {
        return new Keahlian(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Keahlian rename(Name name) {
        return new Keahlian(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Keahlian rename(Table<?> name) {
        return new Keahlian(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Keahlian where(Condition condition) {
        return new Keahlian(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Keahlian where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Keahlian where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Keahlian where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Keahlian where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Keahlian where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Keahlian where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Keahlian where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Keahlian whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Keahlian whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
