/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Jabatan.JabatanPath;
import id.perumdamts.kepegawaian.jooq.tables.Organisasi.OrganisasiPath;
import id.perumdamts.kepegawaian.jooq.tables.Profesi.ProfesiPath;
import id.perumdamts.kepegawaian.jooq.tables.records.OrganisasiRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Organisasi extends TableImpl<OrganisasiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.organisasi</code>
     */
    public static final Organisasi ORGANISASI = new Organisasi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganisasiRecord> getRecordType() {
        return OrganisasiRecord.class;
    }

    /**
     * The column <code>kepegawaian.organisasi.id</code>.
     */
    public final TableField<OrganisasiRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>kepegawaian.organisasi.kode</code>.
     */
    public final TableField<OrganisasiRecord, String> KODE = createField(DSL.name("kode"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>kepegawaian.organisasi.parent_id</code>.
     */
    public final TableField<OrganisasiRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.organisasi.level_org</code>.
     */
    public final TableField<OrganisasiRecord, Integer> LEVEL_ORG = createField(DSL.name("level_org"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kepegawaian.organisasi.nama</code>.
     */
    public final TableField<OrganisasiRecord, String> NAMA = createField(DSL.name("nama"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>kepegawaian.organisasi.short_name</code>.
     */
    public final TableField<OrganisasiRecord, String> SHORT_NAME = createField(DSL.name("short_name"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.organisasi.category</code>.
     */
    public final TableField<OrganisasiRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.organisasi.is_deleted</code>.
     */
    public final TableField<OrganisasiRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BIT.nullable(false).defaultValue(DSL.field(DSL.raw("b'0'"), SQLDataType.BIT)), this, "");

    /**
     * The column <code>kepegawaian.organisasi.created_at</code>.
     */
    public final TableField<OrganisasiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp(6)"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.organisasi.created_by</code>.
     */
    public final TableField<OrganisasiRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.organisasi.updated_at</code>.
     */
    public final TableField<OrganisasiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.organisasi.updated_by</code>.
     */
    public final TableField<OrganisasiRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Organisasi(Name alias, Table<OrganisasiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Organisasi(Name alias, Table<OrganisasiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.organisasi</code> table reference
     */
    public Organisasi(String alias) {
        this(DSL.name(alias), ORGANISASI);
    }

    /**
     * Create an aliased <code>kepegawaian.organisasi</code> table reference
     */
    public Organisasi(Name alias) {
        this(alias, ORGANISASI);
    }

    /**
     * Create a <code>kepegawaian.organisasi</code> table reference
     */
    public Organisasi() {
        this(DSL.name("organisasi"), null);
    }

    public <O extends Record> Organisasi(Table<O> path, ForeignKey<O, OrganisasiRecord> childPath, InverseForeignKey<O, OrganisasiRecord> parentPath) {
        super(path, childPath, parentPath, ORGANISASI);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrganisasiPath extends Organisasi implements Path<OrganisasiRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrganisasiPath(Table<O> path, ForeignKey<O, OrganisasiRecord> childPath, InverseForeignKey<O, OrganisasiRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrganisasiPath(Name alias, Table<OrganisasiRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrganisasiPath as(String alias) {
            return new OrganisasiPath(DSL.name(alias), this);
        }

        @Override
        public OrganisasiPath as(Name alias) {
            return new OrganisasiPath(alias, this);
        }

        @Override
        public OrganisasiPath as(Table<?> alias) {
            return new OrganisasiPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ORGANISASI_IDX_ORGANISASI_IS_DELETED, Indexes.ORGANISASI_IDX_ORGANISASI_KODE, Indexes.ORGANISASI_IDX_ORGANISASI_LEVEL_ORG, Indexes.ORGANISASI_IDX_ORGANISASI_NAMA, Indexes.ORGANISASI_IDX_ORGANISASI_PARENT);
    }

    @Override
    public Identity<OrganisasiRecord, Long> getIdentity() {
        return (Identity<OrganisasiRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrganisasiRecord> getPrimaryKey() {
        return Keys.KEY_ORGANISASI_PRIMARY;
    }

    @Override
    public List<ForeignKey<OrganisasiRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ORGANISASI_PARENT);
    }

    private transient OrganisasiPath _organisasi;

    /**
     * Get the implicit join path to the <code>kepegawaian.organisasi</code>
     * table.
     */
    public OrganisasiPath organisasi() {
        if (_organisasi == null)
            _organisasi = new OrganisasiPath(this, Keys.FK_ORGANISASI_PARENT, null);

        return _organisasi;
    }

    private transient JabatanPath _jabatan;

    /**
     * Get the implicit to-many join path to the
     * <code>kepegawaian.jabatan</code> table
     */
    public JabatanPath jabatan() {
        if (_jabatan == null)
            _jabatan = new JabatanPath(this, null, Keys.FK_JABATAN_ORGANISASI.getInverseKey());

        return _jabatan;
    }

    private transient ProfesiPath _profesi;

    /**
     * Get the implicit to-many join path to the
     * <code>kepegawaian.profesi</code> table
     */
    public ProfesiPath profesi() {
        if (_profesi == null)
            _profesi = new ProfesiPath(this, null, Keys.FK_PROFESI_ORGANISASI.getInverseKey());

        return _profesi;
    }

    @Override
    public Organisasi as(String alias) {
        return new Organisasi(DSL.name(alias), this);
    }

    @Override
    public Organisasi as(Name alias) {
        return new Organisasi(alias, this);
    }

    @Override
    public Organisasi as(Table<?> alias) {
        return new Organisasi(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisasi rename(String name) {
        return new Organisasi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisasi rename(Name name) {
        return new Organisasi(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organisasi rename(Table<?> name) {
        return new Organisasi(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisasi where(Condition condition) {
        return new Organisasi(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisasi where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisasi where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisasi where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisasi where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisasi where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisasi where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organisasi where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisasi whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organisasi whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
