/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.DefaultSchema;
import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Biodata.BiodataPath;
import id.perumdamts.kepegawaian.jooq.tables.CutiApproval.CutiApprovalPath;
import id.perumdamts.kepegawaian.jooq.tables.CutiKuota.CutiKuotaPath;
import id.perumdamts.kepegawaian.jooq.tables.CutiPegawai.CutiPegawaiPath;
import id.perumdamts.kepegawaian.jooq.tables.GajiPendapatanNonPajak.GajiPendapatanNonPajakPath;
import id.perumdamts.kepegawaian.jooq.tables.GajiProfil.GajiProfilPath;
import id.perumdamts.kepegawaian.jooq.tables.Golongan.GolonganPath;
import id.perumdamts.kepegawaian.jooq.tables.Grade.GradePath;
import id.perumdamts.kepegawaian.jooq.tables.Jabatan.JabatanPath;
import id.perumdamts.kepegawaian.jooq.tables.Organisasi.OrganisasiPath;
import id.perumdamts.kepegawaian.jooq.tables.Profesi.ProfesiPath;
import id.perumdamts.kepegawaian.jooq.tables.RiwayatCuti.RiwayatCutiPath;
import id.perumdamts.kepegawaian.jooq.tables.RiwayatKeluar.RiwayatKeluarPath;
import id.perumdamts.kepegawaian.jooq.tables.RiwayatKontrak.RiwayatKontrakPath;
import id.perumdamts.kepegawaian.jooq.tables.RiwayatMutasi.RiwayatMutasiPath;
import id.perumdamts.kepegawaian.jooq.tables.RiwayatSk.RiwayatSkPath;
import id.perumdamts.kepegawaian.jooq.tables.RiwayatSp.RiwayatSpPath;
import id.perumdamts.kepegawaian.jooq.tables.RiwayatTerminasi.RiwayatTerminasiPath;
import id.perumdamts.kepegawaian.jooq.tables.RumahDinas.RumahDinasPath;
import id.perumdamts.kepegawaian.jooq.tables.records.PegawaiRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Pegawai extends TableImpl<PegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pegawai</code>
     */
    public static final Pegawai PEGAWAI = new Pegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PegawaiRecord> getRecordType() {
        return PegawaiRecord.class;
    }

    /**
     * The column <code>pegawai.id</code>.
     */
    public final TableField<PegawaiRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>pegawai.changed_status</code>.
     */
    public final TableField<PegawaiRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>pegawai.absensi_id</code>.
     */
    public final TableField<PegawaiRecord, Long> ABSENSI_ID = createField(DSL.name("absensi_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.email</code>.
     */
    public final TableField<PegawaiRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>pegawai.gaji_pokok</code>.
     */
    public final TableField<PegawaiRecord, Double> GAJI_POKOK = createField(DSL.name("gaji_pokok"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>pegawai.is_askes</code>.
     */
    public final TableField<PegawaiRecord, Boolean> IS_ASKES = createField(DSL.name("is_askes"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "");

    /**
     * The column <code>pegawai.jml_tanggungan</code>.
     */
    public final TableField<PegawaiRecord, Integer> JML_TANGGUNGAN = createField(DSL.name("jml_tanggungan"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>pegawai.mkg_bulan</code>.
     */
    public final TableField<PegawaiRecord, Integer> MKG_BULAN = createField(DSL.name("mkg_bulan"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>pegawai.mkg_tahun</code>.
     */
    public final TableField<PegawaiRecord, Integer> MKG_TAHUN = createField(DSL.name("mkg_tahun"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>pegawai.nipam</code>.
     */
    public final TableField<PegawaiRecord, String> NIPAM = createField(DSL.name("nipam"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>pegawai.notes</code>.
     */
    public final TableField<PegawaiRecord, String> NOTES = createField(DSL.name("notes"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>pegawai.phdp</code>.
     */
    public final TableField<PegawaiRecord, Double> PHDP = createField(DSL.name("phdp"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>pegawai.ref_sk_capeg_id</code>.
     */
    public final TableField<PegawaiRecord, Long> REF_SK_CAPEG_ID = createField(DSL.name("ref_sk_capeg_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.ref_sk_gaji_berkala_id</code>.
     */
    public final TableField<PegawaiRecord, Long> REF_SK_GAJI_BERKALA_ID = createField(DSL.name("ref_sk_gaji_berkala_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.ref_sk_gol_id</code>.
     */
    public final TableField<PegawaiRecord, Long> REF_SK_GOL_ID = createField(DSL.name("ref_sk_gol_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.ref_sk_jabatan_id</code>.
     */
    public final TableField<PegawaiRecord, Long> REF_SK_JABATAN_ID = createField(DSL.name("ref_sk_jabatan_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.ref_sk_mutasi_id</code>.
     */
    public final TableField<PegawaiRecord, Long> REF_SK_MUTASI_ID = createField(DSL.name("ref_sk_mutasi_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.ref_sk_pegawai_id</code>.
     */
    public final TableField<PegawaiRecord, Long> REF_SK_PEGAWAI_ID = createField(DSL.name("ref_sk_pegawai_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.status_kerja</code>.
     */
    public final TableField<PegawaiRecord, Byte> STATUS_KERJA = createField(DSL.name("status_kerja"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>pegawai.status_pegawai</code>.
     */
    public final TableField<PegawaiRecord, Byte> STATUS_PEGAWAI = createField(DSL.name("status_pegawai"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>pegawai.tanggal_pengangkatan</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TANGGAL_PENGANGKATAN = createField(DSL.name("tanggal_pengangkatan"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>pegawai.tmt_gaji_berkala</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TMT_GAJI_BERKALA = createField(DSL.name("tmt_gaji_berkala"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>pegawai.tmt_golongan</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TMT_GOLONGAN = createField(DSL.name("tmt_golongan"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>pegawai.tmt_jabatan</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TMT_JABATAN = createField(DSL.name("tmt_jabatan"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>pegawai.tmt_kerja</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TMT_KERJA = createField(DSL.name("tmt_kerja"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>pegawai.tmt_mutasi</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TMT_MUTASI = createField(DSL.name("tmt_mutasi"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>pegawai.tmt_pegawai</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TMT_PEGAWAI = createField(DSL.name("tmt_pegawai"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>pegawai.tmt_pensiun</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TMT_PENSIUN = createField(DSL.name("tmt_pensiun"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>pegawai.biodata_id</code>.
     */
    public final TableField<PegawaiRecord, String> BIODATA_ID = createField(DSL.name("biodata_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>pegawai.gaji_profil_id</code>.
     */
    public final TableField<PegawaiRecord, Long> GAJI_PROFIL_ID = createField(DSL.name("gaji_profil_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.golongan_id</code>.
     */
    public final TableField<PegawaiRecord, Long> GOLONGAN_ID = createField(DSL.name("golongan_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.grade_id</code>.
     */
    public final TableField<PegawaiRecord, Long> GRADE_ID = createField(DSL.name("grade_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.jabatan_id</code>.
     */
    public final TableField<PegawaiRecord, Long> JABATAN_ID = createField(DSL.name("jabatan_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.gaji_pendapatan_non_pajak_id</code>.
     */
    public final TableField<PegawaiRecord, Long> GAJI_PENDAPATAN_NON_PAJAK_ID = createField(DSL.name("gaji_pendapatan_non_pajak_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.organisasi_id</code>.
     */
    public final TableField<PegawaiRecord, Long> ORGANISASI_ID = createField(DSL.name("organisasi_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.profesi_id</code>.
     */
    public final TableField<PegawaiRecord, Long> PROFESI_ID = createField(DSL.name("profesi_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.rumah_dinas_id</code>.
     */
    public final TableField<PegawaiRecord, Long> RUMAH_DINAS_ID = createField(DSL.name("rumah_dinas_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pegawai.created_at</code>.
     */
    public final TableField<PegawaiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>pegawai.created_by</code>.
     */
    public final TableField<PegawaiRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>pegawai.is_deleted</code>.
     */
    public final TableField<PegawaiRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>pegawai.updated_at</code>.
     */
    public final TableField<PegawaiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>pegawai.updated_by</code>.
     */
    public final TableField<PegawaiRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>pegawai.version</code>.
     */
    public final TableField<PegawaiRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private Pegawai(Name alias, Table<PegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Pegawai(Name alias, Table<PegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>pegawai</code> table reference
     */
    public Pegawai(String alias) {
        this(DSL.name(alias), PEGAWAI);
    }

    /**
     * Create an aliased <code>pegawai</code> table reference
     */
    public Pegawai(Name alias) {
        this(alias, PEGAWAI);
    }

    /**
     * Create a <code>pegawai</code> table reference
     */
    public Pegawai() {
        this(DSL.name("pegawai"), null);
    }

    public <O extends Record> Pegawai(Table<O> path, ForeignKey<O, PegawaiRecord> childPath, InverseForeignKey<O, PegawaiRecord> parentPath) {
        super(path, childPath, parentPath, PEGAWAI);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PegawaiPath extends Pegawai implements Path<PegawaiRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PegawaiPath(Table<O> path, ForeignKey<O, PegawaiRecord> childPath, InverseForeignKey<O, PegawaiRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PegawaiPath(Name alias, Table<PegawaiRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PegawaiPath as(String alias) {
            return new PegawaiPath(DSL.name(alias), this);
        }

        @Override
        public PegawaiPath as(Name alias) {
            return new PegawaiPath(alias, this);
        }

        @Override
        public PegawaiPath as(Table<?> alias) {
            return new PegawaiPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PEGAWAI_IDX_PGW_BIO_ID, Indexes.PEGAWAI_IDX_PGW_GJ_PP_NN_PJK_ID, Indexes.PEGAWAI_IDX_PGW_GJ_PRF_ID, Indexes.PEGAWAI_IDX_PGW_GLG_ID, Indexes.PEGAWAI_IDX_PGW_GRD_ID, Indexes.PEGAWAI_IDX_PGW_IS_DELETED, Indexes.PEGAWAI_IDX_PGW_JBT_ID, Indexes.PEGAWAI_IDX_PGW_ORG_ID, Indexes.PEGAWAI_IDX_PGW_PFS_ID, Indexes.PEGAWAI_IDX_PGW_RMH_DNS_ID, Indexes.PEGAWAI_IDX_PGW_TMT_PENSIUN);
    }

    @Override
    public Identity<PegawaiRecord, Long> getIdentity() {
        return (Identity<PegawaiRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PegawaiRecord> getPrimaryKey() {
        return Keys.KEY_PEGAWAI_PRIMARY;
    }

    @Override
    public List<UniqueKey<PegawaiRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PEGAWAI_UK_PGW_NIPAM);
    }

    @Override
    public List<ForeignKey<PegawaiRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PGW_BIO_BIO_ID, Keys.FK_PGW_GJ_PP_NN_PJK_GJ_PP_NN_PJK_ID, Keys.FK_PGW_GJ_PRF_GJ_PRF_ID, Keys.FK_PGW_GLG_GLG_ID, Keys.FK_PGW_GRD_GRD_ID, Keys.FK_PGW_JBT_JBT_ID, Keys.FK_PGW_ORG_ORG_ID, Keys.FK_PGW_PFS_PFS_ID, Keys.FK_PGW_RMH_DNS_RMH_DNS_ID);
    }

    private transient BiodataPath _biodata;

    /**
     * Get the implicit join path to the <code>biodata</code> table.
     */
    public BiodataPath biodata() {
        if (_biodata == null)
            _biodata = new BiodataPath(this, Keys.FK_PGW_BIO_BIO_ID, null);

        return _biodata;
    }

    private transient GajiPendapatanNonPajakPath _gajiPendapatanNonPajak;

    /**
     * Get the implicit join path to the <code>gaji_pendapatan_non_pajak</code>
     * table.
     */
    public GajiPendapatanNonPajakPath gajiPendapatanNonPajak() {
        if (_gajiPendapatanNonPajak == null)
            _gajiPendapatanNonPajak = new GajiPendapatanNonPajakPath(this, Keys.FK_PGW_GJ_PP_NN_PJK_GJ_PP_NN_PJK_ID, null);

        return _gajiPendapatanNonPajak;
    }

    private transient GajiProfilPath _gajiProfil;

    /**
     * Get the implicit join path to the <code>gaji_profil</code> table.
     */
    public GajiProfilPath gajiProfil() {
        if (_gajiProfil == null)
            _gajiProfil = new GajiProfilPath(this, Keys.FK_PGW_GJ_PRF_GJ_PRF_ID, null);

        return _gajiProfil;
    }

    private transient GolonganPath _golongan;

    /**
     * Get the implicit join path to the <code>golongan</code> table.
     */
    public GolonganPath golongan() {
        if (_golongan == null)
            _golongan = new GolonganPath(this, Keys.FK_PGW_GLG_GLG_ID, null);

        return _golongan;
    }

    private transient GradePath _grade;

    /**
     * Get the implicit join path to the <code>grade</code> table.
     */
    public GradePath grade() {
        if (_grade == null)
            _grade = new GradePath(this, Keys.FK_PGW_GRD_GRD_ID, null);

        return _grade;
    }

    private transient JabatanPath _jabatan;

    /**
     * Get the implicit join path to the <code>jabatan</code> table.
     */
    public JabatanPath jabatan() {
        if (_jabatan == null)
            _jabatan = new JabatanPath(this, Keys.FK_PGW_JBT_JBT_ID, null);

        return _jabatan;
    }

    private transient OrganisasiPath _organisasi;

    /**
     * Get the implicit join path to the <code>organisasi</code> table.
     */
    public OrganisasiPath organisasi() {
        if (_organisasi == null)
            _organisasi = new OrganisasiPath(this, Keys.FK_PGW_ORG_ORG_ID, null);

        return _organisasi;
    }

    private transient ProfesiPath _profesi;

    /**
     * Get the implicit join path to the <code>profesi</code> table.
     */
    public ProfesiPath profesi() {
        if (_profesi == null)
            _profesi = new ProfesiPath(this, Keys.FK_PGW_PFS_PFS_ID, null);

        return _profesi;
    }

    private transient RumahDinasPath _rumahDinas;

    /**
     * Get the implicit join path to the <code>rumah_dinas</code> table.
     */
    public RumahDinasPath rumahDinas() {
        if (_rumahDinas == null)
            _rumahDinas = new RumahDinasPath(this, Keys.FK_PGW_RMH_DNS_RMH_DNS_ID, null);

        return _rumahDinas;
    }

    private transient CutiApprovalPath _cutiApproval;

    /**
     * Get the implicit to-many join path to the <code>cuti_approval</code>
     * table
     */
    public CutiApprovalPath cutiApproval() {
        if (_cutiApproval == null)
            _cutiApproval = new CutiApprovalPath(this, null, Keys.FK_CT_APV_PGW_APPROVER_ID.getInverseKey());

        return _cutiApproval;
    }

    private transient CutiKuotaPath _cutiKuota;

    /**
     * Get the implicit to-many join path to the <code>cuti_kuota</code> table
     */
    public CutiKuotaPath cutiKuota() {
        if (_cutiKuota == null)
            _cutiKuota = new CutiKuotaPath(this, null, Keys.FK_CT_KTA_PGW_PGW_ID.getInverseKey());

        return _cutiKuota;
    }

    private transient CutiPegawaiPath _cutiPegawai;

    /**
     * Get the implicit to-many join path to the <code>cuti_pegawai</code> table
     */
    public CutiPegawaiPath cutiPegawai() {
        if (_cutiPegawai == null)
            _cutiPegawai = new CutiPegawaiPath(this, null, Keys.FK_CT_PGW_PGW_PGW_ID.getInverseKey());

        return _cutiPegawai;
    }

    private transient RiwayatCutiPath _riwayatCuti;

    /**
     * Get the implicit to-many join path to the <code>riwayat_cuti</code> table
     */
    public RiwayatCutiPath riwayatCuti() {
        if (_riwayatCuti == null)
            _riwayatCuti = new RiwayatCutiPath(this, null, Keys.FK_RWT_CT_PGW_PGW_ID.getInverseKey());

        return _riwayatCuti;
    }

    private transient RiwayatKeluarPath _fkRwtKlrPgwDisetujuiOleh;

    /**
     * Get the implicit to-many join path to the <code>riwayat_keluar</code>
     * table, via the <code>fk_rwt_klr_pgw_disetujui_oleh</code> key
     */
    public RiwayatKeluarPath fkRwtKlrPgwDisetujuiOleh() {
        if (_fkRwtKlrPgwDisetujuiOleh == null)
            _fkRwtKlrPgwDisetujuiOleh = new RiwayatKeluarPath(this, null, Keys.FK_RWT_KLR_PGW_DISETUJUI_OLEH.getInverseKey());

        return _fkRwtKlrPgwDisetujuiOleh;
    }

    private transient RiwayatKeluarPath _fkRwtKlrPgwPgwId;

    /**
     * Get the implicit to-many join path to the <code>riwayat_keluar</code>
     * table, via the <code>fk_rwt_klr_pgw_pgw_id</code> key
     */
    public RiwayatKeluarPath fkRwtKlrPgwPgwId() {
        if (_fkRwtKlrPgwPgwId == null)
            _fkRwtKlrPgwPgwId = new RiwayatKeluarPath(this, null, Keys.FK_RWT_KLR_PGW_PGW_ID.getInverseKey());

        return _fkRwtKlrPgwPgwId;
    }

    private transient RiwayatKontrakPath _riwayatKontrak;

    /**
     * Get the implicit to-many join path to the <code>riwayat_kontrak</code>
     * table
     */
    public RiwayatKontrakPath riwayatKontrak() {
        if (_riwayatKontrak == null)
            _riwayatKontrak = new RiwayatKontrakPath(this, null, Keys.FK_RWT_KTRK_PGW_PGW_ID.getInverseKey());

        return _riwayatKontrak;
    }

    private transient RiwayatMutasiPath _riwayatMutasi;

    /**
     * Get the implicit to-many join path to the <code>riwayat_mutasi</code>
     * table
     */
    public RiwayatMutasiPath riwayatMutasi() {
        if (_riwayatMutasi == null)
            _riwayatMutasi = new RiwayatMutasiPath(this, null, Keys.FK_RWT_MTS_PGW_PGW_ID.getInverseKey());

        return _riwayatMutasi;
    }

    private transient RiwayatSkPath _riwayatSk;

    /**
     * Get the implicit to-many join path to the <code>riwayat_sk</code> table
     */
    public RiwayatSkPath riwayatSk() {
        if (_riwayatSk == null)
            _riwayatSk = new RiwayatSkPath(this, null, Keys.FK_RWT_SK_PGW_PGW_ID.getInverseKey());

        return _riwayatSk;
    }

    private transient RiwayatSpPath _riwayatSp;

    /**
     * Get the implicit to-many join path to the <code>riwayat_sp</code> table
     */
    public RiwayatSpPath riwayatSp() {
        if (_riwayatSp == null)
            _riwayatSp = new RiwayatSpPath(this, null, Keys.FK_RWT_SP_PGW_PGW_ID.getInverseKey());

        return _riwayatSp;
    }

    private transient RiwayatTerminasiPath _riwayatTerminasi;

    /**
     * Get the implicit to-many join path to the <code>riwayat_terminasi</code>
     * table
     */
    public RiwayatTerminasiPath riwayatTerminasi() {
        if (_riwayatTerminasi == null)
            _riwayatTerminasi = new RiwayatTerminasiPath(this, null, Keys.FK_RWT_TRM_PGW_PGW_ID.getInverseKey());

        return _riwayatTerminasi;
    }

    @Override
    public Pegawai as(String alias) {
        return new Pegawai(DSL.name(alias), this);
    }

    @Override
    public Pegawai as(Name alias) {
        return new Pegawai(alias, this);
    }

    @Override
    public Pegawai as(Table<?> alias) {
        return new Pegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pegawai rename(String name) {
        return new Pegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pegawai rename(Name name) {
        return new Pegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pegawai rename(Table<?> name) {
        return new Pegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai where(Condition condition) {
        return new Pegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
