/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Biodata.BiodataPath;
import id.perumdamts.kepegawaian.jooq.tables.records.PengalamanKerjaRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PengalamanKerja extends TableImpl<PengalamanKerjaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.pengalaman_kerja</code>
     */
    public static final PengalamanKerja PENGALAMAN_KERJA = new PengalamanKerja();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PengalamanKerjaRecord> getRecordType() {
        return PengalamanKerjaRecord.class;
    }

    /**
     * The column <code>kepegawaian.pengalaman_kerja.id</code>.
     */
    public final TableField<PengalamanKerjaRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.changed_status</code>.
     */
    public final TableField<PengalamanKerjaRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.created_at</code>.
     */
    public final TableField<PengalamanKerjaRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.created_by</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.is_deleted</code>.
     */
    public final TableField<PengalamanKerjaRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.updated_at</code>.
     */
    public final TableField<PengalamanKerjaRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.updated_by</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.version</code>.
     */
    public final TableField<PengalamanKerjaRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.disetujui</code>.
     */
    public final TableField<PengalamanKerjaRecord, Byte> DISETUJUI = createField(DSL.name("disetujui"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.disetujui_oleh</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> DISETUJUI_OLEH = createField(DSL.name("disetujui_oleh"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.jabatan</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> JABATAN = createField(DSL.name("jabatan"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.lokasi</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> LOKASI = createField(DSL.name("lokasi"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.nama_perusahaan</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> NAMA_PERUSAHAAN = createField(DSL.name("nama_perusahaan"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.notes</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> NOTES = createField(DSL.name("notes"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.tahun_keluar</code>.
     */
    public final TableField<PengalamanKerjaRecord, Integer> TAHUN_KELUAR = createField(DSL.name("tahun_keluar"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.tahun_masuk</code>.
     */
    public final TableField<PengalamanKerjaRecord, Integer> TAHUN_MASUK = createField(DSL.name("tahun_masuk"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.tanggal_disetujui</code>.
     */
    public final TableField<PengalamanKerjaRecord, LocalDateTime> TANGGAL_DISETUJUI = createField(DSL.name("tanggal_disetujui"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.tanggal_pengajuan</code>.
     */
    public final TableField<PengalamanKerjaRecord, LocalDateTime> TANGGAL_PENGAJUAN = createField(DSL.name("tanggal_pengajuan"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.type_perusahaan</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> TYPE_PERUSAHAAN = createField(DSL.name("type_perusahaan"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.pengalaman_kerja.biodata_id</code>.
     */
    public final TableField<PengalamanKerjaRecord, String> BIODATA_ID = createField(DSL.name("biodata_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private PengalamanKerja(Name alias, Table<PengalamanKerjaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PengalamanKerja(Name alias, Table<PengalamanKerjaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.pengalaman_kerja</code> table
     * reference
     */
    public PengalamanKerja(String alias) {
        this(DSL.name(alias), PENGALAMAN_KERJA);
    }

    /**
     * Create an aliased <code>kepegawaian.pengalaman_kerja</code> table
     * reference
     */
    public PengalamanKerja(Name alias) {
        this(alias, PENGALAMAN_KERJA);
    }

    /**
     * Create a <code>kepegawaian.pengalaman_kerja</code> table reference
     */
    public PengalamanKerja() {
        this(DSL.name("pengalaman_kerja"), null);
    }

    public <O extends Record> PengalamanKerja(Table<O> path, ForeignKey<O, PengalamanKerjaRecord> childPath, InverseForeignKey<O, PengalamanKerjaRecord> parentPath) {
        super(path, childPath, parentPath, PENGALAMAN_KERJA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PengalamanKerjaPath extends PengalamanKerja implements Path<PengalamanKerjaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PengalamanKerjaPath(Table<O> path, ForeignKey<O, PengalamanKerjaRecord> childPath, InverseForeignKey<O, PengalamanKerjaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PengalamanKerjaPath(Name alias, Table<PengalamanKerjaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PengalamanKerjaPath as(String alias) {
            return new PengalamanKerjaPath(DSL.name(alias), this);
        }

        @Override
        public PengalamanKerjaPath as(Name alias) {
            return new PengalamanKerjaPath(alias, this);
        }

        @Override
        public PengalamanKerjaPath as(Table<?> alias) {
            return new PengalamanKerjaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PENGALAMAN_KERJA_IDXO52N89YL6IVYGURLKBBIUTEUM);
    }

    @Override
    public Identity<PengalamanKerjaRecord, Long> getIdentity() {
        return (Identity<PengalamanKerjaRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PengalamanKerjaRecord> getPrimaryKey() {
        return Keys.KEY_PENGALAMAN_KERJA_PRIMARY;
    }

    @Override
    public List<ForeignKey<PengalamanKerjaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKTFWLOU3LU3982TRUDGJVSQ8UH);
    }

    private transient BiodataPath _biodata;

    /**
     * Get the implicit join path to the <code>kepegawaian.biodata</code> table.
     */
    public BiodataPath biodata() {
        if (_biodata == null)
            _biodata = new BiodataPath(this, Keys.FKTFWLOU3LU3982TRUDGJVSQ8UH, null);

        return _biodata;
    }

    @Override
    public PengalamanKerja as(String alias) {
        return new PengalamanKerja(DSL.name(alias), this);
    }

    @Override
    public PengalamanKerja as(Name alias) {
        return new PengalamanKerja(alias, this);
    }

    @Override
    public PengalamanKerja as(Table<?> alias) {
        return new PengalamanKerja(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PengalamanKerja rename(String name) {
        return new PengalamanKerja(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PengalamanKerja rename(Name name) {
        return new PengalamanKerja(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PengalamanKerja rename(Table<?> name) {
        return new PengalamanKerja(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PengalamanKerja where(Condition condition) {
        return new PengalamanKerja(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PengalamanKerja where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PengalamanKerja where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PengalamanKerja where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PengalamanKerja where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PengalamanKerja where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PengalamanKerja where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PengalamanKerja where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PengalamanKerja whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PengalamanKerja whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
