/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Indexes;
import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.Keys;
import id.perumdamts.kepegawaian.jooq.tables.Jabatan.JabatanPath;
import id.perumdamts.kepegawaian.jooq.tables.JenisSp.JenisSpPath;
import id.perumdamts.kepegawaian.jooq.tables.Organisasi.OrganisasiPath;
import id.perumdamts.kepegawaian.jooq.tables.Pegawai.PegawaiPath;
import id.perumdamts.kepegawaian.jooq.tables.SanksiSp.SanksiSpPath;
import id.perumdamts.kepegawaian.jooq.tables.records.RiwayatSpRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RiwayatSp extends TableImpl<RiwayatSpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.riwayat_sp</code>
     */
    public static final RiwayatSp RIWAYAT_SP = new RiwayatSp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RiwayatSpRecord> getRecordType() {
        return RiwayatSpRecord.class;
    }

    /**
     * The column <code>kepegawaian.riwayat_sp.id</code>.
     */
    public final TableField<RiwayatSpRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.changed_status</code>.
     */
    public final TableField<RiwayatSpRecord, Byte> CHANGED_STATUS = createField(DSL.name("changed_status"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.created_at</code>.
     */
    public final TableField<RiwayatSpRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.created_by</code>.
     */
    public final TableField<RiwayatSpRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.is_deleted</code>.
     */
    public final TableField<RiwayatSpRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.updated_at</code>.
     */
    public final TableField<RiwayatSpRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.updated_by</code>.
     */
    public final TableField<RiwayatSpRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.version</code>.
     */
    public final TableField<RiwayatSpRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.file_name</code>.
     */
    public final TableField<RiwayatSpRecord, String> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.hashed_file_name</code>.
     */
    public final TableField<RiwayatSpRecord, String> HASHED_FILE_NAME = createField(DSL.name("hashed_file_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.mime_type</code>.
     */
    public final TableField<RiwayatSpRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.jabatan_penanda_tangan</code>.
     */
    public final TableField<RiwayatSpRecord, String> JABATAN_PENANDA_TANGAN = createField(DSL.name("jabatan_penanda_tangan"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.nama</code>.
     */
    public final TableField<RiwayatSpRecord, String> NAMA = createField(DSL.name("nama"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.nama_jabatan</code>.
     */
    public final TableField<RiwayatSpRecord, String> NAMA_JABATAN = createField(DSL.name("nama_jabatan"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.nama_organisasi</code>.
     */
    public final TableField<RiwayatSpRecord, String> NAMA_ORGANISASI = createField(DSL.name("nama_organisasi"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.nipam</code>.
     */
    public final TableField<RiwayatSpRecord, String> NIPAM = createField(DSL.name("nipam"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.nomor_sp</code>.
     */
    public final TableField<RiwayatSpRecord, String> NOMOR_SP = createField(DSL.name("nomor_sp"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.notes</code>.
     */
    public final TableField<RiwayatSpRecord, String> NOTES = createField(DSL.name("notes"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.penanda_tangan</code>.
     */
    public final TableField<RiwayatSpRecord, String> PENANDA_TANGAN = createField(DSL.name("penanda_tangan"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.sanksi_notes</code>.
     */
    public final TableField<RiwayatSpRecord, String> SANKSI_NOTES = createField(DSL.name("sanksi_notes"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.tanggal_eksekusi_sanksi</code>.
     */
    public final TableField<RiwayatSpRecord, LocalDate> TANGGAL_EKSEKUSI_SANKSI = createField(DSL.name("tanggal_eksekusi_sanksi"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.tanggal_mulai</code>.
     */
    public final TableField<RiwayatSpRecord, LocalDate> TANGGAL_MULAI = createField(DSL.name("tanggal_mulai"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.tanggal_selesai</code>.
     */
    public final TableField<RiwayatSpRecord, LocalDate> TANGGAL_SELESAI = createField(DSL.name("tanggal_selesai"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.tanggal_sp</code>.
     */
    public final TableField<RiwayatSpRecord, LocalDate> TANGGAL_SP = createField(DSL.name("tanggal_sp"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.jabatan_id</code>.
     */
    public final TableField<RiwayatSpRecord, Long> JABATAN_ID = createField(DSL.name("jabatan_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.jenis_sp_id</code>.
     */
    public final TableField<RiwayatSpRecord, Long> JENIS_SP_ID = createField(DSL.name("jenis_sp_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.organisasi_id</code>.
     */
    public final TableField<RiwayatSpRecord, Long> ORGANISASI_ID = createField(DSL.name("organisasi_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.pegawai_id</code>.
     */
    public final TableField<RiwayatSpRecord, Long> PEGAWAI_ID = createField(DSL.name("pegawai_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.riwayat_sp.sanksi_id</code>.
     */
    public final TableField<RiwayatSpRecord, Long> SANKSI_ID = createField(DSL.name("sanksi_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    private RiwayatSp(Name alias, Table<RiwayatSpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RiwayatSp(Name alias, Table<RiwayatSpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kepegawaian.riwayat_sp</code> table reference
     */
    public RiwayatSp(String alias) {
        this(DSL.name(alias), RIWAYAT_SP);
    }

    /**
     * Create an aliased <code>kepegawaian.riwayat_sp</code> table reference
     */
    public RiwayatSp(Name alias) {
        this(alias, RIWAYAT_SP);
    }

    /**
     * Create a <code>kepegawaian.riwayat_sp</code> table reference
     */
    public RiwayatSp() {
        this(DSL.name("riwayat_sp"), null);
    }

    public <O extends Record> RiwayatSp(Table<O> path, ForeignKey<O, RiwayatSpRecord> childPath, InverseForeignKey<O, RiwayatSpRecord> parentPath) {
        super(path, childPath, parentPath, RIWAYAT_SP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RiwayatSpPath extends RiwayatSp implements Path<RiwayatSpRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RiwayatSpPath(Table<O> path, ForeignKey<O, RiwayatSpRecord> childPath, InverseForeignKey<O, RiwayatSpRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RiwayatSpPath(Name alias, Table<RiwayatSpRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RiwayatSpPath as(String alias) {
            return new RiwayatSpPath(DSL.name(alias), this);
        }

        @Override
        public RiwayatSpPath as(Name alias) {
            return new RiwayatSpPath(alias, this);
        }

        @Override
        public RiwayatSpPath as(Table<?> alias) {
            return new RiwayatSpPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RIWAYAT_SP_IDX482OG76FSE137VVUHEWPPW4HS, Indexes.RIWAYAT_SP_IDX9BYHSAG4C837GM2CYN3OA8RKS, Indexes.RIWAYAT_SP_IDXFRM7005GBXJRD5N5EVVPFS341);
    }

    @Override
    public Identity<RiwayatSpRecord, Long> getIdentity() {
        return (Identity<RiwayatSpRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RiwayatSpRecord> getPrimaryKey() {
        return Keys.KEY_RIWAYAT_SP_PRIMARY;
    }

    @Override
    public List<ForeignKey<RiwayatSpRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK2Q8E6HBP5N4DBGBTP1YVUVG9E, Keys.FKBIG7GAK8CSIF6HU1096NXTU04, Keys.FKCH0QHFC0IH9I6QLAG1EEA1C7F, Keys.FKI7MYY0NWFD6I2TQE2K2FO0PWB, Keys.FKME2KGEMSCNC9EB7U7FS1LF8N);
    }

    private transient JabatanPath _jabatan;

    /**
     * Get the implicit join path to the <code>kepegawaian.jabatan</code> table.
     */
    public JabatanPath jabatan() {
        if (_jabatan == null)
            _jabatan = new JabatanPath(this, Keys.FK2Q8E6HBP5N4DBGBTP1YVUVG9E, null);

        return _jabatan;
    }

    private transient JenisSpPath _jenisSp;

    /**
     * Get the implicit join path to the <code>kepegawaian.jenis_sp</code>
     * table.
     */
    public JenisSpPath jenisSp() {
        if (_jenisSp == null)
            _jenisSp = new JenisSpPath(this, Keys.FKBIG7GAK8CSIF6HU1096NXTU04, null);

        return _jenisSp;
    }

    private transient OrganisasiPath _organisasi;

    /**
     * Get the implicit join path to the <code>kepegawaian.organisasi</code>
     * table.
     */
    public OrganisasiPath organisasi() {
        if (_organisasi == null)
            _organisasi = new OrganisasiPath(this, Keys.FKCH0QHFC0IH9I6QLAG1EEA1C7F, null);

        return _organisasi;
    }

    private transient SanksiSpPath _sanksiSp;

    /**
     * Get the implicit join path to the <code>kepegawaian.sanksi_sp</code>
     * table.
     */
    public SanksiSpPath sanksiSp() {
        if (_sanksiSp == null)
            _sanksiSp = new SanksiSpPath(this, Keys.FKI7MYY0NWFD6I2TQE2K2FO0PWB, null);

        return _sanksiSp;
    }

    private transient PegawaiPath _pegawai;

    /**
     * Get the implicit join path to the <code>kepegawaian.pegawai</code> table.
     */
    public PegawaiPath pegawai() {
        if (_pegawai == null)
            _pegawai = new PegawaiPath(this, Keys.FKME2KGEMSCNC9EB7U7FS1LF8N, null);

        return _pegawai;
    }

    @Override
    public RiwayatSp as(String alias) {
        return new RiwayatSp(DSL.name(alias), this);
    }

    @Override
    public RiwayatSp as(Name alias) {
        return new RiwayatSp(alias, this);
    }

    @Override
    public RiwayatSp as(Table<?> alias) {
        return new RiwayatSp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RiwayatSp rename(String name) {
        return new RiwayatSp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RiwayatSp rename(Name name) {
        return new RiwayatSp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RiwayatSp rename(Table<?> name) {
        return new RiwayatSp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RiwayatSp where(Condition condition) {
        return new RiwayatSp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RiwayatSp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RiwayatSp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RiwayatSp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RiwayatSp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RiwayatSp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RiwayatSp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RiwayatSp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RiwayatSp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RiwayatSp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
