/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables;


import id.perumdamts.kepegawaian.jooq.Kepegawaian;
import id.perumdamts.kepegawaian.jooq.tables.records.VPegawaiRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDate;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VPegawai extends TableImpl<VPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kepegawaian.v_pegawai</code>
     */
    public static final VPegawai V_PEGAWAI = new VPegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VPegawaiRecord> getRecordType() {
        return VPegawaiRecord.class;
    }

    /**
     * The column <code>kepegawaian.v_pegawai.id</code>.
     */
    public final TableField<VPegawaiRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.nipam</code>.
     */
    public final TableField<VPegawaiRecord, String> NIPAM = createField(DSL.name("nipam"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.nik</code>.
     */
    public final TableField<VPegawaiRecord, String> NIK = createField(DSL.name("nik"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.nama</code>.
     */
    public final TableField<VPegawaiRecord, String> NAMA = createField(DSL.name("nama"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.jenis_kelamin</code>.
     */
    public final TableField<VPegawaiRecord, Byte> JENIS_KELAMIN = createField(DSL.name("jenis_kelamin"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.status_kawin</code>.
     */
    public final TableField<VPegawaiRecord, Byte> STATUS_KAWIN = createField(DSL.name("status_kawin"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.tempat_lahir</code>.
     */
    public final TableField<VPegawaiRecord, String> TEMPAT_LAHIR = createField(DSL.name("tempat_lahir"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.tanggal_lahir</code>.
     */
    public final TableField<VPegawaiRecord, LocalDate> TANGGAL_LAHIR = createField(DSL.name("tanggal_lahir"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.organisasi_id</code>.
     */
    public final TableField<VPegawaiRecord, Long> ORGANISASI_ID = createField(DSL.name("organisasi_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.nama_organisasi</code>.
     */
    public final TableField<VPegawaiRecord, String> NAMA_ORGANISASI = createField(DSL.name("nama_organisasi"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.jabatan_id</code>.
     */
    public final TableField<VPegawaiRecord, Long> JABATAN_ID = createField(DSL.name("jabatan_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.nama_jabatan</code>.
     */
    public final TableField<VPegawaiRecord, String> NAMA_JABATAN = createField(DSL.name("nama_jabatan"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.golongan_id</code>.
     */
    public final TableField<VPegawaiRecord, Long> GOLONGAN_ID = createField(DSL.name("golongan_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.golongan</code>.
     */
    public final TableField<VPegawaiRecord, String> GOLONGAN = createField(DSL.name("golongan"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.pangkat</code>.
     */
    public final TableField<VPegawaiRecord, String> PANGKAT = createField(DSL.name("pangkat"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.status_kerja</code>.
     */
    public final TableField<VPegawaiRecord, Byte> STATUS_KERJA = createField(DSL.name("status_kerja"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>kepegawaian.v_pegawai.status_pegawai</code>.
     */
    public final TableField<VPegawaiRecord, Byte> STATUS_PEGAWAI = createField(DSL.name("status_pegawai"), SQLDataType.TINYINT.nullable(false), this, "");

    private VPegawai(Name alias, Table<VPegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VPegawai(Name alias, Table<VPegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view `v_pegawai` as select `peg`.`id` AS `id`,`peg`.`nipam` AS `nipam`,`bio`.`nik` AS `nik`,`bio`.`nama` AS `nama`,`bio`.`jenis_kelamin` AS `jenis_kelamin`,`bio`.`status_kawin` AS `status_kawin`,`bio`.`tempat_lahir` AS `tempat_lahir`,`bio`.`tanggal_lahir` AS `tanggal_lahir`,`org`.`id` AS `organisasi_id`,`org`.`nama` AS `nama_organisasi`,`jab`.`id` AS `jabatan_id`,`jab`.`nama` AS `nama_jabatan`,`gol`.`id` AS `golongan_id`,`gol`.`golongan` AS `golongan`,`gol`.`pangkat` AS `pangkat`,`peg`.`status_kerja` AS `status_kerja`,`peg`.`status_pegawai` AS `status_pegawai` from ((((`kepegawaian`.`pegawai` `peg` join `kepegawaian`.`biodata` `bio` on(`peg`.`nik` = `bio`.`nik`)) join `kepegawaian`.`organisasi` `org` on(`peg`.`organisasi_id` = `org`.`id`)) join `kepegawaian`.`jabatan` `jab` on(`peg`.`jabatan_id` = `jab`.`id`)) join `kepegawaian`.`golongan` `gol` on(`peg`.`golongan_id` = `gol`.`id`)) where `peg`.`status_kerja` in (1,2)"), where);
    }

    /**
     * Create an aliased <code>kepegawaian.v_pegawai</code> table reference
     */
    public VPegawai(String alias) {
        this(DSL.name(alias), V_PEGAWAI);
    }

    /**
     * Create an aliased <code>kepegawaian.v_pegawai</code> table reference
     */
    public VPegawai(Name alias) {
        this(alias, V_PEGAWAI);
    }

    /**
     * Create a <code>kepegawaian.v_pegawai</code> table reference
     */
    public VPegawai() {
        this(DSL.name("v_pegawai"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public VPegawai as(String alias) {
        return new VPegawai(DSL.name(alias), this);
    }

    @Override
    public VPegawai as(Name alias) {
        return new VPegawai(alias, this);
    }

    @Override
    public VPegawai as(Table<?> alias) {
        return new VPegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VPegawai rename(String name) {
        return new VPegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VPegawai rename(Name name) {
        return new VPegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VPegawai rename(Table<?> name) {
        return new VPegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VPegawai where(Condition condition) {
        return new VPegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VPegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VPegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VPegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VPegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VPegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VPegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VPegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VPegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VPegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
