SET FOREIGN_KEY_CHECKS = 0;
-- Seed: gaji_komponen part 2/3 (records 111-220 of 280)

INSERT INTO gaji_komponen (urut, profil_gaji_id, kode, nama, jenis_gaji, nilai, is_reference, formula, is_deleted, created_at, created_by, updated_at, updated_by) VALUES
(16, 4, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 4, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 4, 'ASTEK', 'Astek', 'NONE', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 4, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 4, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 4, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 4, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 4, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 4, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 4, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 4, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, '( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 4, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, '( REF_JML_POT_KK / 22 ) * GP', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 4, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, 'TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 4, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(30, 4, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(31, 4, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(32, 4, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(1, 5, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 5, 'REF_TUNJ_JABATAN', 'Referensi Tunjangan Jabatan', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 5, 'REF_TUNJ_BERAS', 'Referensi Tunjangan Beras', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 5, 'REF_TUNJ_KK', 'Referensi Tunjangan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 5, 'REF_TUNJ_AIR', 'Referensi Tunjangan Air', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 5, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 5, 'REF_POT_TKK', 'Referensi Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 5, 'REF_PTKP', 'Referensi Pendapatan Tidak Kena Pajak', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 5, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 5, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 5, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '0.1 * GP ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 5, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, 'JML_ANAK *  ( 0.05 * GP )', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 5, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, 'REF_TUNJ_JABATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 5, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, 'JML_JIWA * REF_TUNJ_BERAS ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 5, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, 'REF_TUNJ_KK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 5, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, 'REF_TUNJ_AIR ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 5, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 5, 'ASTEK', 'Astek', 'NONE', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 5, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 5, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 5, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 5, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 5, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 5, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 5, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 5, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, '( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 5, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, 'REF_JML_POT_KK * REF_POT_TKK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 5, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, 'TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 5, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(30, 5, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(31, 5, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(32, 5, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(1, 6, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 6, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 6, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 6, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 6, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 6, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 6, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 6, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 6, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 6, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 6, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 6, 'ASTEK', 'Astek', 'NONE', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 6, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 6, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 6, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 6, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 6, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, 'GP * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 6, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 6, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, 'GP * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 6, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, 'GP * 0.01 * REF_ASKES', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 6, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, '( REF_JML_POT_KK / 22 ) * GP', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 6, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, 'TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 6, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 6, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 6, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 6, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(1, 7, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 7, 'REF_TUNJ_JABATAN', 'Referensi Tunjangan Jabatan', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 7, 'REF_TUNJ_BERAS', 'Referensi Tunjangan Beras', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 7, 'REF_TUNJ_KK', 'Referensi Tunjangan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 7, 'REF_TUNJ_AIR', 'Referensi Tunjangan Air', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 7, 'REF_PHDP', 'Referensi PHDP', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 7, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 7, 'REF_POT_TKK', 'Referensi Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 7, 'REF_PTKP', 'Referensi Pendapatan Tidak Kena Pajak', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 7, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 7, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 7, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 7, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, 'JML_ANAK *  ( 0.05 * GP )', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 7, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, 'REF_TUNJ_JABATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 7, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, 'JML_JIWA * REF_TUNJ_BERAS ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 7, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, 'REF_TUNJ_KK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 7, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, 'REF_TUNJ_AIR ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 7, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 7, 'ASTEK', 'Astek', 'NONE', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 7, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 7, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 7, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 7, 'PHDP', 'PhDP', 'NONE', 0, 0, 'REF_PHDP ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 7, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, 'PHDP * 0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 7, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 7, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 7, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 7, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, '( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 7, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, 'REF_JML_POT_KK * REF_POT_TKK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(30, 7, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, 'TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(31, 7, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(32, 7, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(33, 7, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(34, 7, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(1, 8, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');
SET FOREIGN_KEY_CHECKS = 1;
