SET FOREIGN_KEY_CHECKS = 0;
-- Seed: gaji_komponen part 3/3 (records 221-280 of 280)

INSERT INTO gaji_komponen (urut, profil_gaji_id, kode, nama, jenis_gaji, nilai, is_reference, formula, is_deleted, created_at, created_by, updated_at, updated_by) VALUES
(2, 8, 'REF_TUNJ_JABATAN', 'Referensi Tunjangan Jabatan', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 8, 'REF_TUNJ_BERAS', 'Referensi Tunjangan Beras', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 8, 'REF_TUNJ_KK', 'Referensi Tunjangan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 8, 'REF_TUNJ_AIR', 'Referensi Tunjangan Air', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 8, 'REF_PHDP', 'Referensi PHDP', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 8, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 8, 'REF_PTKP', 'Referensi Pendapatan Tidak Kena Pajak', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 8, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 8, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 8, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '0.1 * GP ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 8, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, 'JML_ANAK *  ( 0.05 * GP )', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 8, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, 'REF_TUNJ_JABATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 8, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, 'JML_JIWA * REF_TUNJ_BERAS ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 8, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 8, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 8, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 8, 'ASTEK', 'Astek', 'NONE', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 8, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 8, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 8, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 8, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 8, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 8, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 8, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 8, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, '1750000 * 0.01 * REF_ASKES ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 8, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, '( REF_JML_POT_KK / 22 ) * GP', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 8, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, 'TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 8, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(30, 8, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(31, 8, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(32, 8, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(1, 9, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 9, 'REF_PTKP', 'Referensi Pendapatan Tidak Kena Pajak', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 9, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 9, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 9, 'REF_POT_TKK', 'Referensi Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 9, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 9, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 9, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 9, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 9, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 9, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 9, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 9, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 9, 'ASTEK', 'Astek', 'NONE', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 9, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 9, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 9, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 9, 'PHDP', 'PhDP', 'NONE', 23736460, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 9, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, 'PHDP * 0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 9, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 9, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 9, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 9, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, '( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 9, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, 'REF_JML_POT_KK * REF_POT_TKK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 9, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, '( PKP - ( 0.05 * PKP ) - REF_PTKP ) * 0.1', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 9, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 9, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 9, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 9, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');
SET FOREIGN_KEY_CHECKS = 1;
