-- kepegawaian-m04g: tambah field `group` (grup hierarki) pada master Organisasi.
-- Kolom DB bernama `org_group` karena `group` reserved word di MariaDB; JSON/DTO tetap `group`.
-- Wajib (NOT NULL) dengan default '' — record yang belum dikelompokkan dirender FE sebagai "belum dikelompokkan".

ALTER TABLE `organisasi` ADD COLUMN `org_group` varchar(64) NOT NULL DEFAULT '' AFTER `category`;

-- Backfill mapping nama → group dari `docs/organization.sql` (kolom `group` di smartoffice.organization).
-- Match by nama (isi seed V3 sama dengan legacy); record yang tidak match tetap '' (default kolom).
UPDATE `organisasi` SET `org_group` = CASE `nama`
    WHEN 'BAG. HUMAS & HUKUM' THEN '06.BAGIAN HUMAS & HUKUM'
    WHEN 'BAG. KESEKRETARIATAN' THEN '07.BAGIAN KESEKRETARIATAN'
    WHEN 'BAG. KEUANGAN' THEN '08.BAGIAN KEUANGAN'
    WHEN 'BAG. PENGENDALIAN TEKNIK' THEN '06.BAGIAN PENGENDALIAN TEKNIK'
    WHEN 'BAG. PERENCANAAN & PENGEMBANGAN' THEN '03.BAGIAN PERENCANAAN & PENGEMBANGAN'
    WHEN 'BAG. PERLENGKAPAN' THEN '10.BAGIAN PERLENGKAPAN'
    WHEN 'BAG. PRODUKSI & DISTRIBUSI 1' THEN '04.BAGIAN PRODUKSI & DISTRIBUSI 1'
    WHEN 'BAG. PRODUKSI & DISTRIBUSI 2' THEN '05.BAGIAN PRODUKSI & DISTRIBUSI 2'
    WHEN 'BAG. SUMBER DAYA MANUSIA & TI' THEN '09.BAGIAN SUMBER DAYA MANUSIA & TI'
    WHEN 'BID. PENELITIAN & PENGEMBANGAN' THEN '03.BIDANG PENELITIAN & PENGEMBANGAN'
    WHEN 'BID. TEKNOLOGI INFORMASI' THEN '04.BIDANG TEKNOLOGI INFORMASI'
    WHEN 'CABANG AJIBARANG' THEN '13.CABANG AJIBARANG'
    WHEN 'CABANG BANYUMAS' THEN '15.CABANG BANYUMAS'
    WHEN 'CABANG PURWOKERTO 1' THEN '11.CABANG PURWOKERTO 1'
    WHEN 'CABANG PURWOKERTO 2' THEN '12.CABANG PURWOKERTO 2'
    WHEN 'CABANG WANGON' THEN '14.CABANG WANGON'
    WHEN 'DIREKTORAT ADMIN & KEUANGAN' THEN '01.DIREKSI'
    WHEN 'DIREKTORAT TEKNIK' THEN '01.DIREKSI'
    WHEN 'DIREKTORAT UTAMA' THEN '01.DIREKSI'
    WHEN 'SATUAN PENGAWAS INTERN' THEN '02.SATUAN PENGAWAS INTERN'
    WHEN 'SUB BAG ADM & KEU CAB. AJIBARANG' THEN '13.CABANG AJIBARANG'
    WHEN 'SUB BAG ADM & KEU CAB. BANYUMAS' THEN '15.CABANG BANYUMAS'
    WHEN 'SUB BAG ADM & KEU CAB. PWKT 1' THEN '11.CABANG PURWOKERTO 1'
    WHEN 'SUB BAG ADM & KEU CAB. PWKT 2' THEN '12.CABANG PURWOKERTO 2'
    WHEN 'SUB BAG ADM & KEU CAB. WANGON' THEN '14.CABANG WANGON'
    WHEN 'SUB BAG ADM & PENGEMBANGAN SDM' THEN '09.BAGIAN SUMBER DAYA MANUSIA & TI'
    WHEN 'SUB BAG AKUNTANSI' THEN '08.BAGIAN KEUANGAN'
    WHEN 'SUB BAG ANGGARAN & PELAPORAN' THEN '08.BAGIAN KEUANGAN'
    WHEN 'SUB BAG ASET' THEN '10.BAGIAN PERLENGKAPAN'
    WHEN 'SUB BAG AUDIT INTERN' THEN '02.SATUAN PENGAWAS INTERN'
    WHEN 'SUB BAG HUKUM & PERIZINAN' THEN '07.BAGIAN KESEKRETARIATAN'
    WHEN 'SUB BAG MEKANIKAL & ELEKTRIKAL' THEN '06.BAGIAN PENGENDALIAN TEKNIK'
    WHEN 'SUB BAG PELAYANAN CAB. AJIBARANG' THEN '13.CABANG AJIBARANG'
    WHEN 'SUB BAG PELAYANAN CAB. BANYUMAS' THEN '15.CABANG BANYUMAS'
    WHEN 'SUB BAG PELAYANAN CAB. PWKT 1' THEN '11.CABANG PURWOKERTO 1'
    WHEN 'SUB BAG PELAYANAN CAB. PWKT 2' THEN '12.CABANG PURWOKERTO 2'
    WHEN 'SUB BAG PELAYANAN CAB. WANGON' THEN '14.CABANG WANGON'
    WHEN 'SUB BAG PEMASARAN' THEN '16.UNIT BISNIS AMDK'
    WHEN 'SUB BAG PENGADAAN' THEN '10.BAGIAN PERLENGKAPAN'
    WHEN 'SUB BAG PENGAWASAN PEKERJAAN' THEN '02.SATUAN PENGAWAS INTERN'
    WHEN 'SUB BAG PENGEMBANGAN' THEN '09.BAGIAN PERENCANAAN & PENGEMBANGAN'
    WHEN 'SUB BAG PENGEMBANGAN 2' THEN '03.BAGIAN PERENCANAAN & PENGEMBANGAN'
    WHEN 'SUB BAG PENGENDALIAN DISTRIBUSI 1' THEN '04.BAGIAN PRODUKSI & DISTRIBUSI 1'
    WHEN 'SUB BAG PENGENDALIAN DISTRIBUSI 1 baru' THEN '10.BAGIAN PRODUKSI & DISTRIBUSI 1'
    WHEN 'SUB BAG PENGENDALIAN DISTRIBUSI 2' THEN '05.BAGIAN PRODUKSI & DISTRIBUSI 2'
    WHEN 'SUB BAG PENGENDALIAN DISTRIBUSI 2 - baru' THEN '11.BAGIAN PRODUKSI & DISTRIBUSI 2'
    WHEN 'SUB BAG PENGENDALIAN KEHILANGAN AIR' THEN '06.BAGIAN PENGENDALIAN TEKNIK'
    WHEN 'SUB BAG PENGENDALIAN PRODUKSI 1' THEN '04.BAGIAN PRODUKSI & DISTRIBUSI 1'
    WHEN 'SUB BAG PENGENDALIAN PRODUKSI 2' THEN '05.BAGIAN PRODUKSI & DISTRIBUSI 2'
    WHEN 'SUB BAG PENJAMINAN MUTU AIR' THEN '06.BAGIAN PENGENDALIAN TEKNIK'
    WHEN 'SUB BAG PERBENDAHARAAN' THEN '08.BAGIAN KEUANGAN'
    WHEN 'SUB BAG PERENCANAAN' THEN '03.BAGIAN PERENCANAAN & PENGEMBANGAN'
    WHEN 'SUB BAG PERSEDIAAN' THEN '10.BAGIAN PERLENGKAPAN'
    WHEN 'SUB BAG PRODUKSI' THEN '16.UNIT BISNIS AMDK'
    WHEN 'SUB BAG REHAB JARINGAN PIPA' THEN '12.BAGIAN REHABILITASI & PENGENDALIAN PEMELIHARAAN'
    WHEN 'SUB BAG REMUNERASI & K3' THEN '09.BAGIAN SUMBER DAYA MANUSIA & TI'
    WHEN 'SUB BAG STANDARDISASI' THEN '02.SATUAN PENGAWAS INTERN'
    WHEN 'SUB BAG TATA USAHA & RUMAH TANGGA' THEN '07.BAGIAN KESEKRETARIATAN'
    WHEN 'SUB BAG TEKNIK CAB. AJIBARANG' THEN '13.CABANG AJIBARANG'
    WHEN 'SUB BAG TEKNIK CAB. BANYUMAS' THEN '15.CABANG BANYUMAS'
    WHEN 'SUB BAG TEKNIK CAB. PWKT 1' THEN '11.CABANG PURWOKERTO 1'
    WHEN 'SUB BAG TEKNIK CAB. PWKT 2' THEN '12.CABANG PURWOKERTO 2'
    WHEN 'SUB BAG TEKNIK CAB. WANGON' THEN '14.CABANG WANGON'
    WHEN 'SUB BAG TEKNOLOGI INFORMASI' THEN '09.BAGIAN SUMBER DAYA MANUSIA & TI'
    WHEN 'SUB BAG UMUM CAB. AJIBARANG' THEN '15.CABANG AJIBARANG'
    WHEN 'SUB BAG UMUM CAB. BANYUMAS' THEN '17.CABANG BANYUMAS'
    WHEN 'SUB BAG UMUM CAB. PWKT 1' THEN '13.CABANG PURWOKERTO 1'
    WHEN 'SUB BAG UMUM CAB. PWKT 2' THEN '14.CABANG PURWOKERTO 2'
    WHEN 'SUB BAG UMUM CAB. WANGON' THEN '16.CABANG WANGON'
    WHEN 'SUB BID MANAJEMEN INFORMASI' THEN '04.BIDANG TEKNOLOGI INFORMASI'
    WHEN 'SUB BID PENGENDALIAN DOKUMEN' THEN '02.BIDANG PENGAWASAN INTERNAL'
    WHEN 'UNIT BISNIS AMDK' THEN '16.UNIT BISNIS AMDK'
END
WHERE `nama` IN (
    'BAG. HUMAS & HUKUM','BAG. KESEKRETARIATAN','BAG. KEUANGAN','BAG. PENGENDALIAN TEKNIK',
    'BAG. PERENCANAAN & PENGEMBANGAN','BAG. PERLENGKAPAN','BAG. PRODUKSI & DISTRIBUSI 1',
    'BAG. PRODUKSI & DISTRIBUSI 2','BAG. SUMBER DAYA MANUSIA & TI','BID. PENELITIAN & PENGEMBANGAN',
    'BID. TEKNOLOGI INFORMASI','CABANG AJIBARANG','CABANG BANYUMAS','CABANG PURWOKERTO 1',
    'CABANG PURWOKERTO 2','CABANG WANGON','DIREKTORAT ADMIN & KEUANGAN','DIREKTORAT TEKNIK',
    'DIREKTORAT UTAMA','SATUAN PENGAWAS INTERN','SUB BAG ADM & KEU CAB. AJIBARANG',
    'SUB BAG ADM & KEU CAB. BANYUMAS','SUB BAG ADM & KEU CAB. PWKT 1','SUB BAG ADM & KEU CAB. PWKT 2',
    'SUB BAG ADM & KEU CAB. WANGON','SUB BAG ADM & PENGEMBANGAN SDM','SUB BAG AKUNTANSI',
    'SUB BAG ANGGARAN & PELAPORAN','SUB BAG ASET','SUB BAG AUDIT INTERN','SUB BAG HUKUM & PERIZINAN',
    'SUB BAG MEKANIKAL & ELEKTRIKAL','SUB BAG PELAYANAN CAB. AJIBARANG','SUB BAG PELAYANAN CAB. BANYUMAS',
    'SUB BAG PELAYANAN CAB. PWKT 1','SUB BAG PELAYANAN CAB. PWKT 2','SUB BAG PELAYANAN CAB. WANGON',
    'SUB BAG PEMASARAN','SUB BAG PENGADAAN','SUB BAG PENGAWASAN PEKERJAAN','SUB BAG PENGEMBANGAN',
    'SUB BAG PENGEMBANGAN 2','SUB BAG PENGENDALIAN DISTRIBUSI 1','SUB BAG PENGENDALIAN DISTRIBUSI 1 baru',
    'SUB BAG PENGENDALIAN DISTRIBUSI 2','SUB BAG PENGENDALIAN DISTRIBUSI 2 - baru',
    'SUB BAG PENGENDALIAN KEHILANGAN AIR','SUB BAG PENGENDALIAN PRODUKSI 1','SUB BAG PENGENDALIAN PRODUKSI 2',
    'SUB BAG PENJAMINAN MUTU AIR','SUB BAG PERBENDAHARAAN','SUB BAG PERENCANAAN','SUB BAG PERSEDIAAN',
    'SUB BAG PRODUKSI','SUB BAG REHAB JARINGAN PIPA','SUB BAG REMUNERASI & K3','SUB BAG STANDARDISASI',
    'SUB BAG TATA USAHA & RUMAH TANGGA','SUB BAG TEKNIK CAB. AJIBARANG','SUB BAG TEKNIK CAB. BANYUMAS',
    'SUB BAG TEKNIK CAB. PWKT 1','SUB BAG TEKNIK CAB. PWKT 2','SUB BAG TEKNIK CAB. WANGON',
    'SUB BAG TEKNOLOGI INFORMASI','SUB BAG UMUM CAB. AJIBARANG','SUB BAG UMUM CAB. BANYUMAS',
    'SUB BAG UMUM CAB. PWKT 1','SUB BAG UMUM CAB. PWKT 2','SUB BAG UMUM CAB. WANGON',
    'SUB BID MANAJEMEN INFORMASI','SUB BID PENGENDALIAN DOKUMEN','UNIT BISNIS AMDK'
);