-- Seed: profesi part 1/2 (Manajer + Supervisor, IDs 1-56)
INSERT INTO profesi (id, nama, detail, resiko, organisasi_id, jabatan_id, level_id, grade_id, is_deleted, created_at, created_by, updated_at, updated_by) VALUES
(1, 'Manajer Satuan Pengawas Intern', '-', '-', 5, 53, 5, 1, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 'Manajer Cabang Purwokerto 1', '-', '-', 8, 70, 5, 3, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 'Manajer Cabang Purwokerto 2', '-', '-', 9, 79, 5, 2, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 'Manajer Cabang Banyumas', '-', '-', 12, 106, 5, 2, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 'Manajer Cabang Wangon', '-', '-', 11, 97, 5, 1, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 'Manajer Cabang Ajibarang', '-', '-', 10, 88, 5, 1, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 'Manajer Unit Bisnis AMDK', '-', '-', 68, 119, 5, 1, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 'Manajer Kesekretariatan', '-', '-', 15, 40, 5, 1, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 'Manajer Keuangan', '-', '-', 13, 26, 5, 1, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 'Manajer Sumber Daya Manusia & TI', '-', '-', 16, 48, 5, 1, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 'Manajer Perlengkapan', '-', '-', 69, 118, 5, 2, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 'Manajer Perencanaan & Pengembangan', '-', '-', 17, 4, 5, 2, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 'Manajer Produksi & Distribusi 1', '-', '-', 18, 9, 5, 2, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 'Manajer Produksi & Distribusi 2', '-', '-', 19, 14, 5, 2, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 'Manajer Pengendalian Teknik', '-', '-', 20, 19, 5, 2, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 'Supervisor Audit Intern', '-', '-', 61, 56, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 'Supervisor Standardisasi', '-', '-', 60, 54, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 'Supervisor Adm & Keu Cab. Pwkt 1', '-', '-', 21, 71, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 'Supervisor Pelayanan Cab. Pwkt 1', '-', '-', 23, 75, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 'Supervisor Teknik Cab. Pwkt 1', '-', '-', 24, 77, 6, 6, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 'Supervisor Adm & Keu Cab. Pwkt 2', '-', '-', 25, 80, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 'Supervisor Pelayanan Cab. Pwkt 2', '-', '-', 27, 84, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 'Supervisor Teknik Cab. Pwkt 2', '-', '-', 28, 86, 6, 6, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 'Supervisor Adm & Keu Cab. Banyumas', '-', '-', 37, 107, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 'Supervisor Pelayanan Cab. Banyumas', '-', '-', 39, 111, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 'Supervisor Teknik Cab. Banyumas', '-', '-', 40, 113, 6, 6, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 'Supervisor Adm & Keu Cab. Wangon', '-', '-', 33, 98, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 'Supervisor Pelayanan Cab. Wangon', '-', '-', 35, 102, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 'Supervisor Teknik Cab. Wangon', '-', '-', 36, 104, 6, 6, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(30, 'Supervisor Adm & Keu Cab. Ajibarang', '-', '-', 29, 89, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(31, 'Supervisor Pelayanan Cab. Ajibarang', '-', '-', 31, 93, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(32, 'Supervisor Teknik Cab. Ajibarang', '-', '-', 32, 95, 6, 6, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(33, 'Supervisor Pemasaran', '-', '-', 45, 125, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(34, 'Supervisor Produksi', '-', '-', 75, 124, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(35, 'Supervisor Hukum & Perizinan', '-', '-', 46, 38, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(36, 'Supervisor Humas & Protokol', '-', '-', 44, 34, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(37, 'Supervisor Tata Usaha & Rumah Tangga', '-', '-', 47, 41, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(38, 'Supervisor Akuntansi', '-', '-', 42, 29, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(39, 'Supervisor Anggaran & Pelaporan', '-', '-', 41, 27, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(40, 'Supervisor Perbendaharaan', '-', '-', 43, 31, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(41, 'Supervisor Adm. & Pengembangan SDM', '-', '-', 50, 49, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(42, 'Supervisor Remunerasi & K3', '-', '-', 51, 51, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(43, 'Supervisor Teknologi Informasi', '-', '-', 65, 66, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(44, 'Supervisor Aset', '-', '-', 48, 44, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(45, 'Supervisor Pengadaan', '-', '-', 49, 46, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(46, 'Supervisor Persediaan', '-', '-', 74, 123, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(47, 'Supervisor Perencanaan', '-', '-', 52, 5, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(48, 'Supervisor Pengembangan', '-', '-', 63, 61, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(49, 'Supervisor Pengawasan Pekerjaan', '-', '-', 53, 7, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(50, 'Supervisor Pengendalian Produksi 1', '-', '-', 54, 10, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(51, 'Supervisor Pengendalian Distribusi 1', '-', '-', 56, 15, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(52, 'Supervisor Pengendalian Produksi 2', '-', '-', 72, 121, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(53, 'Supervisor Pengendalian Distribusi 2', '-', '-', 57, 17, 6, 5, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(54, 'Supervisor Mekanikal & Elektrikal', '-', '-', 58, 20, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(55, 'Supervisor Pengendalian Kehilangan Air', '-', '-', 64, 63, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(56, 'Supervisor Penjaminan Mutu Air', '-', '-', 55, 12, 6, 4, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');
