-- Seed: gaji_komponen part 1/3 (records 1-110 of 280)

INSERT INTO gaji_komponen (urut, profil_gaji_id, kode, nama, jenis_gaji, nilai, is_reference, formula, is_deleted, created_at, created_by, updated_at, updated_by) VALUES
(1, 1, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 1, 'REF_PTKP', 'Referensi Pendapatan Tidak Kena Pajak', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 1, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 1, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 1, 'REF_POT_TKK', 'Referensi Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 1, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 1, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 1, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 1, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 1, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 1, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 1, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 1, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 1, 'ASTEK', 'Astek', 'NONE', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 1, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 1, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 1, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 1, 'PHDP', 'PhDP', 'NONE', 21362814, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 1, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, 'PHDP * 0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 1, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 1, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 1, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 1, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, '( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 1, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, 'REF_JML_POT_KK * REF_POT_TKK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 1, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, '( PKP - ( 0.05 * PKP ) - REF_PTKP ) * 0.1', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 1, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 1, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 1, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 1, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(1, 2, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 2, 'REF_TUNJ_JABATAN', 'Referensi Tunjangan Jabatan', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 2, 'REF_TUNJ_BERAS', 'Referensi Tunjangan Beras', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 2, 'REF_TUNJ_KK', 'Referensi Tunjangan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 2, 'REF_TUNJ_AIR', 'Referensi Tunjangan Air', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 2, 'REF_PHDP', 'Referensi PHDP', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 2, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 2, 'REF_POT_TKK', 'Referensi Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 2, 'REF_PTKP', 'Referensi Pendapatan Tidak Kena Pajak', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 2, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 2, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 2, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '0.1 * GP ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 2, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, 'JML_ANAK *  ( 0.05 * GP )', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 2, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, 'REF_TUNJ_JABATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 2, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, 'JML_JIWA * REF_TUNJ_BERAS ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 2, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, 'REF_TUNJ_KK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 2, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, 'REF_TUNJ_AIR ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 2, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 2, 'ASTEK', 'Astek', 'NONE', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 2, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 2, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 2, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 2, 'PHDP', 'PhDP', 'NONE', 0, 0, 'REF_PHDP ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 2, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, 'PHDP * 0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 2, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 2, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 2, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 2, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, '( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 2, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, 'REF_JML_POT_KK * REF_POT_TKK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(30, 2, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, 'TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(31, 2, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(32, 2, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(33, 2, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(34, 2, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(1, 3, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 3, 'REF_TUNJ_JABATAN', 'Referensi Tunjangan Jabatan', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 3, 'REF_TUNJ_BERAS', 'Referensi Tunjangan Beras', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 3, 'REF_TUNJ_KK', 'Referensi Tunjangan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 3, 'REF_TUNJ_AIR', 'Referensi Tunjangan Air', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 3, 'REF_PHDP', 'Referensi PHDP', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 3, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 3, 'REF_PTKP', 'Referensi Pendapatan Tidak Kena Pajak', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 3, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 3, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 3, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '0.1 * GP ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 3, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, 'JML_ANAK *  ( 0.05 * GP )', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 3, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, 'REF_TUNJ_JABATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 3, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, 'JML_JIWA * REF_TUNJ_BERAS ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 3, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(16, 3, 'TUNJ_AIR', 'Tunjangan Air', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(17, 3, 'TUNJ_KESEHATAN', 'Tunjangan Kesehatan', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(18, 3, 'ASTEK', 'Astek', 'NONE', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.0489', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(19, 3, 'PKP', 'Pendapatan Kena Pajak', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + ASTEK ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(20, 3, 'TUNJ_PPH21', 'Tunjangan PPh 21', 'PEMASUKAN', 0, 0, '( PKP - ( 0.05 * PKP ) - REF_PTKP ) *  0.05', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(21, 3, 'PENGHASILAN_KOTOR', 'Penghasilan Kotor', 'NONE', 0, 0, 'GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS + TUNJ_KK + TUNJ_KESEHATAN + TUNJ_AIR + TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(22, 3, 'POT_PENSIUN', 'Iuran Pensiun', 'POTONGAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(23, 3, 'POT_ASTEK', 'Potongan Astek', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.02', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(24, 3, 'POT_RUDIN', 'Potongan Rumah Dinas', 'POTONGAN', 0, 0, 'REF_SEWA_RUMDIN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(25, 3, 'POT_JP', 'Potongan Jaminan Pensiun', 'POTONGAN', 0, 0, '( GP + TUNJ_SI + TUNJ_ANAK + TUNJ_JABATAN + TUNJ_BERAS ) * 0.01', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(26, 3, 'POT_ASKES', 'Potongan BPJS Kesehatan', 'POTONGAN', 0, 0, '( PENGHASILAN_KOTOR - TUNJ_PPH21 ) * 0.01 * REF_ASKES ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(27, 3, 'POT_TKK', 'Potongan TKK', 'POTONGAN', 0, 0, '( REF_JML_POT_KK / 22 ) * GP', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(28, 3, 'POT_PPH21', 'Potongan PPh 21', 'POTONGAN', 0, 0, 'TUNJ_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(29, 3, 'POTONGAN', 'Total Potongan', 'NONE', 0, 0, 'POT_PENSIUN +  POT_ASTEK + POT_RUDIN + POT_JP + POT_ASKES + POT_TKK + POT_PPH21 ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(30, 3, 'PENGHASILAN_BERSIH', 'Penghasilan Bersih', 'NONE', 0, 0, 'PENGHASILAN_KOTOR - POTONGAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(31, 3, 'PEMBULATAN', 'Pembulatan', 'NONE', 0, 0, '( CEIL( PENGHASILAN_BERSIH / 100 ) * 100 ) - PENGHASILAN_BERSIH ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(32, 3, 'PENGHASILAN_BERSIH_FINAL', 'Penghasilan Bersih Final', 'NONE', 0, 0, 'PENGHASILAN_BERSIH + PEMBULATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(1, 4, 'GP', 'Gaji Pokok', 'PEMASUKAN', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(2, 4, 'REF_TUNJ_JABATAN', 'Referensi Tunjangan Jabatan', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(3, 4, 'REF_TUNJ_BERAS', 'Referensi Tunjangan Beras', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(4, 4, 'REF_TUNJ_KK', 'Referensi Tunjangan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(5, 4, 'REF_TUNJ_AIR', 'Referensi Tunjangan Air', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(6, 4, 'REF_PHDP', 'Referensi PHDP', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(7, 4, 'REF_SEWA_RUMDIN', 'Referensi Sewa Rumah Dinas', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(8, 4, 'REF_PTKP', 'Referensi Pendapatan Tidak Kena Pajak', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(9, 4, 'REF_ASKES', 'Referensi Kode ASKES', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(10, 4, 'REF_JML_POT_KK', 'Referensi Jumlah Potongan Kegiatan Kerja', 'NONE', 0, 1, '#SYSTEM', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(11, 4, 'TUNJ_SI', 'Tunjangan Suami Istri', 'PEMASUKAN', 0, 0, '0.1 * GP ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(12, 4, 'TUNJ_ANAK', 'Tunjangan Anak', 'PEMASUKAN', 0, 0, 'JML_ANAK *  ( 0.05 * GP )', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(13, 4, 'TUNJ_JABATAN', 'Tunjangan Jabatan', 'PEMASUKAN', 0, 0, 'REF_TUNJ_JABATAN ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(14, 4, 'TUNJ_BERAS', 'Tunjangan Beras', 'PEMASUKAN', 0, 0, 'JML_JIWA * REF_TUNJ_BERAS ', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(15, 4, 'TUNJ_KK', 'Tunjangan Kegiatan Kerja', 'PEMASUKAN', 0, 0, '', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');
