-- Seed: profesi part 2/2 (Staf, IDs 57-146)
INSERT INTO profesi (id, nama, detail, resiko, organisasi_id, jabatan_id, level_id, grade_id, is_deleted, created_at, created_by, updated_at, updated_by) VALUES
(57, 'Staf Sub Bag. Audit Intern', '-', '-', 61, 57, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(58, 'Staf Sub Bag. Standardisasi', '-', '-', 60, 55, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(59, 'Staf Sub Bag. Adm & Keu Cab. Pwkt 1', '-', '-', 21, 72, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(60, 'Staf Sub Bag. Pelayanan Cab. Pwkt 1', '-', '-', 23, 76, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(61, 'Staf Sub Bag. Teknik Cab. Pwkt 1 (PTM)', '-', '-', 24, 78, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(62, 'Staf Sub Bag. Teknik Cab. Pwkt 1 (PMS)', '-', '-', 24, 78, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(63, 'Staf Sub Bag. Teknik Cab. Pwkt 1 (PJ)', '-', '-', 24, 78, 7, 11, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(64, 'Staf Sub Bag. Teknik Cab. Pwkt 1 (Adm RAB)', '-', '-', 24, 78, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(65, 'Staf Sub Bag. Teknik Cab. Pwkt 1 (Adm Kegiatan Teknik)', '-', '-', 24, 78, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(66, 'Staf Sub Bag. Adm & Keu Cab. Pwkt 2', '-', '-', 25, 81, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(67, 'Staf Sub Bag. Pelayanan Cab. Pwkt 2', '-', '-', 27, 85, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(68, 'Staf Sub Bag. Teknik Cab. Pwkt 2 (PTM)', '-', '-', 28, 87, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(69, 'Staf Sub Bag. Teknik Cab. Pwkt 2 (PMS)', '-', '-', 28, 87, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(70, 'Staf Sub Bag. Teknik Cab. Pwkt 2 (PJ)', '-', '-', 28, 87, 7, 11, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(71, 'Staf Sub Bag. Teknik Cab. Pwkt 2 (Adm RAB)', '-', '-', 28, 87, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(72, 'Staf Sub Bag. Teknik Cab. Pwkt 2 (Adm Kegiatan Teknik)', '-', '-', 28, 87, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(73, 'Staf Sub Bag. Adm & Keu Cab. Banyumas', '-', '-', 37, 108, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(74, 'Staf Sub Bag. Pelayanan Cab. Banyumas', '-', '-', 39, 112, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(75, 'Staf Sub Bag. Teknik Cab. Banyumas (PTM)', '-', '-', 40, 114, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(76, 'Staf Sub Bag. Teknik Cab. Banyumas (PMS)', '-', '-', 40, 114, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(77, 'Staf Sub Bag. Teknik Cab. Banyumas (PJ)', '-', '-', 40, 114, 7, 11, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(78, 'Staf Sub Bag. Teknik Cab. Banyumas (Adm RAB)', '-', '-', 40, 114, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(79, 'Staf Sub Bag. Teknik Cab. Banyumas (Adm Kegiatan Teknik)', '-', '-', 40, 114, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(80, 'Staf Sub Bag. Adm & Keu Cab. Wangon', '-', '-', 33, 99, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(81, 'Staf Sub Bag. Pelayanan Cab. Wangon', '-', '-', 35, 103, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(82, 'Staf Sub Bag. Teknik Cab. Wangon (PTM)', '-', '-', 36, 105, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(83, 'Staf Sub Bag. Teknik Cab. Wangon (PMS)', '-', '-', 36, 105, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(84, 'Staf Sub Bag. Teknik Cab. Wangon (PJ)', '-', '-', 36, 105, 7, 11, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(85, 'Staf Sub Bag. Teknik Cab. Wangon (Adm RAB)', '-', '-', 36, 105, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(86, 'Staf Sub Bag. Teknik Cab. Wangon (Adm Kegiatan Teknik)', '-', '-', 36, 105, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(87, 'Staf Sub Bag. Adm & Keu Cab. Ajibarang', '-', '-', 29, 90, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(88, 'Staf Sub Bag. Pelayanan Cab. Ajibarang', '-', '-', 31, 94, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(89, 'Staf Sub Bag. Teknik Cab. Ajibarang (PTM)', '-', '-', 32, 96, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(90, 'Staf Sub Bag. Teknik Cab. Ajibarang (PMS)', '-', '-', 32, 96, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(91, 'Staf Sub Bag. Teknik Cab. Ajibarang (PJ)', '-', '-', 32, 96, 7, 11, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(92, 'Staf Sub Bag. Teknik Cab. Ajibarang (Adm RAB)', '-', '-', 32, 96, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(93, 'Staf Sub Bag. Teknik Cab. Ajibarang (Adm Kegiatan Teknik)', '-', '-', 32, 96, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(94, 'Staf Sub Bag. AMDK (Admin)', '-', '-', 75, 126, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(95, 'Staf Sub Bag. AMDK', '-', '-', 75, 126, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(96, 'Staf Sub Bag. AMDK (Admin)', '-', '-', 45, 37, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(97, 'Staf Sub Bag. AMDK', '-', '-', 45, 37, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(98, 'Staf Sub Bag. Hukum & Perizinan', '-', '-', 46, 39, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(99, 'Staf Sub Bag. Humas & Protokol', '-', '-', 44, 35, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(100, 'Staf Sub Bag. Tata Usaha & Rumah Tangga', '-', '-', 47, 42, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(101, 'Kepala Satpam', '-', '-', 47, 43, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(102, 'Staf Sub Bag. Akuntansi', '-', '-', 42, 30, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(103, 'Staf Sub Bag. Anggaran & Pelaporan', '-', '-', 41, 28, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(104, 'Staf Sub Bag. Perbendaharaan', '-', '-', 43, 32, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(105, 'Staf Sub Bag. Adm. & Pengembangan SDM', '-', '-', 50, 50, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(106, 'Staf Sub Bag. Remunerasi & K3', '-', '-', 51, 52, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(107, 'Staf Sub Bag. Teknologi Informasi (Administrasi)', '-', '-', 65, 67, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(108, 'Staf Sub Bag. Teknologi Informasi (Programmer)', '-', '-', 65, 67, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(109, 'Staf Sub Bag. Teknologi Informasi (Performa Server, Hardware, jaringan & Mikrotik', '-', '-', 65, 67, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(110, 'Staf Sub Bag. Aset', '-', '-', 48, 45, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(111, 'Staf Sub Bag. Pengadaan', '-', '-', 49, 47, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(112, 'Staf Sub Bag. Persediaan', '-', '-', 74, 130, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(113, 'Staf Sub Bag. Perencanaan', '-', '-', 52, 6, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(114, 'Staf Sub Bag. Pengembangan', '-', '-', 63, 62, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(115, 'Staf Sub Bag. Pengawasan Pekerjaan', '-', '-', 53, 8, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(116, 'Staf. Sub Bag. Pengendalian Produksi 1 (Administrasi)', '-', '-', 54, 11, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(117, 'Staf. Sub Bag. Pengendalian Distribusi 1 (Administrasi)', '-', '-', 56, 16, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(118, 'Staf. Sub Bag. Pengendalian Produksi 1 (Teknik)', '-', '-', 54, 11, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(119, 'Staf. Sub Bag. Pengendalian Distribusi 1 (Teknik)', '-', '-', 56, 16, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(120, 'Staf Sub Bag. Pengendalian Produksi 2 (Administrasi)', '-', '-', 72, 128, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(121, 'Staf Sub Bag. Pengendalian Distribusi 2 (Adminsitrasi)', '-', '-', 57, 18, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(122, 'Staf Sub Bag. Pengendalian Produksi 2 (Teknik)', '-', '-', 72, 128, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(123, 'Staf Sub Bag. Pengendalian Distribusi 2 (Teknik)', '-', '-', 57, 18, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(124, 'Staf Sub Bag. Mekanikal & Elektrikal', '-', '-', 58, 21, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(125, 'Staf Sub Bag. Mekanikal & Elektrikal (Administrasi)', '-', '-', 58, 21, 7, 10, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(126, 'Mandor', '-', '-', 58, 22, 7, 8, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(127, 'Staf Sub Bag. Pengendalian Kehilangan Air', '-', '-', 64, 64, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
(128, 'Staf Sub Bag. Penjaminan Mutu Air', '-', '-', 55, 13, 7, 9, 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');
