-- V5_0_2__create_pegawai.sql
-- Pegawai domain: 1 entity table (pegawai) + 1 _AUD table.
-- Pegawai uses Long PK (extends IdsAbstract).

CREATE TABLE pegawai (
    id BIGINT NOT NULL AUTO_INCREMENT,
    biodata_id VARCHAR(255) NOT NULL,
    nipam VARCHAR(255) DEFAULT NULL,
    no_ktp VARCHAR(255) DEFAULT NULL,
    npwp VARCHAR(255) DEFAULT NULL,
    no_bpjs_ketenagakerjaan VARCHAR(255) DEFAULT NULL,
    no_bpjs_kesehatan VARCHAR(255) DEFAULT NULL,
    tanggal_masuk DATE DEFAULT NULL,
    tanggal_berakhir_kontrak DATE DEFAULT NULL,
    status_pegawai INT DEFAULT NULL,
    organisasi_id BIGINT DEFAULT NULL,
    jabatan_id BIGINT DEFAULT NULL,
    profesi_id BIGINT DEFAULT NULL,
    golongan_id BIGINT DEFAULT NULL,
    grade_id BIGINT DEFAULT NULL,
    status_kerja INT NOT NULL,
    tmt_kerja DATE DEFAULT NULL,
    ref_sk_capeg_id BIGINT DEFAULT NULL,
    tanggal_pengangkatan DATE DEFAULT NULL,
    tmt_pensiun DATE DEFAULT NULL,
    ref_sk_pegawai_id BIGINT DEFAULT NULL,
    tmt_pegawai DATE DEFAULT NULL,
    ref_sk_gol_id BIGINT DEFAULT NULL,
    tmt_golongan DATE DEFAULT NULL,
    ref_sk_jabatan_id BIGINT DEFAULT NULL,
    tmt_jabatan DATE DEFAULT NULL,
    ref_sk_mutasi_id BIGINT DEFAULT NULL,
    tmt_mutasi DATE DEFAULT NULL,
    ref_sk_gaji_berkala_id BIGINT DEFAULT NULL,
    tmt_gaji_berkala DATE DEFAULT NULL,
    gaji_profil_id BIGINT DEFAULT NULL,
    gaji_pendapatan_non_pajak_id BIGINT DEFAULT NULL,
    rumah_dinas_id BIGINT DEFAULT NULL,
    gaji_pokok DOUBLE DEFAULT NULL,
    is_askes BIT(1) NOT NULL DEFAULT 0,
    phdp DOUBLE DEFAULT NULL,
    jmlTanggungan INT DEFAULT NULL,
    mkg_tahun INT DEFAULT NULL,
    mkg_bulan INT DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    absensi_id BIGINT DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_by VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) DEFAULT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BIT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_pegawai_biodata (biodata_id),
    KEY idx_pegawai_organisasi (organisasi_id),
    KEY idx_pegawai_jabatan (jabatan_id),
    KEY idx_pegawai_profesi (profesi_id),
    KEY idx_pegawai_golongan (golongan_id),
    KEY idx_pegawai_grade (grade_id),
    KEY idx_pegawai_gaji_profil (gaji_profil_id),
    KEY idx_pegawai_kode_pajak (gaji_pendapatan_non_pajak_id),
    KEY idx_pegawai_rumah_dinas (rumah_dinas_id),
    CONSTRAINT fk_pegawai_biodata FOREIGN KEY (biodata_id) REFERENCES biodata(nik),
    CONSTRAINT fk_pegawai_organisasi FOREIGN KEY (organisasi_id) REFERENCES organisasi(id),
    CONSTRAINT fk_pegawai_jabatan FOREIGN KEY (jabatan_id) REFERENCES jabatan(id),
    CONSTRAINT fk_pegawai_profesi FOREIGN KEY (profesi_id) REFERENCES profesi(id),
    CONSTRAINT fk_pegawai_golongan FOREIGN KEY (golongan_id) REFERENCES golongan(id),
    CONSTRAINT fk_pegawai_grade FOREIGN KEY (grade_id) REFERENCES grade(id),
    CONSTRAINT fk_pegawai_gaji_profil FOREIGN KEY (gaji_profil_id) REFERENCES gaji_profil(id),
    CONSTRAINT fk_pegawai_kode_pajak FOREIGN KEY (gaji_pendapatan_non_pajak_id) REFERENCES gaji_pendapatan_non_pajak(id),
    CONSTRAINT fk_pegawai_rumah_dinas FOREIGN KEY (rumah_dinas_id) REFERENCES rumah_dinas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pegawai_AUD (
    id BIGINT NOT NULL,
    REV BIGINT NOT NULL,
    REVTYPE TINYINT DEFAULT NULL,
    biodata_id VARCHAR(255) DEFAULT NULL,
    nipam VARCHAR(255) DEFAULT NULL,
    no_ktp VARCHAR(255) DEFAULT NULL,
    npwp VARCHAR(255) DEFAULT NULL,
    no_bpjs_ketenagakerjaan VARCHAR(255) DEFAULT NULL,
    no_bpjs_kesehatan VARCHAR(255) DEFAULT NULL,
    tanggal_masuk DATE DEFAULT NULL,
    tanggal_berakhir_kontrak DATE DEFAULT NULL,
    status_pegawai INT DEFAULT NULL,
    organisasi_id BIGINT DEFAULT NULL,
    jabatan_id BIGINT DEFAULT NULL,
    profesi_id BIGINT DEFAULT NULL,
    golongan_id BIGINT DEFAULT NULL,
    grade_id BIGINT DEFAULT NULL,
    status_kerja INT DEFAULT NULL,
    tmt_kerja DATE DEFAULT NULL,
    ref_sk_capeg_id BIGINT DEFAULT NULL,
    tanggal_pengangkatan DATE DEFAULT NULL,
    tmt_pensiun DATE DEFAULT NULL,
    ref_sk_pegawai_id BIGINT DEFAULT NULL,
    tmt_pegawai DATE DEFAULT NULL,
    ref_sk_gol_id BIGINT DEFAULT NULL,
    tmt_golongan DATE DEFAULT NULL,
    ref_sk_jabatan_id BIGINT DEFAULT NULL,
    tmt_jabatan DATE DEFAULT NULL,
    ref_sk_mutasi_id BIGINT DEFAULT NULL,
    tmt_mutasi DATE DEFAULT NULL,
    ref_sk_gaji_berkala_id BIGINT DEFAULT NULL,
    tmt_gaji_berkala DATE DEFAULT NULL,
    gaji_profil_id BIGINT DEFAULT NULL,
    gaji_pendapatan_non_pajak_id BIGINT DEFAULT NULL,
    rumah_dinas_id BIGINT DEFAULT NULL,
    gaji_pokok DOUBLE DEFAULT NULL,
    is_askes BIT(1) DEFAULT NULL,
    phdp DOUBLE DEFAULT NULL,
    jmlTanggungan INT DEFAULT NULL,
    mkg_tahun INT DEFAULT NULL,
    mkg_bulan INT DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    absensi_id BIGINT DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    updated_by VARCHAR(255) DEFAULT NULL,
    is_deleted BIT(1) DEFAULT NULL,
    PRIMARY KEY (id, REV),
    KEY idx_pegawai_aud_rev (REV),
    CONSTRAINT fk_pegawai_aud_rev FOREIGN KEY (REV) REFERENCES revinfo(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
