/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.AlasanBerhentiAud;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlasanBerhentiAudRecord extends UpdatableRecordImpl<AlasanBerhentiAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.revtype</code>.
     */
    public void setRevtype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.revtype</code>.
     */
    public Byte getRevtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.nama</code>.
     */
    public void setNama(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.nama</code>.
     */
    public String getNama() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kepegawaian.alasan_berhenti_aud.notes</code>.
     */
    public void setNotes(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>kepegawaian.alasan_berhenti_aud.notes</code>.
     */
    public String getNotes() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlasanBerhentiAudRecord
     */
    public AlasanBerhentiAudRecord() {
        super(AlasanBerhentiAud.ALASAN_BERHENTI_AUD);
    }

    /**
     * Create a detached, initialised AlasanBerhentiAudRecord
     */
    public AlasanBerhentiAudRecord(Long id_, Integer rev, Byte revtype, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, String nama, String notes) {
        super(AlasanBerhentiAud.ALASAN_BERHENTI_AUD);

        setId(id_);
        setRev(rev);
        setRevtype(revtype);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setNama(nama);
        setNotes(notes);
        resetChangedOnNotNull();
    }
}
