/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.CutiKlaimDetail;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CutiKlaimDetailRecord extends UpdatableRecordImpl<CutiKlaimDetailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kepegawaian.cuti_klaim_detail.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_klaim_detail.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kepegawaian.cuti_klaim_detail.tanggal</code>.
     */
    public void setTanggal(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_klaim_detail.tanggal</code>.
     */
    public LocalDate getTanggal() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>kepegawaian.cuti_klaim_detail.ref_cuti_id</code>.
     */
    public void setRefCutiId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_klaim_detail.ref_cuti_id</code>.
     */
    public Long getRefCutiId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CutiKlaimDetailRecord
     */
    public CutiKlaimDetailRecord() {
        super(CutiKlaimDetail.CUTI_KLAIM_DETAIL);
    }

    /**
     * Create a detached, initialised CutiKlaimDetailRecord
     */
    public CutiKlaimDetailRecord(Long id_, LocalDate tanggal, Long refCutiId) {
        super(CutiKlaimDetail.CUTI_KLAIM_DETAIL);

        setId(id_);
        setTanggal(tanggal);
        setRefCutiId(refCutiId);
        resetChangedOnNotNull();
    }
}
