/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.CutiApprovalAud;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CutiApprovalAudRecord extends UpdatableRecordImpl<CutiApprovalAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.revtype</code>.
     */
    public void setRevtype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.revtype</code>.
     */
    public Byte getRevtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.approval_level</code>.
     */
    public void setApprovalLevel(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.approval_level</code>.
     */
    public Integer getApprovalLevel() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.approval_status</code>.
     */
    public void setApprovalStatus(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.approval_status</code>.
     */
    public Byte getApprovalStatus() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.notes</code>.
     */
    public void setNotes(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.notes</code>.
     */
    public String getNotes() {
        return (String) get(11);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.approver_id</code>.
     */
    public void setApproverId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.approver_id</code>.
     */
    public Long getApproverId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.cuti_pegawai_id</code>.
     */
    public void setCutiPegawaiId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.cuti_pegawai_id</code>.
     */
    public Long getCutiPegawaiId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>kepegawaian.cuti_approval_aud.jabatan_id</code>.
     */
    public void setJabatanId(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>kepegawaian.cuti_approval_aud.jabatan_id</code>.
     */
    public Long getJabatanId() {
        return (Long) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CutiApprovalAudRecord
     */
    public CutiApprovalAudRecord() {
        super(CutiApprovalAud.CUTI_APPROVAL_AUD);
    }

    /**
     * Create a detached, initialised CutiApprovalAudRecord
     */
    public CutiApprovalAudRecord(Long id_, Integer rev, Byte revtype, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, Integer approvalLevel, Byte approvalStatus, String notes, Long approverId, Long cutiPegawaiId, Long jabatanId) {
        super(CutiApprovalAud.CUTI_APPROVAL_AUD);

        setId(id_);
        setRev(rev);
        setRevtype(revtype);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setApprovalLevel(approvalLevel);
        setApprovalStatus(approvalStatus);
        setNotes(notes);
        setApproverId(approverId);
        setCutiPegawaiId(cutiPegawaiId);
        setJabatanId(jabatanId);
        resetChangedOnNotNull();
    }
}
