/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.GajiBatchPotonganTkk;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GajiBatchPotonganTkkRecord extends UpdatableRecordImpl<GajiBatchPotonganTkkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gaji_batch_potongan_tkk.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>gaji_batch_potongan_tkk.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>gaji_batch_potongan_tkk.batch_id</code>.
     */
    public void setBatchId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gaji_batch_potongan_tkk.batch_id</code>.
     */
    public String getBatchId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gaji_batch_potongan_tkk.nipam</code>.
     */
    public void setNipam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gaji_batch_potongan_tkk.nipam</code>.
     */
    public String getNipam() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gaji_batch_potongan_tkk.potongan</code>.
     */
    public void setPotongan(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gaji_batch_potongan_tkk.potongan</code>.
     */
    public Integer getPotongan() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GajiBatchPotonganTkkRecord
     */
    public GajiBatchPotonganTkkRecord() {
        super(GajiBatchPotonganTkk.GAJI_BATCH_POTONGAN_TKK);
    }

    /**
     * Create a detached, initialised GajiBatchPotonganTkkRecord
     */
    public GajiBatchPotonganTkkRecord(Long id_, String batchId, String nipam, Integer potongan) {
        super(GajiBatchPotonganTkk.GAJI_BATCH_POTONGAN_TKK);

        setId(id_);
        setBatchId(batchId);
        setNipam(nipam);
        setPotongan(potongan);
        resetChangedOnNotNull();
    }
}
