/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.enums.GajiKomponenAudJenisGaji;
import id.perumdamts.kepegawaian.jooq.tables.GajiKomponenAud;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GajiKomponenAudRecord extends UpdatableRecordImpl<GajiKomponenAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gaji_komponen_aud.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>gaji_komponen_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>gaji_komponen_aud.revtype</code>.
     */
    public void setRevtype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.revtype</code>.
     */
    public Byte getRevtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>gaji_komponen_aud.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>gaji_komponen_aud.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>gaji_komponen_aud.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gaji_komponen_aud.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>gaji_komponen_aud.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>gaji_komponen_aud.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>gaji_komponen_aud.formula</code>.
     */
    public void setFormula(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.formula</code>.
     */
    public String getFormula() {
        return (String) get(9);
    }

    /**
     * Setter for <code>gaji_komponen_aud.is_reference</code>.
     */
    public void setIsReference(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.is_reference</code>.
     */
    public Boolean getIsReference() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>gaji_komponen_aud.jenis_gaji</code>.
     */
    public void setJenisGaji(GajiKomponenAudJenisGaji value) {
        set(11, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.jenis_gaji</code>.
     */
    public GajiKomponenAudJenisGaji getJenisGaji() {
        return (GajiKomponenAudJenisGaji) get(11);
    }

    /**
     * Setter for <code>gaji_komponen_aud.kode</code>.
     */
    public void setKode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.kode</code>.
     */
    public String getKode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>gaji_komponen_aud.nama</code>.
     */
    public void setNama(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.nama</code>.
     */
    public String getNama() {
        return (String) get(13);
    }

    /**
     * Setter for <code>gaji_komponen_aud.nilai</code>.
     */
    public void setNilai(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.nilai</code>.
     */
    public Double getNilai() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>gaji_komponen_aud.urut</code>.
     */
    public void setUrut(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.urut</code>.
     */
    public Integer getUrut() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>gaji_komponen_aud.profil_gaji_id</code>.
     */
    public void setProfilGajiId(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>gaji_komponen_aud.profil_gaji_id</code>.
     */
    public Long getProfilGajiId() {
        return (Long) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GajiKomponenAudRecord
     */
    public GajiKomponenAudRecord() {
        super(GajiKomponenAud.GAJI_KOMPONEN_AUD);
    }

    /**
     * Create a detached, initialised GajiKomponenAudRecord
     */
    public GajiKomponenAudRecord(Long id_, Integer rev, Byte revtype, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, String formula, Boolean isReference, GajiKomponenAudJenisGaji jenisGaji, String kode, String nama, Double nilai, Integer urut, Long profilGajiId) {
        super(GajiKomponenAud.GAJI_KOMPONEN_AUD);

        setId(id_);
        setRev(rev);
        setRevtype(revtype);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setFormula(formula);
        setIsReference(isReference);
        setJenisGaji(jenisGaji);
        setKode(kode);
        setNama(nama);
        setNilai(nilai);
        setUrut(urut);
        setProfilGajiId(profilGajiId);
        resetChangedOnNotNull();
    }
}
