/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.Golongan;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GolonganRecord extends UpdatableRecordImpl<GolonganRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>golongan.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>golongan.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>golongan.golongan</code>.
     */
    public void setGolongan(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>golongan.golongan</code>.
     */
    public String getGolongan() {
        return (String) get(1);
    }

    /**
     * Setter for <code>golongan.pangkat</code>.
     */
    public void setPangkat(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>golongan.pangkat</code>.
     */
    public String getPangkat() {
        return (String) get(2);
    }

    /**
     * Setter for <code>golongan.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>golongan.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>golongan.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>golongan.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>golongan.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>golongan.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>golongan.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>golongan.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>golongan.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>golongan.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GolonganRecord
     */
    public GolonganRecord() {
        super(Golongan.GOLONGAN);
    }

    /**
     * Create a detached, initialised GolonganRecord
     */
    public GolonganRecord(Long id_, String golongan, String pangkat, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy) {
        super(Golongan.GOLONGAN);

        setId(id_);
        setGolongan(golongan);
        setPangkat(pangkat);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }
}
