/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.JabatanAud;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JabatanAudRecord extends UpdatableRecordImpl<JabatanAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jabatan_aud.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jabatan_aud.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jabatan_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jabatan_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jabatan_aud.revtype</code>.
     */
    public void setRevtype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>jabatan_aud.revtype</code>.
     */
    public Byte getRevtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>jabatan_aud.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>jabatan_aud.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>jabatan_aud.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>jabatan_aud.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>jabatan_aud.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jabatan_aud.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jabatan_aud.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>jabatan_aud.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>jabatan_aud.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>jabatan_aud.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>jabatan_aud.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>jabatan_aud.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jabatan_aud.kode</code>.
     */
    public void setKode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>jabatan_aud.kode</code>.
     */
    public String getKode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jabatan_aud.nama</code>.
     */
    public void setNama(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>jabatan_aud.nama</code>.
     */
    public String getNama() {
        return (String) get(10);
    }

    /**
     * Setter for <code>jabatan_aud.level_id</code>.
     */
    public void setLevelId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>jabatan_aud.level_id</code>.
     */
    public Long getLevelId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>jabatan_aud.organisasi_id</code>.
     */
    public void setOrganisasiId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>jabatan_aud.organisasi_id</code>.
     */
    public Long getOrganisasiId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>jabatan_aud.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>jabatan_aud.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JabatanAudRecord
     */
    public JabatanAudRecord() {
        super(JabatanAud.JABATAN_AUD);
    }

    /**
     * Create a detached, initialised JabatanAudRecord
     */
    public JabatanAudRecord(Long id_, Integer rev, Byte revtype, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, String kode, String nama, Long levelId, Long organisasiId, Long parentId) {
        super(JabatanAud.JABATAN_AUD);

        setId(id_);
        setRev(rev);
        setRevtype(revtype);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setKode(kode);
        setNama(nama);
        setLevelId(levelId);
        setOrganisasiId(organisasiId);
        setParentId(parentId);
        resetChangedOnNotNull();
    }
}
