/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.Jabatan;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JabatanRecord extends UpdatableRecordImpl<JabatanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kepegawaian.jabatan.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.version</code>.
     */
    public void setVersion(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.kode</code>.
     */
    public void setKode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.kode</code>.
     */
    public String getKode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.nama</code>.
     */
    public void setNama(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.nama</code>.
     */
    public String getNama() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.level_id</code>.
     */
    public void setLevelId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.level_id</code>.
     */
    public Long getLevelId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.organisasi_id</code>.
     */
    public void setOrganisasiId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.organisasi_id</code>.
     */
    public Long getOrganisasiId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>kepegawaian.jabatan.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>kepegawaian.jabatan.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JabatanRecord
     */
    public JabatanRecord() {
        super(Jabatan.JABATAN);
    }

    /**
     * Create a detached, initialised JabatanRecord
     */
    public JabatanRecord(Long id_, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, Integer version, String kode, String nama, Long levelId, Long organisasiId, Long parentId) {
        super(Jabatan.JABATAN);

        setId(id_);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setVersion(version);
        setKode(kode);
        setNama(nama);
        setLevelId(levelId);
        setOrganisasiId(organisasiId);
        setParentId(parentId);
        resetChangedOnNotNull();
    }
}
