/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.KartuIdentitasAud;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KartuIdentitasAudRecord extends UpdatableRecordImpl<KartuIdentitasAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.revtype</code>.
     */
    public void setRevtype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.revtype</code>.
     */
    public Byte getRevtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.nomor_kartu</code>.
     */
    public void setNomorKartu(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.nomor_kartu</code>.
     */
    public String getNomorKartu() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.notes</code>.
     */
    public void setNotes(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.notes</code>.
     */
    public String getNotes() {
        return (String) get(10);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.tanggal_expired</code>.
     */
    public void setTanggalExpired(LocalDate value) {
        set(11, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.tanggal_expired</code>.
     */
    public LocalDate getTanggalExpired() {
        return (LocalDate) get(11);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.tanggal_terima</code>.
     */
    public void setTanggalTerima(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.tanggal_terima</code>.
     */
    public LocalDate getTanggalTerima() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.nik</code>.
     */
    public void setNik(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.nik</code>.
     */
    public String getNik() {
        return (String) get(13);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas_aud.jenis_kitas_id</code>.
     */
    public void setJenisKitasId(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas_aud.jenis_kitas_id</code>.
     */
    public Long getJenisKitasId() {
        return (Long) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KartuIdentitasAudRecord
     */
    public KartuIdentitasAudRecord() {
        super(KartuIdentitasAud.KARTU_IDENTITAS_AUD);
    }

    /**
     * Create a detached, initialised KartuIdentitasAudRecord
     */
    public KartuIdentitasAudRecord(Long id_, Integer rev, Byte revtype, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, String nomorKartu, String notes, LocalDate tanggalExpired, LocalDate tanggalTerima, String nik, Long jenisKitasId) {
        super(KartuIdentitasAud.KARTU_IDENTITAS_AUD);

        setId(id_);
        setRev(rev);
        setRevtype(revtype);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setNomorKartu(nomorKartu);
        setNotes(notes);
        setTanggalExpired(tanggalExpired);
        setTanggalTerima(tanggalTerima);
        setNik(nik);
        setJenisKitasId(jenisKitasId);
        resetChangedOnNotNull();
    }
}
