/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.KartuIdentitas;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KartuIdentitasRecord extends UpdatableRecordImpl<KartuIdentitasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kepegawaian.kartu_identitas.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.version</code>.
     */
    public void setVersion(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.nomor_kartu</code>.
     */
    public void setNomorKartu(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.nomor_kartu</code>.
     */
    public String getNomorKartu() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.notes</code>.
     */
    public void setNotes(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.notes</code>.
     */
    public String getNotes() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.tanggal_expired</code>.
     */
    public void setTanggalExpired(LocalDate value) {
        set(10, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.tanggal_expired</code>.
     */
    public LocalDate getTanggalExpired() {
        return (LocalDate) get(10);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.tanggal_terima</code>.
     */
    public void setTanggalTerima(LocalDate value) {
        set(11, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.tanggal_terima</code>.
     */
    public LocalDate getTanggalTerima() {
        return (LocalDate) get(11);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.nik</code>.
     */
    public void setNik(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.nik</code>.
     */
    public String getNik() {
        return (String) get(12);
    }

    /**
     * Setter for <code>kepegawaian.kartu_identitas.jenis_kitas_id</code>.
     */
    public void setJenisKitasId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>kepegawaian.kartu_identitas.jenis_kitas_id</code>.
     */
    public Long getJenisKitasId() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KartuIdentitasRecord
     */
    public KartuIdentitasRecord() {
        super(KartuIdentitas.KARTU_IDENTITAS);
    }

    /**
     * Create a detached, initialised KartuIdentitasRecord
     */
    public KartuIdentitasRecord(Long id_, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, Integer version, String nomorKartu, String notes, LocalDate tanggalExpired, LocalDate tanggalTerima, String nik, Long jenisKitasId) {
        super(KartuIdentitas.KARTU_IDENTITAS);

        setId(id_);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setVersion(version);
        setNomorKartu(nomorKartu);
        setNotes(notes);
        setTanggalExpired(tanggalExpired);
        setTanggalTerima(tanggalTerima);
        setNik(nik);
        setJenisKitasId(jenisKitasId);
        resetChangedOnNotNull();
    }
}
