/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.PengalamanKerjaAud;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PengalamanKerjaAudRecord extends UpdatableRecordImpl<PengalamanKerjaAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.revtype</code>.
     */
    public void setRevtype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.revtype</code>.
     */
    public Byte getRevtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.disetujui</code>.
     */
    public void setDisetujui(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.disetujui</code>.
     */
    public Byte getDisetujui() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.disetujui_oleh</code>.
     */
    public void setDisetujuiOleh(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.disetujui_oleh</code>.
     */
    public String getDisetujuiOleh() {
        return (String) get(10);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.jabatan</code>.
     */
    public void setJabatan(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.jabatan</code>.
     */
    public String getJabatan() {
        return (String) get(11);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.lokasi</code>.
     */
    public void setLokasi(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.lokasi</code>.
     */
    public String getLokasi() {
        return (String) get(12);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.nama_perusahaan</code>.
     */
    public void setNamaPerusahaan(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.nama_perusahaan</code>.
     */
    public String getNamaPerusahaan() {
        return (String) get(13);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.notes</code>.
     */
    public void setNotes(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.notes</code>.
     */
    public String getNotes() {
        return (String) get(14);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.tahun_keluar</code>.
     */
    public void setTahunKeluar(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.tahun_keluar</code>.
     */
    public Integer getTahunKeluar() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.tahun_masuk</code>.
     */
    public void setTahunMasuk(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.tahun_masuk</code>.
     */
    public Integer getTahunMasuk() {
        return (Integer) get(16);
    }

    /**
     * Setter for
     * <code>kepegawaian.pengalaman_kerja_aud.tanggal_disetujui</code>.
     */
    public void setTanggalDisetujui(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for
     * <code>kepegawaian.pengalaman_kerja_aud.tanggal_disetujui</code>.
     */
    public LocalDateTime getTanggalDisetujui() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for
     * <code>kepegawaian.pengalaman_kerja_aud.tanggal_pengajuan</code>.
     */
    public void setTanggalPengajuan(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for
     * <code>kepegawaian.pengalaman_kerja_aud.tanggal_pengajuan</code>.
     */
    public LocalDateTime getTanggalPengajuan() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.type_perusahaan</code>.
     */
    public void setTypePerusahaan(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.type_perusahaan</code>.
     */
    public String getTypePerusahaan() {
        return (String) get(19);
    }

    /**
     * Setter for <code>kepegawaian.pengalaman_kerja_aud.biodata_id</code>.
     */
    public void setBiodataId(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>kepegawaian.pengalaman_kerja_aud.biodata_id</code>.
     */
    public String getBiodataId() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PengalamanKerjaAudRecord
     */
    public PengalamanKerjaAudRecord() {
        super(PengalamanKerjaAud.PENGALAMAN_KERJA_AUD);
    }

    /**
     * Create a detached, initialised PengalamanKerjaAudRecord
     */
    public PengalamanKerjaAudRecord(Long id_, Integer rev, Byte revtype, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, Byte disetujui, String disetujuiOleh, String jabatan, String lokasi, String namaPerusahaan, String notes, Integer tahunKeluar, Integer tahunMasuk, LocalDateTime tanggalDisetujui, LocalDateTime tanggalPengajuan, String typePerusahaan, String biodataId) {
        super(PengalamanKerjaAud.PENGALAMAN_KERJA_AUD);

        setId(id_);
        setRev(rev);
        setRevtype(revtype);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setDisetujui(disetujui);
        setDisetujuiOleh(disetujuiOleh);
        setJabatan(jabatan);
        setLokasi(lokasi);
        setNamaPerusahaan(namaPerusahaan);
        setNotes(notes);
        setTahunKeluar(tahunKeluar);
        setTahunMasuk(tahunMasuk);
        setTanggalDisetujui(tanggalDisetujui);
        setTanggalPengajuan(tanggalPengajuan);
        setTypePerusahaan(typePerusahaan);
        setBiodataId(biodataId);
        resetChangedOnNotNull();
    }
}
