/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.PrefRolePermission;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PrefRolePermissionRecord extends UpdatableRecordImpl<PrefRolePermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pref_role_permission.role_id</code>.
     */
    public void setRoleId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pref_role_permission.role_id</code>.
     */
    public String getRoleId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pref_role_permission.perm_name</code>.
     */
    public void setPermName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pref_role_permission.perm_name</code>.
     */
    public String getPermName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrefRolePermissionRecord
     */
    public PrefRolePermissionRecord() {
        super(PrefRolePermission.PREF_ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised PrefRolePermissionRecord
     */
    public PrefRolePermissionRecord(String roleId, String permName) {
        super(PrefRolePermission.PREF_ROLE_PERMISSION);

        setRoleId(roleId);
        setPermName(permName);
        resetChangedOnNotNull();
    }
}
