/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.PrefRole;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PrefRoleRecord extends UpdatableRecordImpl<PrefRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pref_role.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pref_role.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrefRoleRecord
     */
    public PrefRoleRecord() {
        super(PrefRole.PREF_ROLE);
    }

    /**
     * Create a detached, initialised PrefRoleRecord
     */
    public PrefRoleRecord(String id_) {
        super(PrefRole.PREF_ROLE);

        setId(id_);
        resetChangedOnNotNull();
    }
}
