/*
 * This file is generated by jOOQ.
 */
package id.perumdamts.kepegawaian.jooq.tables.records;


import id.perumdamts.kepegawaian.jooq.tables.RiwayatTerminasiAud;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RiwayatTerminasiAudRecord extends UpdatableRecordImpl<RiwayatTerminasiAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>riwayat_terminasi_aud.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.revtype</code>.
     */
    public void setRevtype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.revtype</code>.
     */
    public Byte getRevtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.changed_status</code>.
     */
    public void setChangedStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.changed_status</code>.
     */
    public Byte getChangedStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.masa_kerja</code>.
     */
    public void setMasaKerja(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.masa_kerja</code>.
     */
    public Integer getMasaKerja() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.nama</code>.
     */
    public void setNama(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.nama</code>.
     */
    public String getNama() {
        return (String) get(10);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.nama_golongan</code>.
     */
    public void setNamaGolongan(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.nama_golongan</code>.
     */
    public String getNamaGolongan() {
        return (String) get(11);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.nama_jabatan</code>.
     */
    public void setNamaJabatan(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.nama_jabatan</code>.
     */
    public String getNamaJabatan() {
        return (String) get(12);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.nama_organisasi</code>.
     */
    public void setNamaOrganisasi(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.nama_organisasi</code>.
     */
    public String getNamaOrganisasi() {
        return (String) get(13);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.nipam</code>.
     */
    public void setNipam(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.nipam</code>.
     */
    public String getNipam() {
        return (String) get(14);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.nomor_sk</code>.
     */
    public void setNomorSk(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.nomor_sk</code>.
     */
    public String getNomorSk() {
        return (String) get(15);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.notes</code>.
     */
    public void setNotes(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.notes</code>.
     */
    public String getNotes() {
        return (String) get(16);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.tahun_terminasi</code>.
     */
    public void setTahunTerminasi(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.tahun_terminasi</code>.
     */
    public Integer getTahunTerminasi() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.tanggal_terminasi</code>.
     */
    public void setTanggalTerminasi(LocalDate value) {
        set(18, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.tanggal_terminasi</code>.
     */
    public LocalDate getTanggalTerminasi() {
        return (LocalDate) get(18);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.alasan_terminasi_id</code>.
     */
    public void setAlasanTerminasiId(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.alasan_terminasi_id</code>.
     */
    public Long getAlasanTerminasiId() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.golongan_id</code>.
     */
    public void setGolonganId(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.golongan_id</code>.
     */
    public Long getGolonganId() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.jabatan_id</code>.
     */
    public void setJabatanId(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.jabatan_id</code>.
     */
    public Long getJabatanId() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.organisasi_id</code>.
     */
    public void setOrganisasiId(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.organisasi_id</code>.
     */
    public Long getOrganisasiId() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.pegawai_id</code>.
     */
    public void setPegawaiId(Long value) {
        set(23, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.pegawai_id</code>.
     */
    public Long getPegawaiId() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>riwayat_terminasi_aud.riwayat_sk_id</code>.
     */
    public void setRiwayatSkId(Long value) {
        set(24, value);
    }

    /**
     * Getter for <code>riwayat_terminasi_aud.riwayat_sk_id</code>.
     */
    public Long getRiwayatSkId() {
        return (Long) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RiwayatTerminasiAudRecord
     */
    public RiwayatTerminasiAudRecord() {
        super(RiwayatTerminasiAud.RIWAYAT_TERMINASI_AUD);
    }

    /**
     * Create a detached, initialised RiwayatTerminasiAudRecord
     */
    public RiwayatTerminasiAudRecord(Long id_, Integer rev, Byte revtype, Byte changedStatus, LocalDateTime createdAt, String createdBy, Boolean isDeleted, LocalDateTime updatedAt, String updatedBy, Integer masaKerja, String nama, String namaGolongan, String namaJabatan, String namaOrganisasi, String nipam, String nomorSk, String notes, Integer tahunTerminasi, LocalDate tanggalTerminasi, Long alasanTerminasiId, Long golonganId, Long jabatanId, Long organisasiId, Long pegawaiId, Long riwayatSkId) {
        super(RiwayatTerminasiAud.RIWAYAT_TERMINASI_AUD);

        setId(id_);
        setRev(rev);
        setRevtype(revtype);
        setChangedStatus(changedStatus);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setIsDeleted(isDeleted);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setMasaKerja(masaKerja);
        setNama(nama);
        setNamaGolongan(namaGolongan);
        setNamaJabatan(namaJabatan);
        setNamaOrganisasi(namaOrganisasi);
        setNipam(nipam);
        setNomorSk(nomorSk);
        setNotes(notes);
        setTahunTerminasi(tahunTerminasi);
        setTanggalTerminasi(tanggalTerminasi);
        setAlasanTerminasiId(alasanTerminasiId);
        setGolonganId(golonganId);
        setJabatanId(jabatanId);
        setOrganisasiId(organisasiId);
        setPegawaiId(pegawaiId);
        setRiwayatSkId(riwayatSkId);
        resetChangedOnNotNull();
    }
}
